### ISSUE TITLE
Disconnected from MQTT server core-mosquitto:1883

### ISSUE THREAD

**Issue by pipetboy** [home-assistant/addons#1648]
## The problem

Tonight my Mosquitto MQTT broker suddenly stopped. My system is a Raspberry Pi 3b+ with SSD. I run Zigbee2MQTT which does send messages, but they do not arrive in Hassio. Restarting does not resolve the issue.

Logs say:

Logger: homeassistant.components.mqtt
Source: components/mqtt/__init__.py:1004
Integration: MQTT (documentation, issues)
First occurred: 21:53:39 (2 occurrences)
Last logged: 22:12:29
Disconnected from MQTT server core-mosquitto:1883 (1) 

AND:

Logger: homeassistant.components.mqtt
Source: components/mqtt/__init__.py:1020
Integration: MQTT (documentation, issues)
First occurred: 21:54:01 (64 occurrences)
Last logged: 22:12:52

    Timed out waiting for mid 385
    Timed out waiting for mid 386
    Timed out waiting for mid 387
    Timed out waiting for mid 388
    Timed out waiting for mid 389

Everything is up to date, and no recent updates or major changes. 

## Environment

- Home Assistant Core release with the issue: 0.116.4
- Last working Home Assistant Core release (if known): 0.116.4
- Operating environment (OS/Container/Supervised/Core): Hassio
- Integration causing this issue: Mosquitto broker 5.1
- Link to integration documentation on our website: https://github.com/home-assistant/hassio-addons/blob/master/mosquitto/README.md

## Problem-relevant `configuration.yaml`

```yaml
logins:
  - username: XXXX
    password: XXXX
anonymous: false
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
```

## Traceback/Error logs

```txt
[22:12:38] INFO: Setup mosquitto configuration
[22:12:38] WARNING: SSL not enabled - No valid certs found!
[22:12:38] INFO: Found local users inside config
[22:12:39] INFO: Initialize Hass.io Add-on services
[22:12:39] INFO: Initialize Home Assistant discovery
[22:12:39] INFO: Start Mosquitto daemon
1603224759: mosquitto version 1.6.3 starting
1603224759: Config loaded from /etc/mosquitto.conf.
1603224759: Loading plugin: /usr/share/mosquitto/auth-plug.so
1603224759:  ├── Username/password checking enabled.
1603224759:  ├── TLS-PSK checking enabled.
1603224759:  └── Extended authentication not enabled.
1603224759: |-- *** auth-plug: startup
1603224759: Opening ipv4 listen socket on port 1883.
1603224759: Opening ipv6 listen socket on port 1883.
1603224759: Opening websockets listen socket on port 1884.
1603224759: Warning: Mosquitto should not be run as root/administrator.
1603224759: New connection from 172.30.XX.X on port 1883.
[INFO] found MQTT on local database
1603224761: New client connected from 172.30.XX.X as mqttjs_1cf06564 (p2, c1, k60, u'MQTT').
1603224761: New connection from 172.30.XX.X on port 1883.
[INFO] found homeassistant on local database
1603224762: New client connected from 172.30.XX.X as auto-3417D062-921B-87B4-9EB1-XXXXXXXXXXX (p2, c1, k60, u'homeassistant').
1603226559: Saving in-memory database to /data/mosquitto.db.


Zigbee2MQTT:error 2020-10-20 22:12:33: Not connected to MQTT server!



20-10-20 19:52:28 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-10-20 19:53:38 INFO (SyncWorker_2) [supervisor.docker.interface] Stop addon_core_mosquitto application
20-10-20 19:53:41 INFO (SyncWorker_2) [supervisor.docker.interface] Clean addon_core_mosquitto application
20-10-20 19:53:44 INFO (SyncWorker_5) [supervisor.docker.addon] Start Docker add-on homeassistant/armv7-addon-mosquitto with version 5.1
20-10-20 19:53:47 INFO (MainThread) [supervisor.services.modules.mqtt] Set core_mosquitto as service provider for mqtt
20-10-20 20:12:29 INFO (SyncWorker_5) [supervisor.docker.interface] Stop addon_core_mosquitto application
20-10-20 20:12:32 INFO (SyncWorker_5) [supervisor.docker.interface] Clean addon_core_mosquitto application
20-10-20 20:12:35 INFO (SyncWorker_7) [supervisor.docker.addon] Start Docker add-on homeassistant/armv7-addon-mosquitto with version 5.1
20-10-20 20:12:39 INFO (MainThread) [supervisor.services.modules.mqtt] Set core_mosquitto as service provider for mqtt
20-10-20 20:22:28 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-10-20 20:24:25 INFO (MainThread) [supervisor.snapshots] Found 2 snapshot files
```

## Additional information

I have no background in IT, but if there's anything I can do, please let me know.

Thank you for your support

**Comment by frenck** [comment]
Transferred the issue to the add-ons repo by request of @emontnemery

**Comment by baldfox** [comment]
I'm also experiencing such an issue. It's disconnecting and then reconnecting a short time after. It's causing issues with zigbee2mqtt .... Running hassio 0.118.3 and mosquitto add-on 5.1. 


2020-11-26 14:47:30 ERROR (Thread-5) [paho.mqtt.client] failed to receive on socket: [Errno 104] Connection reset by peer
2020-11-26 14:47:30 WARNING (Thread-5) [homeassistant.components.mqtt] Disconnected from MQTT server core-mosquitto:1883 (1)
2020-11-26 14:47:31 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on tele/bedroom/SENSOR: b'{"Time":"2020-11-26T09:44:39","ENERGY":{"TotalStartTime":"2020-08-27T19:52:36","Total":0.077,"Yesterday":0.024,"Today":0.010,"Power":1,"ApparentPower":4,"ReactivePower":4,"Factor":0.23,"Voltage":125,"Current":0.034}}'
2020-11-26 14:47:31 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on tele/bed/STATE: b'{"Time":"2020-11-26T09:44:40","Uptime":"1T01:04:00","UptimeSec":90240,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":12,"POWER":"ON","Wifi":{"AP":1,"SSId":"Cybertron","BSSId":"F0:9F:C2:FA:2D:96","Channel":11,"RSSI":66,"Signal":-67,"LinkCount":1,"Downtime":"0T00:00:03"}}'
2020-11-26 14:47:31 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on tele/bed/SENSOR: b'{"Time":"2020-11-26T09:44:40","ENERGY":{"TotalStartTime":"2019-05-15T08:31:12","Total":10.123,"Yesterday":0.089,"Today":0.043,"Period":1,"Power":16,"ApparentPower":29,"ReactivePower":24,"Factor":0.56,"Voltage":293,"Current":0.098}}'
2020-11-26 14:47:32 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on tele/brick/HASS_STATE: b'{"Version":"9.1.0(tasmota)","BuildDateTime":"2020-11-07T11:57:45","Module or Template":"Teckin","RestartReason":"Software/System restart","Uptime":"1T01:03:55","Hostname":"brick-4509","IPAddress":"192.168.2.91","RSSI":"86","Signal (dBm)":"-57","WiFi LinkCount":1,"WiFi Downtime":"0T00:00:03","MqttCount":13,"LoadAvg":19}'
2020-11-26 14:47:32 INFO (Thread-5) [homeassistant.components.mqtt] Connected to MQTT server core-mosquitto:1883 (0)
![image](https://user-images.githubusercontent.com/32448665/100342862-cc46dd80-3008-11eb-81ea-3ef9934d37f1.png)

**Comment by baldfox** [comment]
@pipetboy which integration did you remove? This is happening to me probably every other hour...

**Comment by baldfox** [comment]
Also my configuration for Mosquitto:


logins:
  - username: homeassistant
    password: **redacted**
anonymous: false
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
quiet_logs: true

**Comment by Autom3** [comment]
> @pipetboy which integration did you remove? This is happening to me probably every other hour...

I'm having the same problems here except it's every 2 minutes, I'm running Home Assistant OS on Rpi4 nothing special.
This basically renders most of my smart home useless. I'll try to see if I can revert to an older version of home assistant and see if that fixes anything.

This is (part of) the log from my homeassistant container:
```
2020-11-27 08:59:27 WARNING (Thread-5) [homeassistant.components.mqtt] Disconnected from MQTT server core-mosquitto:1883 (1)
2020-11-27 09:01:17 WARNING (Thread-5) [homeassistant.components.mqtt] Disconnected from MQTT server core-mosquitto:1883 (1)
2020-11-27 09:03:45 WARNING (Thread-5) [homeassistant.components.mqtt] Disconnected from MQTT server core-mosquitto:1883 (1)
2020-11-27 09:03:45 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2702081352] Unexpected error inside websocket API
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 197, in async_handle
    msg = await wsock.receive()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_ws.py", line 438, in receive
    await self.pong(msg.data)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_ws.py", line 293, in pong
    await self._writer.pong(message)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 667, in pong
    await self._send_frame(message, WSMsgType.PONG)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 650, in _send_frame
    self._write(header + message)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 660, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2020-11-27 09:06:04 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2690650800] Unexpected error inside websocket API
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 197, in async_handle
    msg = await wsock.receive()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_ws.py", line 438, in receive
    await self.pong(msg.data)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_ws.py", line 293, in pong
    await self._writer.pong(message)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 667, in pong
    await self._send_frame(message, WSMsgType.PONG)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 650, in _send_frame
    self._write(header + message)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 660, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2020-11-27 09:06:04 WARNING (Thread-5) [homeassistant.components.mqtt] Disconnected from MQTT server core-mosquitto:1883 (1)
```
This is (part of) the log from my mosquitto container:
```
1606467472: New client connected from 172.30.32.1 as 0v6EDSPQDwWrKtOzKJZiwN (p2, c1, k60, u'homeassistant').
1606467566: Client 0v6EDSPQDwWrKtOzKJZiwN has exceeded timeout, disconnecting.
1606467568: New connection from 172.30.32.1 on port 1883.
1606467568: New client connected from 172.30.32.1 as 0v6EDSPQDwWrKtOzKJZiwN (p2, c1, k60, u'homeassistant').
1606467661: Client 0v6EDSPQDwWrKtOzKJZiwN has exceeded timeout, disconnecting.
1606467678: New connection from 172.30.32.1 on port 1883.
1606467678: New client connected from 172.30.32.1 as 0v6EDSPQDwWrKtOzKJZiwN (p2, c1, k60, u'homeassistant').
1606467771: Client 0v6EDSPQDwWrKtOzKJZiwN has exceeded timeout, disconnecting.
1606467826: New connection from 172.30.32.1 on port 1883.
[INFO] found homeassistant on local database
1606467826: New client connected from 172.30.32.1 as 0v6EDSPQDwWrKtOzKJZiwN (p2, c1, k60, u'homeassistant').
```

**Comment by pipetboy** [comment]
I'm not sure what exactly did the trick.
I just removed a few things I didn't use anymore. Can't even remember details anymore... sorry

**Comment by zambujal** [comment]
My problem also... :D I give up on my raspberry... buying an nuc or just I let it stay in VM i386 ...My guess is less memory, so this sometimes stalls... then losing connection I tried everything !!!

**Comment by zambujal** [comment]
before it worked... but I did put a little more stuff in there...

**Comment by Autom3** [comment]
My problem was disk space actually, I've now upgraded to a bootable USB device and I've not had issues since.

**Comment by zambujal** [comment]
My problem was not space, I have 1 TB hard disk connected... :D 
My problems went away when I removed the exposed port to the raspberry... so I cut the outside world to the raspberry.

I thought on buying an NUC, so I tested with an virtual machine with homeassistant...
I put good ram (8 gb) to it... I have plenty 48 gb... :D and it was similar... sometimes... ok... then caput... I also put the other mqtt addon, even if it's harder to get it to work... but this also happened with it, less times...  (before the disconnection to the outside)

allmoust 24 hours working with 2 times more identities, I am adding remaking my network... an not a single problem. so my problem was indeed someone outside, or something...
