### ISSUE TITLE
Glances 501 Message: Unsupported method ('GET').

### ISSUE THREAD

**Issue by mjkl-gh** [home-assistant/addons#1711]
When opening the glances addon I get a Message: Unsupported method ('GET').

## Environment

- Add-on with the issue: glances
- Add-on release with the issue: 0.9.1
- Last working add-on release (if known): Unknown
- Operating environment (OS/Supervised): Supervised

## Problem-relevant configuration

```yaml
log_level: info
process_info: false
refresh_time: 10
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
influxdb:
  enabled: false
  host: a0d7b954-influxdb
  port: 8086
  username: glances
  password: ''
  database: glances
  prefix: localhost
  interval: 60
```

## Traceback/Error logs

```txt
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
[13/Dec/2020:16:20:53 +0000] 501 127.0.0.1, 172.30.32.1(172.30.32.2) GET / HTTP/1.1 (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36)
Glances Web User Interface started on http://127.0.0.1:61209/
Traceback (most recent call last):
  File "/usr/bin/glances", line 11, in <module>
    load_entry_point('Glances==3.1.5', 'console_scripts', 'glances')()
  File "/usr/lib/python3.8/site-packages/glances/__init__.py", line 143, in main
    start(config=config, args=args)
  File "/usr/lib/python3.8/site-packages/glances/__init__.py", line 112, in start
    mode.serve_forever()
  File "/usr/lib/python3.8/site-packages/glances/webserver.py", line 48, in serve_forever
    self.web.start(self.stats)
  File "/usr/lib/python3.8/site-packages/glances/outputs/glances_bottle.py", line 216, in start
    self._app.run(host=self.args.bind_address,
  File "/usr/bin/bottle.py", line 761, in run
    run(self, **kwargs)
  File "/usr/bin/bottle.py", line 3137, in run
    server.run(app)
  File "/usr/bin/bottle.py", line 2789, in run
    srv = make_server(self.host, self.port, app, server_cls, handler_cls)
  File "/usr/lib/python3.8/wsgiref/simple_server.py", line 154, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address in use
[13/Dec/2020:16:21:43 +0000] 501 192.168.10.23, 172.30.32.1(172.30.32.2) GET / HTTP/1.1 (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36)
```

## Additional information

The error message suggests glances is trying to use a port that's already in use. However, it's in its own docker container with no ports allocated so I'm unsure how that is possible

**Comment by mjkl-gh** [comment]
wrong repo
