### ISSUE TITLE
deCONZ: Smart Plugs not available in HA since latest HA updates

### ISSUE THREAD

**Issue by Weygert** [home-assistant/addons#1762]
## The problem
Since the recent update to Home Assistant 2021.1.1, my two smart plugs (Lidl Silvercrest and LEDVANCE Smart+ Plug) are shown being unavailable in HA, whereas in Phoscon, they are available and can be switched. My sensors connected through the Conbee II USB Stick are working properly.

## Environment
- Add-on with the issue: deCONZ
- Add-on release with the issue: 6.6.2
- Last working add-on release (if known): not sure if upgrade of HA or deCONZ created the issue, always keep both up to date
- Operating environment (OS/Supervised): Home Assistant 2021.1.1 (Home Assistant OS 5.10, Supervisor 2020.12.7)

## Problem-relevant configuration
```yaml

```

## Traceback/Error logs
```txt
2021-01-13 16:52:36 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_2
2021-01-13 17:40:00 ERROR (MainThread) [pydeconz.websocket] Client connection error
2021-01-13 17:40:15 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 17:43:18 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_2
2021-01-13 17:43:19 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_2
2021-01-13 17:43:19 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 17:43:20 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 17:43:21 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 17:43:21 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 17:43:22 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 17:43:22 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 17:43:22 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 17:43:23 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 17:43:23 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 17:43:23 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 17:43:24 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 17:43:48 ERROR (MainThread) [pydeconz.websocket] Client connection error
2021-01-13 17:44:03 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 17:44:31 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_2
2021-01-13 17:44:32 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[17:49:06] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2021-01-13 17:51:57 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_2
2021-01-13 17:51:59 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 18:25:25 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_2
2021-01-13 18:25:28 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 18:25:29 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 18:25:30 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_2
2021-01-13 18:25:31 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 18:25:31 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 18:25:32 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 18:25:32 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 18:25:33 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 18:25:33 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 18:25:35 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 18:27:03 ERROR (MainThread) [pydeconz.websocket] Client connection error
2021-01-13 18:27:21 ERROR (MainThread) [pydeconz.websocket] Client connection error
2021-01-13 18:27:39 ERROR (MainThread) [pydeconz.websocket] Client connection error
2021-01-13 18:27:57 ERROR (MainThread) [pydeconz.websocket] Client connection error
2021-01-13 18:28:15 ERROR (MainThread) [pydeconz.websocket] Client connection error
2021-01-13 18:28:33 ERROR (MainThread) [pydeconz.websocket] Client connection error
2021-01-13 18:28:52 ERROR (MainThread) [pydeconz.websocket] Client connection error
2021-01-13 18:29:10 ERROR (MainThread) [pydeconz.websocket] Client connection error
2021-01-13 18:29:28 ERROR (MainThread) [pydeconz.websocket] Client connection error
2021-01-13 18:29:46 ERROR (MainThread) [pydeconz.websocket] Client connection error
2021-01-13 18:30:01 ERROR (MainThread) [pydeconz.websocket] Client connection error
2021-01-13 18:30:16 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 19:45:32 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 19:45:32 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
2021-01-13 19:45:37 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 57, in _handle
    return await self._handle_request(request, token, path)
  File "/usr/src/homeassistant/homeassistant/components/hassio/ingress.py", line 152, in _handle_request
    await response.prepare(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_response.py", line 378, in prepare
    return await self._start(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_response.py", line 386, in _start
    await self._write_headers()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_response.py", line 458, in _write_headers
    await writer.write_headers(status_line, self._headers)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/http_writer.py", line 119, in write_headers
    self._write(buf)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2021-01-13 19:46:32 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.on_off_plug_in_unit_3
```

## Additional information
- deCONZ plugin also seems to be more unstable. From time to time get the info, that the gateway isn't reachable. Seconds later it's loading properly again.

- In HA/Settings/Entities I see an entity of deCONZ beong "restored". Can I delete it?!
![2021-01-13_201121](https://user-images.githubusercontent.com/20655714/104498472-0598d400-55dc-11eb-91cd-3037ca168420.png)

- There seems to be major disruption in the history since the last system update for many entities (though not all). This seems to be the point where the two plugs stopped working. Sensor data is shown also prior to that date (Jan 10th, ~10a.m.)
![2021-01-13_193936](https://user-images.githubusercontent.com/20655714/104498890-9374bf00-55dc-11eb-8784-3124a79c256b.png)

**Comment by huuub** [comment]
Having exactly the same issue...
