### ISSUE TITLE
Z-Wave JS Cover

### ISSUE THREAD

**Issue by foXaCe** [home-assistant/addons#1809]
cover do not work correctly

Logger: homeassistant.components.websocket_api.http.connection
Source: components/zwave_js/cover.py:83
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 18:33:12 (1 occurrences)
Last logged: 18:33:12

[548089187728] None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 136, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 595, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 632, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/cover.py", line 83, in async_open_cover
    await self.info.node.async_set_value(target_value, PRESS_BUTTON)
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/model/node.py", line 248, in async_set_value
    val = self.values[val]
KeyError: None

**Comment by frenck** [comment]
This is not an error message from the add-on, but from the Home Assistant Core.

Please report your issue here: <https://github.com/home-assistant/core/issues/>

**Comment by natekspencer** [comment]
Also, it's a duplicate of https://github.com/home-assistant/core/issues/45922
