### ISSUE TITLE
ERROR (MainThread) [supervisor.jobs] Unhandled exception: Remote 'origin' has no refspec set.

### ISSUE THREAD

**Issue by hudingjing244** [home-assistant/addons#1930]
## The problem
When i reload add-on store,the git problem appear.
The error log adivise me to  set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"',but i don't know where the local git repository is.

## Environment

![image](https://user-images.githubusercontent.com/18326709/111778234-53d59680-88ef-11eb-8c7a-84ad93e9e7c8.png)

## Traceback/Error logs
<--
  21-03-19 11:57:33 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
21-03-19 11:57:33 ERROR (MainThread) [supervisor.jobs] Unhandled exception: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"'.
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 100, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/git/remote.py", line 787, in fetch
    self._assert_refspec()
  File "/usr/local/lib/python3.8/site-packages/git/remote.py", line 753, in _assert_refspec
    raise AssertionError(msg % (self.name, self.name))
AssertionError: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"'.
21-03-19 11:57:33 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-3392' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:105> exception=JobException()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 100, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/git/remote.py", line 787, in fetch
    self._assert_refspec()
  File "/usr/local/lib/python3.8/site-packages/git/remote.py", line 753, in _assert_refspec
    raise AssertionError(msg % (self.name, self.name))
AssertionError: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"'.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 109, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    raise JobException() from err
supervisor.exceptions.JobException
21-03-19 11:57:33 INFO (MainThread) [supervisor.store] Loading add-ons from store: 1 all - 0 new - 0 remove
21-03-19 11:57:33 INFO (MainThread) [supervisor.store] Loading add-ons from store: 1 all - 0 new - 0 remove
21-03-19 11:57:56 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
21-03-19 11:57:56 ERROR (MainThread) [supervisor.jobs] Unhandled exception: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"'.
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 100, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/git/remote.py", line 787, in fetch
    self._assert_refspec()
  File "/usr/local/lib/python3.8/site-packages/git/remote.py", line 753, in _assert_refspec
    raise AssertionError(msg % (self.name, self.name))
AssertionError: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"'.
21-03-19 11:57:56 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-3417' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:105> exception=JobException()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 100, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/git/remote.py", line 787, in fetch
    self._assert_refspec()
  File "/usr/local/lib/python3.8/site-packages/git/remote.py", line 753, in _assert_refspec
    raise AssertionError(msg % (self.name, self.name))
AssertionError: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"'.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 109, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    raise JobException() from err
supervisor.exceptions.JobException
21-03-19 11:57:56 INFO (MainThread) [supervisor.store] Loading add-ons from store: 1 all - 0 new - 0 remove
-->

**Comment by countrysideboy** [comment]
21-06-22 00:29:58 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
21-06-22 00:29:58 ERROR (MainThread) [supervisor.jobs] Unhandled exception: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"'.
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 105, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 818, in fetch
    self._assert_refspec()
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 782, in _assert_refspec
    raise AssertionError(msg % (self.name, self.name))
AssertionError: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"'.
21-06-22 00:29:58 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-187372' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:106> exception=JobException()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 105, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 818, in fetch
    self._assert_refspec()
  File "/usr/local/lib/python3.9/site-packages/git/remote.py", line 782, in _assert_refspec
    raise AssertionError(msg % (self.name, self.name))
AssertionError: Remote 'origin' has no refspec set.
You can set it as follows: 'git config --add "remote.origin.fetch +refs/heads/*:refs/heads/*"'.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 110, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 111, in wrapper
    raise JobException() from err
supervisor.exceptions.JobException

**Comment by ludeeus** [comment]
This is not an add-on issue, if you still see this open an issue with the Supervisor https://github.com/home-assistant/supervisor/issues/new?assignees=&labels=bug&template=bug_report.yml 👍
