### ISSUE TITLE
Losing Zigbee after upgrade to core-2021.4.6

### ISSUE THREAD

**Issue by JeffPixelSplash** [home-assistant/addons#1987]
I have a sonoff wireless bridge that's been rock steady until I upgraded.  Now, I lost contact with Zigbee every few hours requiring a core restart to get it going again.  From my logs, I see entires like this:
```
021-04-27 20:14:23 WARNING (MainThread) [bellows.zigbee.application] Watchdog heartbeat timeout: 
2021-04-27 20:14:33 ERROR (bellows.thread_0) [bellows.uart] CRC error in frame b'c202c20251a8bd7e' (b'a8bd' != b'ef7e')
2021-04-27 20:14:33 ERROR (MainThread) [bellows.ezsp] NCP entered failed state. Requesting APP controller restart
```
Or this
```
2021-04-27 20:20:51 WARNING (bellows.thread_0) [bellows.uart] Reset future is None
2021-04-27 20:20:52 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback ThreadsafeProxy.__getattr__.<locals>.func_wrapper.<locals>.check_result_wrapper() at /usr/local/lib/python3.8/site-packages/bellows/thread.py:97
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/site-packages/bellows/thread.py", line 98, in check_result_wrapper
    result = call()
  File "/usr/local/lib/python3.8/site-packages/bellows/ezsp/__init__.py", line 254, in frame_received
    self._protocol(data)
  File "/usr/local/lib/python3.8/site-packages/bellows/ezsp/protocol.py", line 102, in __call__
    frame_name = self.COMMANDS_BY_ID[frame_id][0]
KeyError: 520
2021-04-27 20:21:03 ERROR (bellows.thread_0) [bellows.uart] Lost serial connection: read failed: [Errno 104] Connection reset by peer
2021-04-27 20:21:03 ERROR (MainThread) [bellows.ezsp] NCP entered failed state. Requesting APP controller restart
```
Is anyone else seeing this?  Am I looking at downgrading here?  So far my wife is tolerating this but I really need to get this working properly again somehow.

Thoughts anyone?

**Comment by JeffPixelSplash** [comment]
Issue may be with Tasmota 9.4.0.1  - Closing pending more investigation
