### ISSUE TITLE
Z-wave JS: activate watchdog generate errors in supervisor log

### ISSUE THREAD

**Issue by wpeeters** [home-assistant/addons#2047]
## The problem

When the watchdog for Z-wave JS is active, I get every 2 minutes error messages in the supervisor log.
If turned off, no errors appear.
## Environment

- Add-on with the issue: Z-wave JS
- Add-on release with the issue: 0.1.24
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): OS (HA Blue device)

## Problem-relevant configuration

```yaml
device: /dev/serial/by-id/usb-0658_0200-if00
network_key: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
log_level: debug

```

## Traceback/Error logs

```txt
21-05-28 18:32:43 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-863006' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=TypeError('an integer is required (got type str)')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 416, in _watchdog_addon_application
    if addon.in_progress or await addon.watchdog_application():
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 479, in watchdog_application
    return await self.sys_run_in_executor(check_port, self.ip_address, port)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 43, in check_port
    result = sock.connect_ex((str(address), port))
TypeError: an integer is required (got type str)
```

## Additional information

No error messages in the Z-wave JS log

**Comment by wpeeters** [comment]
Installed 2021.6.1 (and now also 2021.6.3) => errors in the log are gone.
