### ISSUE TITLE
Zwave-JS error not starting up zwave-js integration

### ISSUE THREAD

**Issue by canedje** [home-assistant/addons#2206]
## The problem

Zwave-JS integration not starting up and giving error after update zwave-js addon to version: 0.1.41

I think something to do with network key.
In version 1.41 there are 4 keys and differnet then mine original

Logger: homeassistant.config_entries
Source: components/zwave_js/__init__.py:590
First occurred: 8:08:40 (1 occurrences)
Last logged: 8:08:40

Error setting up entry Z-Wave JS for zwave_js
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/__init__.py", line 121, in async_setup_entry
    await async_ensure_addon_running(hass, entry)
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/__init__.py", line 590, in async_ensure_addon_running
    addon_network_key = addon_options[CONF_ADDON_NETWORK_KEY]
KeyError: 'network_key'

## Environment

- Add-on with the issue: zwave-js
- Add-on release with the issue: version: 0.1.41
- Last working add-on release (if known): 0.1.40
- Operating environment (OS/Supervised): Supervised

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

Logger: homeassistant.config_entries
Source: components/zwave_js/__init__.py:590
First occurred: 8:08:40 (1 occurrences)
Last logged: 8:08:40

Error setting up entry Z-Wave JS for zwave_js
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/__init__.py", line 121, in async_setup_entry
    await async_ensure_addon_running(hass, entry)
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/__init__.py", line 590, in async_ensure_addon_running
    addon_network_key = addon_options[CONF_ADDON_NETWORK_KEY]
KeyError: 'network_key'

```txt

```

## Additional information
![image](https://user-images.githubusercontent.com/23150947/135397688-e3ea2798-0caa-4e23-8aac-ea40285a5222.png)
Before update
 
![image](https://user-images.githubusercontent.com/23150947/135399560-1fd2f38a-6948-4977-8ebe-d3c183640e47.png)

After  update
 
![image](https://user-images.githubusercontent.com/23150947/135399704-71597552-6f32-4697-9858-ea0f42e1615e.png)

After restart HA:
 
![image](https://user-images.githubusercontent.com/23150947/135399727-8d13b535-8f2e-4fbd-9a18-6f605f23c8ae.png)

**Comment by MartinHjelmare** [comment]
Thanks for the report. This should be fixed in add-on version 0.1.42. Please try to update the add-on to that version and check if it solves the problem. Thanks!

**Comment by sthmn** [comment]
Hi
I have loaded 0.1.41 and 0.1.42 and continue to have this issue.

2021-09-29 22:41:15 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 18280a61f3ca5e0e8644f65c0839673c516eeaf66eb12d1baf311ce127b8d8b8 from 10.0.183.45
2021-09-29 22:41:24 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Z-Wave JS for zwave_js
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/usr/src/homeassistant/homeassistant/components/zwave_js/__init__.py", line 121, in async_setup_entry
await async_ensure_addon_running(hass, entry)
File "/usr/src/homeassistant/homeassistant/components/zwave_js/__init__.py", line 590, in async_ensure_addon_running
addon_network_key = addon_options[CONF_ADDON_NETWORK_KEY]
KeyError: 'network_key'

**Comment by sthmn** [comment]
I did a full reboot of the host system and it is now working.

**Comment by canedje** [comment]
How can I do install version 1.42? I do use HACS
