### ISSUE TITLE
Z-Wave JS version: 0.1.44 Error: Invalid key format for securityKeys.S0_Legacy option

### ISSUE THREAD

**Issue by radionerd1** [home-assistant/addons#2212]
Updated version to latest version:
0.1.44
 Fix casing issues with security keys
 Fix emulate_hardware configuration option

No connection and Z-Wave JS is pulling constant +25% CPU 

Rolled back to zwave_js_0.1.41:
Same Error

Rolled back to zwave_js_0.1.40:
Restarted Server Management System, now all z-wave devices are back to normal (abby-normal ;-)
 

10:13:45] INFO: Both 'network_key' and 's0_legacy_key' are set and match. All ok.
[cont-init.d] config.sh: exited 0.
[cont-init.d] structure.sh: executing... 
[cont-init.d] structure.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:13:47] INFO: Successfully send discovery information to Home Assistant.

[10:06:54] INFO: Successfully send discovery information to Home Assistant.
Error: failed loading config file /etc/zwave_config.json
Error: Invalid key format for securityKeys.S0_Legacy option
    at normalizeKey (/usr/src/node_modules/@zwave-js/server/dist/bin/server.js:17:11)
    at /usr/src/node_modules/@zwave-js/server/dist/bin/server.js:60:53
    at Object.<anonymous> (/usr/src/node_modules/@zwave-js/server/dist/bin/server.js:119:3)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

**Comment by PachangaDad** [comment]
I'm also receiving the following repeating errors, even after coming current to latest version 0.1.145 "Z-Wave JS" add-on on HA. Before everything was fine and connected to my devices.

[18:13:24] INFO: Successfully send discovery information to Home Assistant.
Error: failed loading config file /etc/zwave_config.json
Error: Invalid key format for securityKeys.S0_Legacy option
    at normalizeKey (/usr/src/node_modules/@zwave-js/server/dist/bin/server.js:17:11)
    at /usr/src/node_modules/@zwave-js/server/dist/bin/server.js:60:53
    at Object.<anonymous> (/usr/src/node_modules/@zwave-js/server/dist/bin/server.js:119:3)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47


My Network Key and S0_legacy_key look identical:

0X6B, 0XA9, 0X18, 0XB0, 0XB2, 0XD6, 0X11, 0X5E, 0X14, 0XD0, 0XCA, 0X58, 0X85, 0X93, 0X63, 0X94

Any suggestions for correction? or guidance for correct format needed?
Everything was fine until recently.
Thanks

**Comment by MartinHjelmare** [comment]
Try replacing the capital `X` in `, 0X` with `x`. If the key above was your actual key you should now create a new key since the key above is on the internet now.

**Comment by PachangaDad** [comment]
Thank you! It worked All is well again
