### ISSUE TITLE
HomeMatic starting issue (thread locked)

### ISSUE THREAD

**Issue by sander76** [home-assistant/addons#2305]
### Describe the issue you are experiencing

Not sure whether it is related, but after my hass os update to version 7 I am unable to start my Homematic addon anymore, which was working fine previously.

I am watching the startup log and see messages like below:

```
WARNING: Thread Thread[vert.x-eventloop-thread-4,5,main] has been blocked for 7798 ms, time limit is 2000
io.vertx.core.VertxException: Thread blocked
```

The list with these warnings is pretty long, unable to view the start of the error messages, not being sure whether the above is a cause or a result of another error.

hassio core: 2021.11.5
supervisor: 2021.12.1
hass os: 7.0

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

HomeMatic CCU

### What is the version of the add-on?

11.3.0

### Steps to reproduce the issue

After updating to hassos 7 a restart of the system results in the error.

### Anything in the Supervisor logs that might be useful for us?

```txt
21-12-13 08:41:39 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on homeassistant/armv7-addon-homematic with version 11.3.0
21-12-13 08:54:10 INFO (SyncWorker_3) [supervisor.docker.interface] Stopping addon_core_homematic application
21-12-13 08:54:15 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_core_homematic application
```
```


### Anything in the add-on logs that might be useful for us?

```txt
WARNING: Thread Thread[vert.x-eventloop-thread-4,5,main] has been blocked for 9799 ms, time limit is 2000
io.vertx.core.VertxException: Thread blocked
	at java.base@11.0.11/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.11/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.base@11.0.11/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
	at java.base@11.0.11/java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:458)
	at app//de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega.registerCallback(VirtualDeviceHandlerRega.java:99)
	at java.base@11.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.11/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.11/java.lang.reflect.Method.invoke(Method.java:566)
	at app//de.eq3.cbcs.legacy.communication.rpc.internal.rpc.AnnotationAwareRpcHandler.execute(AnnotationAwareRpcHandler.java:80)
	at app//de.eq3.ccu.server.internal.RpcMessageHandler.handle(RpcMessageHandler.java:70)
	at app//de.eq3.ccu.server.internal.RpcMessageHandler.handle(RpcMessageHandler.java:24)
	at app//io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
	at app//io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191)
	at app//io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:505)
	at app//io.vertx.core.eventbus.impl.EventBusImpl$$Lambda$107/0x6dbbac28.handle(Unknown Source)
	at app//io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at app//io.vertx.core.impl.ContextImpl$$Lambda$88/0x6db66428.run(Unknown Source)
	at app//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.base@11.0.11/java.lang.Thread.run(Thread.java:829)
2021-12-13 08:42:45,679 [INFO] LegacyServiceHandler - (un)registerCallback on LegacyServiceHandler called from url: xmlrpc_bin://127.0.0.1:1999
```
```


### Additional information

_No response_

**Comment by sander76** [comment]
For now switching over to raspverry matic : https://github.com/jens-maus/RaspberryMatic
Seems to be more uptodata and working without any issue.
