### ISSUE TITLE
Error setting up entry ConBee II for deconz

### ISSUE THREAD

**Issue by gvssr** [home-assistant/addons#2316]
### Describe the issue you are experiencing

deCONZ no longer works as of the latest add-on update. Devices can't be controlled either through Phoscon/deCONZ or Home Assistant.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.11.0

### Steps to reproduce the issue

1. Update add-on to 6.11.0
...

### Anything in the Supervisor logs that might be useful for us?

```txt
21-12-20 14:19:14 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 502, message='Invalid response status', url=URL('http://172.30.33.1:8099/websocket')
```

### Additional information

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/deconz/__init__.py", line 37, in async_setup_entry
    if not await gateway.async_setup():
  File "/usr/src/homeassistant/homeassistant/components/deconz/gateway.py", line 171, in async_setup
    self.api = await get_gateway(
  File "/usr/src/homeassistant/homeassistant/components/deconz/gateway.py", line 280, in get_gateway
    await deconz.refresh_state()
  File "/usr/local/lib/python3.9/site-packages/pydeconz/gateway.py", line 121, in refresh_state
    data = await self.request("get", "")
  File "/usr/local/lib/python3.9/site-packages/pydeconz/gateway.py", line 141, in request
    return await self._request(
  File "/usr/local/lib/python3.9/site-packages/pydeconz/gateway.py", line 160, in _request
    raise ResponseError(
pydeconz.errors.ResponseError: Invalid content type: text/html
```

**Comment by frenck** [comment]
The log/stack trace you pasted, is from the Home Assistant deCONZ integration, please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
