### ISSUE TITLE
Check Config with 2022.02.1 fails with No module named 'zha' but real upgrade is fine

### ISSUE THREAD

**Issue by Kisty** [home-assistant/addons#2374]
### Describe the issue you are experiencing

After running Check Configuration addon against 2022.02.1 coming from 2021.12.10, it errors out saying that 'zha' integration cannot be found. Upgrading for real is fine so seems like a bug with the addon.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Check Home Assistant configuration

### What is the version of the add-on?

3.9.0

### Steps to reproduce the issue

1. With core-2021.12.10 installed
2. Have an automation in automation.yaml with domain trigger as `zha` (think this was set up in UI). For example:
```yaml
- id: '1627914350415'
  alias: Tim's lamp button off
  description: ''
  trigger:
  - device_id: <redacted device ID>
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  condition: []
  action:
  - type: turn_off
    device_id: <redacted device ID>
    entity_id: switch.ikea_plug_1
    domain: switch
  mode: single
```
3. Run Check Config addon
...

### Anything in the add-on logs that might be useful for us?

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[04:00:02] INFO: Don't worry, this temporary installation is not overwriting your current one.
[04:00:02] INFO: Installing Home Assistant: stable...
[04:00:02] INFO: Please be patient, this might take a few minutes...
[04:01:05] INFO: Installed Home Assistant 2022.2.1
[04:01:05] INFO: Making a copy of your configuration for checking...
[04:01:06] INFO: Checking your configuration against this version...
[04:04:34] ERROR: The configuration check did not pass!
[04:04:34] ERROR: See the output below for more details.
Testing configuration at /tmp/config
INFO:homeassistant.helpers.storage:Migrating core.device_registry storage from 1.2 to 1.3
INFO:homeassistant.helpers.storage:Migrating core.entity_registry storage from 1.4 to 1.5
INFO:custom_components.unified_remote:Remotes loaded sucessful
ERROR:homeassistant.config:Invalid config for [automation]: Integration 'zha' not found (See /tmp/config/configuration.yaml, line 16). 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/homeassistant/components/device_automation/__init__.py", line 135, in async_get_device_automation_platform
grep: write error: Broken pipe
    integration = await async_get_integration_with_requirements(hass, domain)
  File "/usr/local/lib/python3.9/site-packages/homeassistant/requirements.py", line 75, in async_get_integration_with_requirements
    raise IntegrationNotFound(domain)
homeassistant.loader.IntegrationNotFound: Integration 'zha' not found.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

### Additional information

https://github.com/home-assistant/core/issues/65611

**Comment by Kisty** [comment]
Tried fixing via #2385 but that didn't help. Thought it was related to https://github.com/home-assistant/addons/issues/2373#issuecomment-1043606596 & https://github.com/home-assistant/addons/issues/2377 but don't think it is. 

Have set up my local dev enviornment for addons so will try and fix it.

**Comment by Kisty** [comment]
Closing since this is a core issue https://github.com/home-assistant/core/issues/66904
