### ISSUE TITLE
 Mariadb historian not working after power outage on local server home assistant

### ISSUE THREAD

**Issue by murolenas** [home-assistant/addons#2402]
### Describe the issue you are experiencing

Hi,

This error only occurs when the hassio local server is shut down incorrectly or power cut. 
Shutting down correctly I didn't notice the problem

logs error:
Error during connection setup to mysql://user:password@core-mariadb/homeassistant?charset=utf8mb4: (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to MySQL server on 'core-mariadb' (115)") (Background on this error at: https://sqlalche.me/e/14/e3q8) (retrying in 3 seconds)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 253, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 368, in __init__
    self.__connect()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 611, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2002, "Can't connect to MySQL server on 'core-mariadb' (115)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 720, in _setup_recorder
    self._setup_connection()
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 1023, in _setup_connection
    Base.metadata.create_all(self.engine)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 4740, in create_all
    bind._run_ddl_visitor(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3078, in _run_ddl_visitor
    with self.begin() as conn:
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2994, in begin
    conn = self.connect(close_with_result=close_with_result)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3215, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2069, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 253, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 368, in __init__
    self.__connect()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 611, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to MySQL server on 'core-mariadb' (115)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

MariaDB

### What is the version of the add-on?

2.4.0

### Steps to reproduce the issue

1. Hassio Local Server started normally and historian Maria-DB running ok
2. Power cut on Hassio Local Server.
3. When energy recovered Hassio local server starts normally but historian Maria-DB don't run and show error.
...

### Anything in the add-on logs that might be useful for us?

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:27:48] INFO: Using existing mariadb initial system
[15:27:48] INFO: Starting MariaDB
220309 15:27:49 mysqld_safe Logging to '/data/databases/mariadb.err'.
220309 15:27:49 mysqld_safe Starting mysqld daemon with databases from /data/databases
220309 15:27:49 mysqld_safe Starting mysqld daemon with databases from /data/databases
2022-03-09 15:27:49 0 [Note] /usr/bin/mysqld (mysqld 10.4.19-MariaDB) starting as process 395 ...
2022-03-09 15:27:49 0 [Note] InnoDB: Using Linux native AIO
2022-03-09 15:27:49 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2022-03-09 15:27:49 0 [Note] InnoDB: Uses event mutexes
2022-03-09 15:27:49 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2022-03-09 15:27:49 0 [Note] InnoDB: Number of pools: 1
2022-03-09 15:27:49 0 [Note] InnoDB: Using SSE2 crc32 instructions
2022-03-09 15:27:49 0 [Note] mysqld: O_TMPFILE is not supported on /var/tmp (disabling future attempts)
2022-03-09 15:27:49 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2022-03-09 15:27:49 0 [Note] InnoDB: Completed initialization of buffer pool
2022-03-09 15:27:49 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2022-03-09 15:27:49 0 [ERROR] InnoDB: Missing MLOG_CHECKPOINT at 168437472 between the checkpoint 168437472 and the end 168437248.
2022-03-09 15:27:49 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2022-03-09 15:27:50 0 [Note] InnoDB: Starting shutdown...
2022-03-09 15:27:50 0 [ERROR] Plugin 'InnoDB' init function returned error.
2022-03-09 15:27:50 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2022-03-09 15:27:50 0 [Note] Plugin 'FEEDBACK' is disabled.
2022-03-09 15:27:50 0 [ERROR] Unknown/unsupported storage engine: InnoDB
2022-03-09 15:27:50 0 [ERROR] Aborting
220309 15:27:50 mysqld_safe mysqld from pid file /data/databases/core-mariadb.pid ended
```

**Comment by ADoby** [comment]
I think i have the same problem. I am not sure if it is connected with a power outage or just updating home assistant.
But currently history and some other integrations are broken because of this.

Home Assistant 2022.3.5
OS 7.5
Addon Version: 2.4.0

Error in Home Assistant Log:
```
Error during connection setup: (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to MySQL server on 'core-mariadb' (115)") (Background on this error at: https://sqlalche.me/e/14/e3q8) (retrying in 3 seconds)
```

MariaDB Log:
```[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:55:32] INFO: Using existing mariadb initial system
[15:55:32] INFO: Starting MariaDB
220318 15:55:33 mysqld_safe Logging to '/data/databases/mariadb.err'.
220318 15:55:33 mysqld_safe Starting mysqld daemon with databases from /data/databases
220318 15:55:33 mysqld_safe Starting mysqld daemon with databases from /data/databases
2022-03-18 15:55:33 0 [Note] /usr/bin/mysqld (mysqld 10.4.19-MariaDB) starting as process 395 ...
2022-03-18 15:55:33 0 [Note] InnoDB: Using Linux native AIO
2022-03-18 15:55:33 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2022-03-18 15:55:33 0 [Note] InnoDB: Uses event mutexes
2022-03-18 15:55:33 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2022-03-18 15:55:33 0 [Note] InnoDB: Number of pools: 1
2022-03-18 15:55:33 0 [Note] InnoDB: Using generic crc32 instructions
2022-03-18 15:55:33 0 [Note] mysqld: O_TMPFILE is not supported on /var/tmp (disabling future attempts)
2022-03-18 15:55:33 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2022-03-18 15:55:33 0 [Note] InnoDB: Completed initialization of buffer pool
2022-03-18 15:55:33 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2022-03-18 15:55:33 0 [ERROR] InnoDB: Missing MLOG_CHECKPOINT at 7201216777 between the checkpoint 7201216777 and the end 7201216512.
2022-03-18 15:55:33 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2022-03-18 15:55:34 0 [Note] InnoDB: Starting shutdown...
2022-03-18 15:55:34 0 [ERROR] Plugin 'InnoDB' init function returned error.
2022-03-18 15:55:34 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2022-03-18 15:55:34 0 [Note] Plugin 'FEEDBACK' is disabled.
2022-03-18 15:55:34 0 [ERROR] Unknown/unsupported storage engine: InnoDB
2022-03-18 15:55:34 0 [ERROR] Aborting
220318 15:55:34 mysqld_safe mysqld from pid file /data/databases/core-mariadb.pid ended
```

The same thing happened to me some time ago, and i think i just reinstalled mariaDB addon.
I guess this is the same thing as deleting all the innoDb log files, which means lost data right?

I have not found a user friendly way of fixing this.
