### ISSUE TITLE
Configuration check fails even though no errors are present

### ISSUE THREAD

**Issue by janchlebek** [home-assistant/addons#2446]
### Describe the issue you are experiencing

Checking config while preparing update from 2022.4.5 to 2022.4.6 and then also from 2022.4.7 reported errors. I could not identify anything wrong in my config so decided to proceed after having a proper backup. Update went fine in both cases even though there were errors reported. I believe this is some false positive.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Check Home Assistant configuration

### What is the version of the add-on?

3.10.0

### Steps to reproduce the issue

1. Start Add-On
2. Wait for it to Finish - errors reported
3. Update HA core, no issues. 
...

### Anything in the Supervisor logs that might be useful for us?

```txt
No errors reported
```

### Anything in the add-on logs that might be useful for us?

```txt
[11:10:45] INFO: Installed Home Assistant 2022.4.7
[11:10:45] INFO: Making a copy of your configuration for checking...
[11:10:46] INFO: Checking your configuration against this version...
[11:16:17] ERROR: The configuration check did not pass!
[11:16:17] ERROR: See the output below for more details.
Testing configuration at /tmp/config
ERROR:homeassistant.helpers.check_config:Unexpected error validating config
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/homeassistant/helpers/check_config.py", line 162, in async_check_ha_config_file
    await config_validator.async_validate_config(hass, config)
  File "/usr/local/lib/python3.9/site-packages/homeassistant/components/automation/config.py", line 126, in async_validate_config
    await asyncio.gather(
  File "/usr/local/lib/python3.9/site-packages/homeassistant/components/automation/config.py", line 103, in _try_async_validate_config_item
    config = await async_validate_config_item(hass, config, full_config)
  File "/usr/local/lib/python3.9/site-packages/homeassistant/components/automation/config.py", line 74, in async_validate_config_item
    config[CONF_TRIGGER] = await async_validate_trigger_config(
  File "/usr/local/lib/python3.9/site-packages/homeassistant/helpers/trigger.py", line 52, in async_validate_trigger_config
grep: write error: Broken pipe
    conf = await platform.async_validate_trigger_config(hass, conf)
  File "/usr/local/lib/python3.9/site-packages/homeassistant/components/device_automation/trigger.py", line 59, in async_validate_trigger_config
    return await platform.async_validate_trigger_config(hass, config)
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by janchlebek** [comment]
Eventually I have seen the following at the end of the log (does not seem to always happen):

> ...
>   File "/usr/local/lib/python3.9/site-packages/homeassistant/components/device_automation/trigger.py", line 59, in async_validate_trigger_config
>     return await platform.async_validate_trigger_config(hass, config)
> grep: write error: Broken pipe
> s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] done.
> [s6-finish] waiting for services.
> [s6-finish] sending all processes the TERM signal.
> [s6-finish] sending all processes the KILL signal and exiting.
> ...

**Comment by janchlebek** [comment]
By trial and error I figured out this is caused by a certain automation.
`alias: Laptop by switchj
description: ''
trigger:
  - platform: device
    device_id: 13e4b97a83a1b0230b7554c356291a8e
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: '001'
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene 001
condition: []
action:
  - type: toggle
    device_id: 358d0c00773f62d1d850ac4d8c0340ab
    entity_id: switch.laptop
    domain: switch
mode: single
`
The automation is working just fine, also configuration check via Developer Tools - YAML - Check Configuration is also ok. This must be something in the Add-On
