### ISSUE TITLE
update to version 4.12.1 results in error Not Found ("manifest for homeassistant/armv7-addon-letsencrypt:4.12.1 not found")

### ISSUE THREAD

**Issue by DoerakkerHA** [home-assistant/addons#2450]
### Describe the issue you are experiencing

on update to new version Not Found ("manifest for homeassistant/armv7-addon-letsencrypt:4.12.1 not found: manifest unknown: manifest unknown" update fails

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

Let's Encrypt (4.12.0) (attempt update to 4.12.1)

### Steps to reproduce the issue

1. update notification  for let's encrypt
2. open notification check create backup before installng
3.click install
4.install/update shows popup in vrowser (bottom in screen but flashes before being able to copy
5. retrieving from error log: Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:169
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 07:10:22 (3 occurrences)
Last logged: 07:25:37

[2955063008] Error updating Let's Encrypt: Can't install homeassistant/armv7-addon-letsencrypt:4.12.1: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=4.12.1&fromImage=homeassistant%2Farmv7-addon-letsencrypt&platform=linux%2Farm%2Fv7: Not Found ("manifest for homeassistant/armv7-addon-letsencrypt:4.12.1 not found: manifest unknown: manifest unknown")
[2754100480] Error updating Let's Encrypt: Can't install homeassistant/armv7-addon-letsencrypt:4.12.1: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=4.12.1&fromImage=homeassistant%2Farmv7-addon-letsencrypt&platform=linux%2Farm%2Fv7: Not Found ("manifest for homeassistant/armv7-addon-letsencrypt:4.12.1 not found: manifest unknown: manifest unknown")
[2750460424] Error updating Let's Encrypt: Can't install homeassistant/armv7-addon-letsencrypt:4.12.1: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=4.12.1&fromImage=homeassistant%2Farmv7-addon-letsencrypt&platform=linux%2Farm%2Fv7: Not Found ("manifest for homeassistant/armv7-addon-letsencrypt:4.12.1 not found: manifest unknown: manifest unknown")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 47, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install homeassistant/armv7-addon-letsencrypt:4.12.1: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=4.12.1&fromImage=homeassistant%2Farmv7-addon-letsencrypt&platform=linux%2Farm%2Fv7: Not Found ("manifest for homeassistant/armv7-addon-letsencrypt:4.12.1 not found: manifest unknown: manifest unknown")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 955, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 146, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 387, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Let's Encrypt: Can't install homeassistant/armv7-addon-letsencrypt:4.12.1: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=4.12.1&fromImage=homeassistant%2Farmv7-addon-letsencrypt&platform=linux%2Farm%2Fv7: Not Found ("manifest for homeassistant/armv7-addon-letsencrypt:4.12.1 not found: manifest unknown: manifest unknown")

...

### Anything in the Supervisor logs that might be useful for us?

```txt
[2955063008] Error updating Let's Encrypt: Can't install homeassistant/armv7-addon-letsencrypt:4.12.1: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=4.12.1&fromImage=homeassistant%2Farmv7-addon-letsencrypt&platform=linux%2Farm%2Fv7: Not Found ("manifest for homeassistant/armv7-addon-letsencrypt:4.12.1 not found: manifest unknown: manifest unknown")
[2754100480] Error updating Let's Encrypt: Can't install homeassistant/armv7-addon-letsencrypt:4.12.1: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=4.12.1&fromImage=homeassistant%2Farmv7-addon-letsencrypt&platform=linux%2Farm%2Fv7: Not Found ("manifest for homeassistant/armv7-addon-letsencrypt:4.12.1 not found: manifest unknown: manifest unknown")
[2750460424] Error updating Let's Encrypt: Can't install homeassistant/armv7-addon-letsencrypt:4.12.1: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=4.12.1&fromImage=homeassistant%2Farmv7-addon-letsencrypt&platform=linux%2Farm%2Fv7: Not Found ("manifest for homeassistant/armv7-addon-letsencrypt:4.12.1 not found: manifest unknown: manifest unknown")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 47, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install homeassistant/armv7-addon-letsencrypt:4.12.1: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=4.12.1&fromImage=homeassistant%2Farmv7-addon-letsencrypt&platform=linux%2Farm%2Fv7: Not Found ("manifest for homeassistant/armv7-addon-letsencrypt:4.12.1 not found: manifest unknown: manifest unknown")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 955, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 146, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 387, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Let's Encrypt: Can't install homeassistant/armv7-addon-letsencrypt:4.12.1: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=4.12.1&fromImage=homeassistant%2Farmv7-addon-letsencrypt&platform=linux%2Farm%2Fv7: Not Found ("manifest for homeassistant/armv7-addon-letsencrypt:4.12.1 not found: manifest unknown: manifest unknown")

...
```

### Anything in the add-on logs that might be useful for us?

```txt
no entry
```

**Comment by ludeeus** [comment]
The build failed for that one, 4.12.2 is now published
