### ISSUE TITLE
Unexpected Error during Check Home Assistant configuration

### ISSUE THREAD

**Issue by Micha70** [home-assistant/addons#2533]
### Describe the issue you are experiencing

During runing the Check Home Assistant configuration addon I get an unexpected error in logfile:

[17:11:18] ERROR: The configuration check did not pass!
[17:11:18] ERROR: See the output below for more details.
Testing configuration at /tmp/config
ERROR:homeassistant.helpers.check_config:Unexpected error validating config
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/homeassistant/helpers/check_config.py", line 162, in async_check_ha_config_file

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Check Home Assistant configuration

### What is the version of the add-on?

3.10.2

### Steps to reproduce the issue

1. just starting the addon
2. wait about 5min
3. check log output from addon

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun check-config (no readiness notification)
s6-rc: info: service legacy-services successfully started
[17:04:25] INFO: Don't worry, this temporary installation is not overwriting your current one.
[17:04:25] INFO: Installing Home Assistant: stable...
[17:04:25] INFO: Please be patient, this might take a few minutes...
[17:05:56] INFO: Installed Home Assistant 2022.6.6
[17:05:56] INFO: Making a copy of your configuration for checking...
[17:06:12] INFO: Checking your configuration against this version...
[17:11:18] ERROR: The configuration check did not pass!
[17:11:18] ERROR: See the output below for more details.
Testing configuration at /tmp/config
ERROR:homeassistant.helpers.check_config:Unexpected error validating config
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/homeassistant/helpers/check_config.py", line 162, in async_check_ha_config_file
    await config_validator.async_validate_config(hass, config)
  File "/usr/local/lib/python3.9/site-packages/homeassistant/components/automation/config.py", line 126, in async_validate_config
    await asyncio.gather(
  File "/usr/local/lib/python3.9/site-packages/homeassistant/components/automation/config.py", line 103, in _try_async_validate_config_item
    config = await async_validate_config_item(hass, config, full_config)
  File "/usr/local/lib/python3.9/site-packages/homeassistant/components/automation/config.py", line 74, in async_validate_config_item
    config[CONF_TRIGGER] = await async_validate_trigger_config(
  File "/usr/local/lib/python3.9/site-packages/homeassistant/helpers/trigger.py", line 59, in async_validate_trigger_config
    conf = await platform.async_validate_trigger_config(hass, conf)
  File "/usr/local/lib/python3.9/site-packages/homeassistant/components/device_automation/trigger.py", line 70, in async_validate_trigger_config
    return await platform.async_validate_trigger_config(hass, config)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by Micha70** [comment]
No, I don't use Z-Wave in my setup. Even not a similar automation...

**Comment by frenck** [comment]
The configuration check add-on has been deprecated and is no longer needed.
See: #2544
