### ISSUE TITLE
deCONZ covers broken in HA 2022.8

### ISSUE THREAD

**Issue by mmiller7** [home-assistant/addons#2615]
### Describe the issue you are experiencing

After updating to Home Assistant Core 2022.8 (versions 2022.8.0, 2022.8.3, 2022.8.4 tested) with deCONZ the cover entities are no longer functioning.  Attempting to set the position of a cover (thru automation, developer service-calls, or Lovelace entity cards) results in an error saying it is unavailable.

Rolling back to Core 2022.7.7 restores functionality.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.15.0

### Steps to reproduce the issue

1. Update to HA 2022.8.x
2. Attempt to set the position of a cover entity (via service-call, Lovelace card, or automation)
3. Observe error
...

### Anything in the Supervisor logs that might be useful for us?

```txt
2022-08-08 08:02:08.011 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/deconz/cover.py", line 88, in async_set_cover_position
    await self.gateway.api.lights.covers.set_state(
  File "/usr/local/lib/python3.10/site-packages/pydeconz/interfaces/lights.py", line 71, in set_state
    return await self.gateway.request_with_retry(
  File "/usr/local/lib/python3.10/site-packages/pydeconz/gateway.py", line 142, in request_with_retry
    return await self.request(method, path, json)
  File "/usr/local/lib/python3.10/site-packages/pydeconz/gateway.py", line 167, in request
    response: dict[str, Any] = await self._request(
  File "/usr/local/lib/python3.10/site-packages/pydeconz/gateway.py", line 194, in _request
    _raise_on_error(response)
  File "/usr/local/lib/python3.10/site-packages/pydeconz/gateway.py", line 225, in _raise_on_error
    raise_error(data["error"])
  File "/usr/local/lib/python3.10/site-packages/pydeconz/errors.py", line 73, in raise_error
    raise cls(
pydeconz.errors.RequestError: 6 /lights/8/state parameter, lift, not available
2022-08-08 08:02:26.499 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140415054376688] 6 /lights/4/state parameter, lift, not available
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/deconz/cover.py", line 88, in async_set_cover_position
    await self.gateway.api.lights.covers.set_state(
  File "/usr/local/lib/python3.10/site-packages/pydeconz/interfaces/lights.py", line 71, in set_state
    return await self.gateway.request_with_retry(
  File "/usr/local/lib/python3.10/site-packages/pydeconz/gateway.py", line 142, in request_with_retry
    return await self.request(method, path, json)
  File "/usr/local/lib/python3.10/site-packages/pydeconz/gateway.py", line 167, in request
    response: dict[str, Any] = await self._request(
  File "/usr/local/lib/python3.10/site-packages/pydeconz/gateway.py", line 194, in _request
    _raise_on_error(response)
  File "/usr/local/lib/python3.10/site-packages/pydeconz/gateway.py", line 225, in _raise_on_error
    raise_error(data["error"])
  File "/usr/local/lib/python3.10/site-packages/pydeconz/errors.py", line 73, in raise_error
    raise cls(
pydeconz.errors.RequestError: 6 /lights/4/state parameter, lift, not available
2022-08-08 08:02:32.476 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140415054376688] 6 /lights/4/state parameter, lift, not available
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/deconz/cover.py", line 88, in async_set_cover_position
    await self.gateway.api.lights.covers.set_state(
  File "/usr/local/lib/python3.10/site-packages/pydeconz/interfaces/lights.py", line 71, in set_state
    return await self.gateway.request_with_retry(
  File "/usr/local/lib/python3.10/site-packages/pydeconz/gateway.py", line 142, in request_with_retry
    return await self.request(method, path, json)
  File "/usr/local/lib/python3.10/site-packages/pydeconz/gateway.py", line 167, in request
    response: dict[str, Any] = await self._request(
  File "/usr/local/lib/python3.10/site-packages/pydeconz/gateway.py", line 194, in _request
    _raise_on_error(response)
  File "/usr/local/lib/python3.10/site-packages/pydeconz/gateway.py", line 225, in _raise_on_error
    raise_error(data["error"])
  File "/usr/local/lib/python3.10/site-packages/pydeconz/errors.py", line 73, in raise_error
    raise cls(
pydeconz.errors.RequestError: 6 /lights/4/state parameter, lift, not available
2022-08-08 08:02:58.064 ERROR (MainThread) [frontend.js.latest.202208020] :0:0 ResizeObserver loop completed with undelivered notifications.
```
```


### Anything in the add-on logs that might be useful for us?

_No response_

### Additional information

![image](https://user-images.githubusercontent.com/606945/184454868-767a791e-4f05-48ef-ab7f-f64a1179384f.png)

**Comment by Smanar** [comment]
Hello do you have the model id and the device manufacture name ?

**Comment by mmiller7** [comment]
> Hello do you have the model id and the device manufacture name ?

The cover devices are Keen 4x10 smart vents and my gateway is the Conbee II.

Here's what it shows for the device info in deCONZ:
Light: VendorKeen Home Inc
ModelMulti Sensor
Version 0x00000012

Sensor: Vendor Keen Home Inc
Product Multi Sensor
Versionunknown

And in Home Assistant:
SV01-410-MP-1.0
by Keen Home Inc
Connected via Phoscon-GW

**Comment by Smanar** [comment]
Ok found it https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1478

I think there is an issue because the device is not a covering, so the code reconize it probably as light and don't create state/lift and state/openlike for other covering (and since some version deconz remove state/on and state/bri)

This device don't have the covering cluster, so for me better to don't use state/lift and state/open, like for Profalux covering and manage it like a dimmable bulb.

Wich one type the device have in the device json ? (Visible on phoscon / help / API information / light  / 4)

**Comment by mmiller7** [comment]
> Wich one type the device have in the device json ? (Visible on phoscon / help / API information / light / 4)

I don't know how to figure this out, but if there is a reference I'm happy to post additional information.

Also, when I find that, would I need to collect the information on both the working 2022.7 and broken 2022.8 versions of HA Core?

**Comment by mmiller7** [comment]
> This device don't have the covering cluster, so for me better to don't use state/lift and state/open, like for Profalux covering and manage it like a dimmable bulb.

So does that mean its a regression that would expect to be fixed, or that it should have been under breaking-changes?  In Home Assistant both before and after the 2022.08 update it still shows as a "cover.entitiy_name" not a light.

**Comment by Smanar** [comment]
I think @Kane610 can give use some information here ^^. IDK what happen on lib core.

The device type is "Level controllable output", I know some covering use this type too, but if I m right all work with the "setlevel" cluster, so can set them like classic dimmable bulb, instead of covering.

And IDK why the lib have decided to reconize this device like a covering ?
The JSON is a "light" JSON but perhaps there is a reason at that ?

**Comment by mmiller7** [comment]
Yeah, "set level" isn't an option for "cover" type, and in HA it doesn't show as "light" as a target entity I can pick to send a service call.  I still don't know what happened, but so far in 2022.8.x it appears to be totally unusable.

**Comment by Smanar** [comment]
But this device (on zigbee side) work like a dimmable light, not a covering.
IDK what is the Kane610 opinion, but for me this one can use the "set level" to don't make mistake with real covering that use the covering cluster.
For the target identity it's a good question, the "Level controllable output" is not a light, but I have a (programmable) cable outlet with this type, so nothing to see with your device ....

The change is from deconz, not the plugin. Deconz now stop using state/bri and state/on for full covering device, but your device need them.

**Comment by mmiller7** [comment]
> The change is from deconz, not the plugin.

When you say this, what exactly do you mean?  Are you saying this bug report should be in a different category under home assistant?  If so, what should it be?

**Comment by Smanar** [comment]
Nope, for the moment you are fine.
We are talking about that on deconz dev, give us some time pls.

**Comment by mmiller7** [comment]
Ok, sounds good.  If there's anything else I can try let me know.

**Comment by Smanar** [comment]
I think we have all informations, the problem is more who need to make a corrective ^^. (Not HA, will be deconz devs or deconz plugin dev, or both)

The device don't have covering cluster, so it s not a covering on zigbee side, it's a bulb
But physically the device look more like a covering than a bulb.

All devs haven't same opinion.

**Comment by Kane610** [comment]
I will revert the change in Home Assistant as a proper solution in deconz will take some time. Im gonna try to look at it tonight or tomorrow
