### ISSUE TITLE
File Editor "unknown tag" error for the "!include" values

### ISSUE THREAD

**Issue by KixMan28** [home-assistant/addons#2656]
### Describe the issue you are experiencing

After I installed the latest version (5.4.0) for the File Editor I get "unknown tag" error with the "!include" and the "!secret" values. If I run a Configuration check, it gives no error, so the config files are OK, but the File Editor doesn't recognizes th3 "!include" and "!secret" values.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

File editor

### What is the version of the add-on?

5.4.0

### Steps to reproduce the issue

1. Update File Editor from version 5.3.3 version to 5.4.0
2. Open any configuration file in Home Assistant
3. The first "!xxxx" kind of value is tagged as "unknown"
4. 
...
![2022-09-07 18_52_19-Microsoft Text Input Application](https://user-images.githubusercontent.com/33165356/188935653-276ec243-82dd-44ce-a7b8-f6eca8137a9f.jpg)

### Anything in the Supervisor logs that might be useful for us?

```txt
Nothing
```

### Anything in the add-on logs that might be useful for us?

```txt
Nothing

`
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun configurator (no readiness notification)
s6-rc: info: service legacy-services successfully started
INFO:2022-09-07 18:34:05,464:hass_configurator.configurator:Starting server
INFO:2022-09-07 18:34:05,465:hass_configurator.configurator:Listening on: http://0.0.0.0:8099
INFO:2022-09-07 18:34:19,233:hass_configurator.configurator:172.30.32.2 - "GET / HTTP/1.1" 200 -
INFO:2022-09-07 18:34:19,919:hass_configurator.configurator:172.30.32.2 - "GET /material-icons.fallback.css HTTP/1.1" 200 -
INFO:2022-09-07 18:34:19,934:hass_configurator.configurator:172.30.32.2 - "GET /style.css HTTP/1.1" 200 -
INFO:2022-09-07 18:34:20,048:hass_configurator.configurator:172.30.32.2 - "GET /jquery-3.6.0.min.js HTTP/1.1" 200 -
INFO:2022-09-07 18:34:20,088:hass_configurator.configurator:172.30.32.2 - "GET /materialize.min.js HTTP/1.1" 200 -
INFO:2022-09-07 18:34:20,494:hass_configurator.configurator:172.30.32.2 - "GET /flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2 HTTP/1.1" 200 -
INFO:2022-09-07 18:34:21,328:hass_configurator.configurator:172.30.32.2 - "GET /js-yaml.min.js HTTP/1.1" 200 -
INFO:2022-09-07 18:34:21,535:hass_configurator.configurator:172.30.32.2 - "GET /api/file?filename=/config/sensor.yaml HTTP/1.1" 200 -
INFO:2022-09-07 18:34:21,784:hass_configurator.configurator:172.30.32.2 - "GET /api/listdir?path=. HTTP/1.1" 200 -
INFO:2022-09-07 18:35:19,003:hass_configurator.configurator:172.30.32.2 - "GET /api/file?filename=/config/configuration.yaml HTTP/1.1" 200 -
INFO:2022-09-07 18:35:39,123:hass_configurator.configurator:172.30.32.2 - "GET / HTTP/1.1" 200 -
INFO:2022-09-07 18:35:39,799:hass_configurator.configurator:172.30.32.2 - "GET /material-icons.fallback.css HTTP/1.1" 200 -
INFO:2022-09-07 18:35:39,817:hass_configurator.configurator:172.30.32.2 - "GET /style.css HTTP/1.1" 200 -
INFO:2022-09-07 18:35:39,967:hass_configurator.configurator:172.30.32.2 - "GET /jquery-3.6.0.min.js HTTP/1.1" 200 -
INFO:2022-09-07 18:35:39,998:hass_configurator.configurator:172.30.32.2 - "GET /materialize.min.js HTTP/1.1" 200 -
INFO:2022-09-07 18:35:40,456:hass_configurator.configurator:172.30.32.2 - "GET /flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2 HTTP/1.1" 200 -
INFO:2022-09-07 18:35:41,045:hass_configurator.configurator:172.30.32.2 - "GET /js-yaml.min.js HTTP/1.1" 200 -
INFO:2022-09-07 18:35:41,185:hass_configurator.configurator:172.30.32.2 - "GET /api/file?filename=/config/configuration.yaml HTTP/1.1" 200 -
INFO:2022-09-07 18:35:41,426:hass_configurator.configurator:172.30.32.2 - "GET /api/listdir?path=. HTTP/1.1" 200 -
INFO:2022-09-07 18:35:56,587:hass_configurator.configurator:172.30.32.2 - "GET / HTTP/1.1" 200 -
INFO:2022-09-07 18:35:57,093:hass_configurator.configurator:172.30.32.2 - "GET /material-icons.fallback.css HTTP/1.1" 200 -
INFO:2022-09-07 18:35:57,106:hass_configurator.configurator:172.30.32.2 - "GET /style.css HTTP/1.1" 200 -
INFO:2022-09-07 18:35:57,295:hass_configurator.configurator:172.30.32.2 - "GET /jquery-3.6.0.min.js HTTP/1.1" 200 -
INFO:2022-09-07 18:35:57,310:hass_configurator.configurator:172.30.32.2 - "GET /materialize.min.js HTTP/1.1" 200 -
INFO:2022-09-07 18:35:57,360:hass_configurator.configurator:172.30.32.2 - "GET /flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2 HTTP/1.1" 200 -
INFO:2022-09-07 18:35:58,675:hass_configurator.configurator:172.30.32.2 - "GET /js-yaml.min.js HTTP/1.1" 200 -
INFO:2022-09-07 18:35:58,842:hass_configurator.configurator:172.30.32.2 - "GET /api/file?filename=/config/configuration.yaml HTTP/1.1" 200 -
INFO:2022-09-07 18:35:59,064:hass_configurator.configurator:172.30.32.2 - "GET /api/listdir?path=. HTTP/1.1" 200 -
INFO:2022-09-07 18:38:24,916:hass_configurator.configurator:172.30.32.2 - "GET / HTTP/1.1" 200 -
WARNING:2022-09-07 18:38:32,304:hass_configurator.configurator:Exception getting release
WARNING:2022-09-07 18:38:32,305:hass_configurator.configurator:<urlopen error [Errno -3] Try again>
----------------------------------------
Exception occurred during processing of request from ('172.30.32.2', 37968)
Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.9/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/lib/python3.9/site-packages/hass_configurator/configurator.py", line 878, in do_GET
    self.wfile.write(bytes(html, "utf8"))
  File "/usr/lib/python3.9/socketserver.py", line 826, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
INFO:2022-09-07 18:38:36,550:hass_configurator.configurator:172.30.32.2 - "GET / HTTP/1.1" 200 -
INFO:2022-09-07 18:38:37,661:hass_configurator.configurator:172.30.32.2 - "GET /material-icons.fallback.css HTTP/1.1" 200 -
INFO:2022-09-07 18:38:37,677:hass_configurator.configurator:172.30.32.2 - "GET /style.css HTTP/1.1" 200 -
INFO:2022-09-07 18:38:37,907:hass_configurator.configurator:172.30.32.2 - "GET /jquery-3.6.0.min.js HTTP/1.1" 200 -
INFO:2022-09-07 18:38:37,921:hass_configurator.configurator:172.30.32.2 - "GET /materialize.min.js HTTP/1.1" 200 -
INFO:2022-09-07 18:38:38,209:hass_configurator.configurator:172.30.32.2 - "GET /flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2 HTTP/1.1" 200 -
INFO:2022-09-07 18:38:38,571:hass_configurator.configurator:172.30.32.2 - "GET /js-yaml.min.js HTTP/1.1" 200 -
INFO:2022-09-07 18:38:39,617:hass_configurator.configurator:172.30.32.2 - "GET /api/file?filename=/config/configuration.yaml HTTP/1.1" 200 -
INFO:2022-09-07 18:38:39,845:hass_configurator.configurator:172.30.32.2 - "GET /api/listdir?path=. HTTP/1.1" 200 -
INFO:2022-09-07 18:45:30,651:hass_configurator.configurator:172.30.32.2 - "GET / HTTP/1.1" 200 -
INFO:2022-09-07 18:45:31,395:hass_configurator.configurator:172.30.32.2 - "GET /material-icons.fallback.css HTTP/1.1" 200 -
INFO:2022-09-07 18:45:31,409:hass_configurator.configurator:172.30.32.2 - "GET /style.css HTTP/1.1" 200 -
INFO:2022-09-07 18:45:31,558:hass_configurator.configurator:172.30.32.2 - "GET /jquery-3.6.0.min.js HTTP/1.1" 200 -
INFO:2022-09-07 18:45:31,588:hass_configurator.configurator:172.30.32.2 - "GET /materialize.min.js HTTP/1.1" 200 -
INFO:2022-09-07 18:45:31,924:hass_configurator.configurator:172.30.32.2 - "GET /flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2 HTTP/1.1" 200 -
INFO:2022-09-07 18:45:32,682:hass_configurator.configurator:172.30.32.2 - "GET /js-yaml.min.js HTTP/1.1" 200 -
INFO:2022-09-07 18:45:32,841:hass_configurator.configurator:172.30.32.2 - "GET /api/file?filename=/config/configuration.yaml HTTP/1.1" 200 -
INFO:2022-09-07 18:45:33,067:hass_configurator.configurator:172.30.32.2 - "GET /api/listdir?path=. HTTP/1.1" 200 -
INFO:2022-09-07 18:51:49,144:hass_configurator.configurator:172.30.32.2 - "GET / HTTP/1.1" 200 -
INFO:2022-09-07 18:51:49,858:hass_configurator.configurator:172.30.32.2 - "GET /material-icons.fallback.css HTTP/1.1" 200 -
INFO:2022-09-07 18:51:49,882:hass_configurator.configurator:172.30.32.2 - "GET /style.css HTTP/1.1" 200 -
INFO:2022-09-07 18:51:50,014:hass_configurator.configurator:172.30.32.2 - "GET /jquery-3.6.0.min.js HTTP/1.1" 200 -
INFO:2022-09-07 18:51:50,050:hass_configurator.configurator:172.30.32.2 - "GET /materialize.min.js HTTP/1.1" 200 -
INFO:2022-09-07 18:51:50,506:hass_configurator.configurator:172.30.32.2 - "GET /flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2 HTTP/1.1" 200 -
INFO:2022-09-07 18:51:51,124:hass_configurator.configurator:172.30.32.2 - "GET /js-yaml.min.js HTTP/1.1" 200 -
INFO:2022-09-07 18:51:51,285:hass_configurator.configurator:172.30.32.2 - "GET /api/file?filename=/config/configuration.yaml HTTP/1.1" 200 -
INFO:2022-09-07 18:51:51,505:hass_configurator.configurator:172.30.32.2 - "GET /api/listdir?path=. HTTP/1.1" 200 -
INFO:2022-09-07 18:54:32,499:hass_configurator.configurator:172.30.32.2 - "GET / HTTP/1.1" 200 -
INFO:2022-09-07 18:54:33,239:hass_configurator.configurator:172.30.32.2 - "GET /material-icons.fallback.css HTTP/1.1" 200 -
INFO:2022-09-07 18:54:33,263:hass_configurator.configurator:172.30.32.2 - "GET /style.css HTTP/1.1" 200 -
INFO:2022-09-07 18:54:33,375:hass_configurator.configurator:172.30.32.2 - "GET /jquery-3.6.0.min.js HTTP/1.1" 200 -
INFO:2022-09-07 18:54:33,427:hass_configurator.configurator:172.30.32.2 - "GET /materialize.min.js HTTP/1.1" 200 -
INFO:2022-09-07 18:54:33,850:hass_configurator.configurator:172.30.32.2 - "GET /flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2 HTTP/1.1" 200 -
````
```


### Additional information

_No response_

**Comment by marcelhoogantink** [comment]
Same here after update to 5.4.0

**Comment by 0n3-70uch** [comment]
+1 same here

**Comment by A-Boers** [comment]
I have the same problem here to.
Running HA version 2022.9.0

![File editor](https://user-images.githubusercontent.com/75908738/188978423-6f2d62b5-850c-42b5-8d71-94e48701aa25.jpeg)

**Comment by sd5932** [comment]
Same here I was going crazy.

**Comment by rktr2009** [comment]
Same here after update to 5.4.0

**Comment by eabode** [comment]
Ditto. It protests on any !xxxxxx tag. I have commented for now until fixed.

**Comment by loganmarchione** [comment]
Same here after update to 5.4.0.

However, the [changes made to the Home Assistant add-on](https://github.com/home-assistant/addons/pull/2646) were actually to just update the configurator, which is [owned/maintaned by another person](https://github.com/danielperna84/hass-configurator/releases/tag/0.5.0). I'm not sure if we need an issue opened here, or there...

**Comment by ludeeus** [comment]
The hass-configurator repository is the correct place for it.

**Comment by frenck** [comment]
## 🤚 I have the same issue! 👇 Read below

Hi there! Sorry to read you are experiencing the same issue as more people here. Nobody likes having issues 😞

Finding an issue on a GitHub issue tracker that matches your problem is kinda nice: At least you know you are not alone. So, let's leave a commit with: "Yeah, I have the same issue", or "+1!!!". 🚫 **No!**

### Please do not create "I have the same issue" comments!

Not just this issue or this project, but anywhere on GitHub or any issue tracker on the internet even. It doesn't add to triaging the issue. It only generates noise when reading / triaging the case. 

### What to do instead?

Instead, go to the top of the issue, and add a 👍 emoji reaction. That way, we can still see that you (and how many others) experience this issue while keeping the issue threads nice and clean.

Thanks! ❤️

../Frenck
