### ISSUE TITLE
Hassos LetsEncrypt configuration not exposed

### ISSUE THREAD

**Issue by RonaldPhilipsen** [home-assistant/addons#2682]
### Describe the issue you are experiencing

I'm currently unable to setup Lets' encrypt on my fresh HassOs installation. the configuration does not seem to expose any configuration options for me to mess with.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

4.12.7

### Steps to reproduce the issue

1. go to add-on store
2. install Let's encrypt addon
3. Go to Configuration tab
4. See "This add-on does not expose configuration for you to mess with…"
5. Attempt to start addon
6. get popup "Missing required option 'domains' in Let's Encrypt (core_letsencrypt). "

### Anything in the Supervisor logs that might be useful for us?

```txt
2-09-25 17:11:10 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/core_letsencrypt
22-09-25 17:11:10 INFO (SyncWorker_6) [supervisor.docker.interface] Downloading docker image homeassistant/aarch64-addon-letsencrypt with tag 4.12.7.
22-09-25 17:11:58 INFO (SyncWorker_1) [supervisor.docker.interface] Downloading docker image homeassistant/aarch64-addon-letsencrypt with tag 4.12.7.
22-09-25 17:12:29 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Node-RED is failed, restarting...
22-09-25 17:12:29 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_a0d7b954_nodered application
22-09-25 17:14:15 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/node-red/aarch64 with version 13.4.0
22-09-25 17:14:58 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-132076' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:964> exception=AddonsJobError('Rate limit exceeded, more then 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 978, in watchdog_container
    await self._restart_after_problem(self, event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 144, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more then 10 calls in 0:30:00
22-09-25 17:17:58 INFO (MainThread) [supervisor.addons] Add-on 'core_letsencrypt' successfully installed
22-09-25 17:17:58 INFO (MainThread) [supervisor.addons] Add-on 'core_letsencrypt' successfully installed
```

### Anything in the add-on logs that might be useful for us?

```txt
No errors have been reported
```

**Comment by RonaldPhilipsen** [comment]
Hmm, seems like the first reboot didn´t do the trick, after a second reboot the option appears
