### ISSUE TITLE
Netatmo integration stop working since 2022.10 for NLPO 

### ISSUE THREAD

**Issue by AceEye03** [home-assistant/addons#2735]
Hi,

I already opened an issue for an error of initializing Netatmo integration since 2022.10 an after the multiple updates, I have the same problem.

Logger: homeassistant.config_entries
Source: components/netatmo/data_handler.py:199
First occurred: 27 octobre 2022 à 21:53:04 (1 occurrences)
Last logged: 27 octobre 2022 à 21:53:04

Error setting up entry Home Assistant Cloud for netatmo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/netatmo/__init__.py", line 164, in async_setup_entry
    await data_handler.async_setup()
  File "/usr/src/homeassistant/homeassistant/components/netatmo/data_handler.py", line 151, in async_setup
    await self.subscribe(ACCOUNT, ACCOUNT, None)
  File "/usr/src/homeassistant/homeassistant/components/netatmo/data_handler.py", line 243, in subscribe
    await self.async_fetch_data(signal_name)
  File "/usr/src/homeassistant/homeassistant/components/netatmo/data_handler.py", line 199, in async_fetch_data
    await getattr(self.account, self.publisher[signal_name].method)(
  File "/usr/local/lib/python3.10/site-packages/pyatmo/account.py", line 69, in async_update_topology
    self.process_topology()
  File "/usr/local/lib/python3.10/site-packages/pyatmo/account.py", line 58, in process_topology
    self.homes[home_id] = Home(self.auth, raw_data=home)
  File "/usr/local/lib/python3.10/site-packages/pyatmo/home.py", line 48, in __init__
    self.modules = {
  File "/usr/local/lib/python3.10/site-packages/pyatmo/home.py", line 49, in <dictcomp>
    module["id"]: getattr(modules, module["type"])(
AttributeError: module 'pyatmo.modules' has no attribute 'NLPO'

I hope that it's possible to fix that issue because a lot of automation works withs Netatmo (for the heating)...

Thank you so much for your job!

**Comment by kingpainter** [comment]
Me 2

**Comment by AceEye03** [comment]
Hi,

Someone can help me ?

Thanks
