### ISSUE TITLE
Error updating `Silicon Labs Multiprotocol` add-on.

### ISSUE THREAD

**Issue by jbouwh** [home-assistant/addons#2832]
### Describe the issue you are experiencing

An error comes up when trying to update the `Silicon Labs Multiprotocol Update` add-on.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Silicon Labs Multiprotocol

### What is the version of the add-on?

0.11.1 -> 0.11.2

### Steps to reproduce the issue

1. The update for version 0.11.2 from 0.11.1 appears
2. Click install
3. An error is logged, the update is not installed.
...

## System Information

version | core-2023.1.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.76-v8
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4939
Installed Version | 1.29.0
Stage | running
Available Repositories | 1257
Downloaded Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.4
-- | --
update_channel | beta
supervisor_version | supervisor-2022.12.1
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 57.6 GB
disk_used | 27.0 GB
healthy | true
supported | failed to load: Unsupported
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.6.1), AppDaemon (0.11.0), File editor (5.4.2), Mosquitto broker (6.1.3), Grafana (8.1.0), InfluxDB (4.5.0), Studio Code Server (5.5.1), Portainer (2.16.2), MariaDB (2.5.1), Silicon Labs Multiprotocol (0.11.1), Matter Server (2.0.0), ESPHome (2022.12.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 12 december 2022 om 08:28
-- | --
current_recorder_run | 11 januari 2023 om 13:08
estimated_db_size | 4942.36 MiB
database_engine | mysql
database_version | 10.6.5

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
23-01-12 09:31:04 ERROR (SyncWorker_3) [supervisor.docker.interface] Can't install homeassistant/aarch64-addon-silabs-multiprotocol:0.11.2: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.11.2&fromImage=homeassistant%2Faarch64-addon-silabs-multiprotocol&platform=linux%2Farm64: Not Found ("manifest for homeassistant/aarch64-addon-silabs-multiprotocol:0.11.2 not found: manifest unknown: manifest unknown")
```

### Additional information

Core logs:
```log
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:169
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 09:31:04 (2 occurrences)
Last logged: 09:31:19

[546848110768] Error updating Silicon Labs Multiprotocol: Can't install homeassistant/aarch64-addon-silabs-multiprotocol:0.11.2: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.11.2&fromImage=homeassistant%2Faarch64-addon-silabs-multiprotocol&platform=linux%2Farm64: Not Found ("manifest for homeassistant/aarch64-addon-silabs-multiprotocol:0.11.2 not found: manifest unknown: manifest unknown")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 51, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install homeassistant/aarch64-addon-silabs-multiprotocol:0.11.2: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.11.2&fromImage=homeassistant%2Faarch64-addon-silabs-multiprotocol&platform=linux%2Farm64: Not Found ("manifest for homeassistant/aarch64-addon-silabs-multiprotocol:0.11.2 not found: manifest unknown: manifest unknown")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 154, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 413, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Silicon Labs Multiprotocol: Can't install homeassistant/aarch64-addon-silabs-multiprotocol:0.11.2: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.11.2&fromImage=homeassistant%2Faarch64-addon-silabs-multiprotocol&platform=linux%2Farm64: Not Found ("manifest for homeassistant/aarch64-addon-silabs-multiprotocol:0.11.2 not found: manifest unknown: manifest unknown")
```

**Comment by jbouwh** [comment]
It seems the image was not ready, in the mean time this was solved and the update installed.
