### ISSUE TITLE
 Cannot start Z- wave JS Add On with z.way ZMEEUZB Stick

### ISSUE THREAD

**Issue by soesas** [home-assistant/addons#2836]
### Describe the issue you are experiencing

I have tried to start Z-Wave integration with the Z-wave JS addOn. The AddOn seems ta be the problem because it will not start properly.
It did work perfectly before but then it suddenly stopped working for no apparent reason. Even trying an alternative  ZMEEUZBstick did not help. The right port is selected. This is the log that causes the problem and it eventually stops both the add on and z-wave itself making my iategration and numerous devices unusable.
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/config.sh
[22:59:52] INFO: Both 'network_key' and 's0_legacy_key' are set and match. All ok.
[22:59:55] INFO: Virtual Machine not detected, enabling soft-reset
cont-init: info: /etc/cont-init.d/config.sh exited 0
cont-init: info: running /etc/cont-init.d/structure.sh
cont-init: info: /etc/cont-init.d/structure.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun zwave_js (no readiness notification)
s6-rc: info: service legacy-services successfully started
[22:59:56] INFO: Successfully send discovery information to Home Assistant.
2023-01-14T21:59:59.654Z DRIVER   ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
                                  ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
                                    ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
                                   ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
                                  ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
                                  ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝
2023-01-14T21:59:59.662Z DRIVER   version 10.3.0
2023-01-14T21:59:59.663Z DRIVER   
2023-01-14T21:59:59.848Z CONFIG   version 10.3.0
2023-01-14T22:00:01.403Z CNTRLR   querying controller IDs...
2023-01-14T22:00:02.806Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2023-01-14T22:00:03.918Z CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                                  n 1100 ms.
2023-01-14T22:00:06.058Z DRIVER   Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK 
                                  from the controller (ZW0200)
                                      at Driver.sendMessage (/usr/src/node_modules/zwave-js/src/lib/driver/Drive
                                  r.ts:3990:23)
                                      at ZWaveController.identify (/usr/src/node_modules/zwave-js/src/lib/contro
                                  ller/Controller.ts:713:33)
                                      at Driver.initializeControllerAndNodes (/usr/src/node_modules/zwave-js/src
                                  /lib/driver/Driver.ts:1208:26)
                                      at Immediate.<anonymous> (/usr/src/node_modules/zwave-js/src/lib/driver/Dr
                                  iver.ts:1015:16)
Error in driver ZWaveError: Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK from the controller (ZW0200)
    at Driver.sendMessage (/usr/src/node_modules/zwave-js/src/lib/driver/Driver.ts:3990:23)
    at ZWaveController.identify (/usr/src/node_modules/zwave-js/src/lib/controller/Controller.ts:713:33)
    at Driver.initializeControllerAndNodes (/usr/src/node_modules/zwave-js/src/lib/driver/Driver.ts:1208:26)
    at Immediate.<anonymous> (/usr/src/node_modules/zwave-js/src/lib/driver/Driver.ts:1015:16) (ZW0100)
    at Immediate.<anonymous> (/usr/src/node_modules/zwave-js/src/lib/driver/Driver.ts:1032:6)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 100,
  context: undefined,
  transactionSource: undefined
}
Shutting down
[22:00:06] WARNING: Halt add-on
s6-rc: info: service legacy-services: stopping
[22:00:06] INFO: Service restart after closing
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```
All the settings in configuration i left untouched and it did work before - I am out of ideas on what to do.
Thankf for yuor help.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of the add-on?

10.3.0

### Steps to reproduce the issue

1. Start the add On
2. Fault in  Driver

```
2023-01-14T22:00:02.806Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2023-01-14T22:00:03.918Z CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                                  n 1100 ms.
2023-01-14T22:00:06.058Z DRIVER   Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK 
                                  from the controller (ZW0200)
                                      at Driver.sendMessage (/usr/src/node_modules/zwave-js/src/lib/driver/Drive
                                  r.ts:3990:23)
                                      at ZWaveController.identify (/usr/src/node_modules/zwave-js/src/lib/contro
                                  ller/Controller.ts:713:33)
                                      at Driver.initializeControllerAndNodes (/usr/src/node_modules/zwave-js/src
                                  /lib/driver/Driver.ts:1208:26)
                                      at Immediate.<anonymous> (/usr/src/node_modules/zwave-js/src/lib/driver/Dr
                                  iver.ts:1015:16)
Error in driver ZWaveError: Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK from the controller (ZW0200)
    at Driver.sendMessage (/usr/src/node_modules/zwave-js/src/lib/driver/Driver.ts:3990:23)
    at ZWaveController.identify (/usr/src/node_modules/zwave-js/src/lib/controller/Controller.ts:713:33)
    at Driver.initializeControllerAndNodes (/usr/src/node_modules/zwave-js/src/lib/driver/Driver.ts:1208:26)
    at Immediate.<anonymous> (/usr/src/node_modules/zwave-js/src/lib/driver/Driver.ts:1015:16) (ZW0100)
    at Immediate.<anonymous> (/usr/src/node_modules/zwave-js/src/lib/driver/Driver.ts:1032:6)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 100,
  context: undefined,
  transactionSource: undefined
}
```

4. Add on stops

## System Information

version | core-2023.1.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.76-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.29.1
Stage | running
Available Repositories | 1265
Downloaded Repositories | 23

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | November 7, 2023 at 01:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-west-2-3.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.12.1
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 57.8 GB
disk_used | 20.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.5.1), File editor (5.4.2), Samba share (10.0.0), Mosquitto broker (6.1.3), deCONZ (6.17.1), ESPHome (2022.12.3), SSH & Web Terminal (13.0.0), Duck DNS (1.15.0), Z-Wave JS UI (1.4.2), Z-Wave JS (0.1.74)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 10
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 5, 2023 at 02:22
-- | --
current_recorder_run | January 14, 2023 at 15:12
estimated_db_size | 461.34 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:843
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 20:30:04 (1 occurrences)
Last logged: 20:30:04

Could not fetch stats for core_zwave_js: Container addon_core_zwave_js is not running
```

### Anything in the add-on logs that might be useful for us?

```txt
Logger: homeassistant.components.zwave_js.config_flow
Source: components/zwave_js/config_flow.py:225
Integration: Z-Wave (documentation, issues)
First occurred: 22:48:31 (1 occurrences)
Last logged: 22:48:31

Failed to start Z-Wave JS add-on: timeout
```

### Additional information

Thank you for your help. Itis probablyy not a bug but faulty user.

**Comment by MartinHjelmare** [comment]
I see in the system health information that you have both the Z-Wave JS UI and the Z-Wave JS add-on installed. Are both running at the same time? If so, that could be the cause of the problems.

**Comment by soesas** [comment]
No unfortunately that's not the case I just tested with only the z-wave stick and only the Zigbee stick.
It's the same result in the logs so no difference there

**Comment by MartinHjelmare** [comment]
What do you mean with "only the z-wave stick and only the Zigbee stick"? I'm talking about the Z-Wave JS UI add-on and the Z-Wave JS add-on which are both for Z-Wave. Only one of those add-ons can run at any one time.

**Comment by soesas** [comment]
Hello again 
I am not completely sure why my but one of the z wave switches seem to have caused the problem. that switch is usually used for Christmas lights. As soon as I  unplugged it  z-wave JS started working properly again. I do not know the true cause of this and I am so happy that is finally working again so thank you anyways for the tips and help even though it was a very beginner kind of question to ask.
