### ISSUE TITLE
Updates for matter server released to stable channel, require beta release

### ISSUE THREAD

**Issue by briped** [home-assistant/addons#2855]
### Describe the issue you are experiencing

Updates for matter server released to stable channel, require beta release.

Would it be possible to stop items that require beta versions, to stable channel?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

3.0.1

### Steps to reproduce the issue

1. Have latest stable version of Home Assistent installed:
- Home Assistant 2023.1.7
- Supervisor 2023.01.1
- Operating Ssystem 9.4
- Frontend 20230110.0 - latest.

2. See notification about update 3.0.2 to Matter Server add-on.
3. Attempt to install Matter Server add-on 3.0.2.
4. Be thwarted by the fact that the Matter Server add-on requires Home Assistant version 2023.2.0b0
5. Scratch head and wonder over why add-ons released to stable channel, require beta release.

### System Health information

There are currently no repairs available

### Anything in the Supervisor logs that might be useful for us?

```txt
File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 413, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Matter Server: Add-on core_matter_server not supported on this system, requires Home Assistant version 2023.2.0b0 or greater
```

### Anything in the add-on logs that might be useful for us?

```txt
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:169
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 17:26:37 (3 occurrences)
Last logged: 17:37:46

[139836342724704] Error updating Matter Server: Add-on core_matter_server not supported on this system, requires Home Assistant version 2023.2.0b0 or greater
[139836807329440] Error updating Matter Server: Add-on core_matter_server not supported on this system, requires Home Assistant version 2023.2.0b0 or greater
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 51, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Add-on core_matter_server not supported on this system, requires Home Assistant version 2023.2.0b0 or greater

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 154, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 413, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Matter Server: Add-on core_matter_server not supported on this system, requires Home Assistant version 2023.2.0b0 or greater
```

**Comment by frenck** [comment]
> Updates for matter server released to stable channel, require beta release.

That is correct at this point. The Matter integration itself is also in beta stage.

> Would it be possible to stop items that require beta versions, to stable channel?

That is currently not possible. Home Assistant doesn't have the constructs needed for supporting that at this point. We are looking into making such things possible for an add-on, but currently, that is not the functionality of Home Assistant.

../Frenck
