### ISSUE TITLE
Skyconnect Problem with Silicon Labs Multiprotocol

### ISSUE THREAD

**Issue by ALutz273** [home-assistant/addons#2869]
### Describe the issue you are experiencing

I got my Skyconnect adapter today and wanted to set it up. 
Unfortunately there are problems with the Multiprtocol support. 

Silicon Labs Multiprotocol 0.12.0

```

s6-rc: info: service mdns: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service mdns successfully started
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/check-cpcd-shm.sh
[17:22:38] INFO: Starting mDNS Responder...
Default: mDNSResponder (Engineering Build) (Jan 23 2023 22:46:33) starting
Default: mDNS_AddDNSServer: Lock not held! mDNS_busy (0) mDNS_reentrancy (0)
cont-init: info: /etc/cont-init.d/check-cpcd-shm.sh exited 0
cont-init: info: running /etc/cont-init.d/config.sh
[17:22:38] INFO: Generating cpcd configuration.
cont-init: info: /etc/cont-init.d/config.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service banner: starting
-----------------------------------------------------------
 Add-on: Silicon Labs Multiprotocol
 Zigbee and OpenThread multiprotocol add-on
-----------------------------------------------------------
 Add-on version: 0.12.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (amd64 / qemux86-64)
 Home Assistant Core: 2023.2.0b9
 Home Assistant Supervisor: 2023.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service universal-silabs-flasher: starting
[17:22:39] INFO: Checking /dev/ttyUSB0 identifying SkyConnect v1.0 from Nabu Casa
[17:22:39] INFO: Starting universal-silabs-flasher with /dev/ttyUSB0 (baudrate 115200)
2023-02-01 17:22:39 core-silabs-multiprotocol universal_silabs_flasher.flash[219] INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version=<AwesomeVersion SemVer '4.1.4'>, ezsp_version=None, fw_type=<FirmwareImageType.RCP_UART_802154: 'rcp-uart-802154'>)
2023-02-01 17:22:39 core-silabs-multiprotocol universal_silabs_flasher.flasher[219] INFO Probing ApplicationType.GECKO_BOOTLOADER
2023-02-01 17:22:41 core-silabs-multiprotocol universal_silabs_flasher.flasher[219] INFO Probing ApplicationType.CPC
2023-02-01 17:22:45 core-silabs-multiprotocol universal_silabs_flasher.flasher[219] INFO Probing ApplicationType.EZSP
Error: Failed to probe running application type
2023-02-01 17:22:50 core-silabs-multiprotocol concurrent.futures[219] ERROR exception calling callback for <Future at 0x7f9e2fb1e9d0 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.9/asyncio/futures.py", line 398, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 791, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
s6-rc: warning: unable to start service universal-silabs-flasher: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
s6-rc: info: service mdns: stopping
s6-rc: info: service banner: stopping
Default: mDNSResponder (Engineering Build) (Jan 23 2023 22:46:33) stopping
s6-rc: info: service banner successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
[17:22:50] INFO: mDNS ended with exit code 4 (signal 0)...
s6-rc: info: service mdns successfully stopped



```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Silicon Labs Multiprotocol

### What is the version of the add-on?

Silicon Labs Multiprotocol

### Steps to reproduce the issue

1. Flash via laptop to the System -> firmware from https://github.com/NabuCasa/silabs-firmware/blob/main/EmberZNetAndOpenThreadRCP/beta/NabuCasa_SkyConnect_EZSP_OpenThread_RCP_v4.1.3.0_ncp-uart-hw_230400.gbl
2. Plugin in the System (VM) 
3. System -> Hardware->  Home Assistant SkyConnect -> start configuration
 

### System Health information

Derzeit sind keine Reparaturen verfügbar

Currently no repairs are available

**Comment by regevbr** [comment]
Same issue - Just installed 2023.2.0, upgrades the firmware of my skyconnect from the hardware configuration page a,d then started the addon and it keeps restating. Here is my logs:

```
s6-rc: info: service mdns: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service mdns successfully started
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/check-cpcd-shm.sh
[23:54:36] INFO: Starting mDNS Responder...
Default: mDNSResponder (Engineering Build) (Jan 23 2023 22:49:33) starting
Default: mDNS_AddDNSServer: Lock not held! mDNS_busy (0) mDNS_reentrancy (0)
cont-init: info: /etc/cont-init.d/check-cpcd-shm.sh exited 0
cont-init: info: running /etc/cont-init.d/config.sh
[23:54:38] INFO: Generating cpcd configuration.
cont-init: info: /etc/cont-init.d/config.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service banner: starting
-----------------------------------------------------------
 Add-on: Silicon Labs Multiprotocol
 Zigbee and OpenThread multiprotocol add-on
-----------------------------------------------------------
 Add-on version: 0.12.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.2.0
 Home Assistant Supervisor: 2023.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service universal-silabs-flasher: starting
[23:54:41] INFO: Checking /dev/ttyUSB1 identifying SkyConnect v1.0 from Nabu Casa
[23:54:41] INFO: Starting universal-silabs-flasher with /dev/ttyUSB1 (baudrate 115200)
2023-02-01 23:54:43 core-silabs-multiprotocol universal_silabs_flasher.flash[219] INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version=<AwesomeVersion SemVer '4.1.4'>, ezsp_version=None, fw_type=<FirmwareImageType.RCP_UART_802154: 'rcp-uart-802154'>)
2023-02-01 23:54:43 core-silabs-multiprotocol universal_silabs_flasher.flasher[219] INFO Probing ApplicationType.GECKO_BOOTLOADER
2023-02-01 23:54:45 core-silabs-multiprotocol universal_silabs_flasher.flasher[219] INFO Probing ApplicationType.CPC
2023-02-01 23:54:49 core-silabs-multiprotocol universal_silabs_flasher.flasher[219] INFO Probing ApplicationType.EZSP
Error: Failed to probe running application type
2023-02-01 23:54:55 core-silabs-multiprotocol concurrent.futures[219] ERROR exception calling callback for <Future at 0x7fb7ae59a0 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.9/asyncio/futures.py", line 398, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 791, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
s6-rc: warning: unable to start service universal-silabs-flasher: command exited 1
```

**Comment by skgsergio** [comment]
Context: https://github.com/NabuCasa/silabs-firmware/issues/9

This is happening because the SkyConnect has firmware configured for a baudrate of `230400` and the addon is trying to flash the device connecting at a baudrate of `115200`:

```
[17:22:39] INFO: Starting universal-silabs-flasher with /dev/ttyUSB0 (baudrate 115200)
```

I don't own a SkyConnect but I'm guessing that either the addon flashed a `230400` baudrate firmware in the past or users having issues flashed a `230400` baudrate firmware manually. By the git history, I guess it was the later.

For @regevbr just flash manually the SkyConnect again like this:

```sh
universal-silabs-flasher --device /dev/ttyUSB1 --baudrate 230400 flash --firmware NabuCasa_SkyConnect_RCP_v4.1.4_rcp-uart-hw-802154_115200.gbl
```

You can grab the firmware file from here: https://github.com/home-assistant/addons/tree/master/silabs-multiprotocol/rootfs/root

**Comment by regevbr** [comment]
Thanks

For me restarting my pi and then the addon one more time fixed it

**Comment by Moqume** [comment]
I've fount it to be the `Automatically flash firmware` option. If it is enabled, I get the same error:

```
s6-rc: info: service mdns: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service mdns successfully started
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/check-cpcd-shm.sh
[21:18:01] INFO: Starting mDNS Responder...
Default: mDNSResponder (Engineering Build) (Jan 23 2023 22:46:33) starting
Default: mDNS_AddDNSServer: Lock not held! mDNS_busy (0) mDNS_reentrancy (0)
cont-init: info: /etc/cont-init.d/check-cpcd-shm.sh exited 0
cont-init: info: running /etc/cont-init.d/config.sh
[21:18:03] INFO: Generating cpcd configuration.
cont-init: info: /etc/cont-init.d/config.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service banner: starting
-----------------------------------------------------------
 Add-on: Silicon Labs Multiprotocol
 Zigbee and OpenThread multiprotocol add-on
-----------------------------------------------------------
 Add-on version: 0.12.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.2.1
 Home Assistant Supervisor: 2023.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service universal-silabs-flasher: starting
[21:18:05] INFO: Checking /dev/ttyUSB0 identifying SkyConnect v1.0 from Nabu Casa
[21:18:05] INFO: Starting universal-silabs-flasher with /dev/ttyUSB0 (baudrate 230400)
2023-02-04 21:18:07 core-silabs-multiprotocol universal_silabs_flasher.flash[217] INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version=<AwesomeVersion SemVer '4.1.4'>, ezsp_version=None, fw_type=<FirmwareImageType.RCP_UART_802154: 'rcp-uart-802154'>)
2023-02-04 21:18:07 core-silabs-multiprotocol universal_silabs_flasher.flasher[217] INFO Probing ApplicationType.GECKO_BOOTLOADER
2023-02-04 21:18:09 core-silabs-multiprotocol universal_silabs_flasher.flasher[217] INFO Probing ApplicationType.CPC
2023-02-04 21:18:13 core-silabs-multiprotocol universal_silabs_flasher.flasher[217] INFO Probing ApplicationType.EZSP
Error: Failed to probe running application type
2023-02-04 21:18:18 core-silabs-multiprotocol concurrent.futures[217] ERROR exception calling callback for <Future at 0x7fd7ab246910 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.9/asyncio/futures.py", line 398, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 791, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
s6-rc: warning: unable to start service universal-silabs-flasher: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
s6-rc: info: service mdns: stopping
s6-rc: info: service banner: stopping
Default: mDNSResponder (Engineering Build) (Jan 23 2023 22:46:33) stopping
s6-rc: info: service banner successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
[21:18:19] INFO: mDNS ended with exit code 4 (signal 0)...
s6-rc: info: service mdns successfully stopped
```
When it is disabled, it starts, except it loops with `Failed to connect to Secondary...` filling up the log:

```
s6-rc: info: service banner successfully started
s6-rc: info: service universal-silabs-flasher: starting
[21:24:58] INFO: Flashing firmware is disabled
s6-rc: info: service universal-silabs-flasher successfully started
s6-rc: info: service cpcd: starting
[21:24:58] INFO: Starting cpcd...
[21:24:58:910] Info : [CPCd v4.1.4.0] [Library API v2] [RCP Protocol v2]
[21:24:58:910] Info : Git commit: 5df3ef9fb8891987b623b623694ec4c435ea5644 / branch: 
[21:24:58:910] Info : Sources hash: 2606b603ff85938a832e691804f2d1fcf86745370d236a1a9c47f03bdf95898e
[21:24:58:910] Info : Reading cli arguments
[21:24:58:910] Info : /usr/local/bin/cpcd 
[21:24:58:929] Info : Reading configuration
[21:24:58:929] Info : file_path = /usr/local/etc/cpcd.conf
[21:24:58:929] Info : instance_name = cpcd_0
[21:24:58:929] Info : socket_folder = /dev/shm
[21:24:58:929] Info : operation_mode = MODE_NORMAL
[21:24:58:929] Info : use_encryption = false
[21:24:58:929] Info : binding_key_file = /etc/binding-key.key
[21:24:58:929] Info : binding_method = 
[21:24:58:929] Info : stdout_tracing = false
[21:24:58:929] Info : file_tracing = false
[21:24:58:929] Info : lttng_tracing = false
[21:24:58:929] Info : enable_frame_trace = false
[21:24:58:929] Info : traces_folder = /dev/shm/cpcd-traces
[21:24:58:929] Info : bus = UART
[21:24:58:929] Info : uart_baudrate = 230400
[21:24:58:929] Info : uart_hardflow = true
[21:24:58:929] Info : uart_file = /dev/ttyUSB0
[21:24:58:929] Info : spi_file = /dev/spidev0.0
[21:24:58:929] Info : spi_bitrate = 1000000
[21:24:58:929] Info : spi_mode = SPI_MODE_0
[21:24:58:929] Info : spi_bit_per_word = 8
[21:24:58:929] Info : spi_cs_chip = gpiochip0
[21:24:58:929] Info : spi_cs_pin = 8
[21:24:58:930] Info : spi_irq_chip = gpiochip0
[21:24:58:930] Info : spi_irq_pin = 22
[21:24:58:930] Info : fu_reset_chip = gpiochip0
[21:24:58:930] Info : fu_spi_reset_pin = 23
[21:24:58:930] Info : fu_wake_chip = gpiochip0
[21:24:58:930] Info : fu_spi_wake_pin = 24
[21:24:58:930] Info : fu_recovery_enabled = false
[21:24:58:930] Info : fu_connect_to_bootloader = false
[21:24:58:930] Info : fu_enter_bootloader = false
[21:24:58:930] Info : fu_file = 
[21:24:58:930] Info : fu_restart_daemon = false
[21:24:58:930] Info : board_controller_ip_addr = 
[21:24:58:930] Info : application_version_validation = false
[21:24:58:930] Info : print_secondary_versions_and_exit = false
[21:24:58:930] Info : use_noop_keep_alive = false
[21:24:58:930] Info : reset_sequence = true
[21:24:58:930] Info : uart_validation_test_option = 
[21:24:58:930] Info : stats_interval = 0
[21:24:58:930] Info : rlimit_nofile = 2000
[21:24:58:930] Info : ENCRYPTION IS DISABLED 
[21:24:58:930] Info : Starting daemon in normal mode
[21:24:58:952] Info : Connecting to Secondary...
[21:25:00:952] Info : Failed to connect to Secondary.
[21:25:00:952] Info : Connecting to Secondary...
... etc ....
```

**Comment by Moqume** [comment]
Oh, and the `Failed to connect to Secondary` appears to be due to the baud rate being set to `230400`. Setting it to `115200` allows it to start without issue:

```
s6-rc: info: service banner successfully started
s6-rc: info: service universal-silabs-flasher: starting
[21:51:05] INFO: Flashing firmware is disabled
s6-rc: info: service universal-silabs-flasher successfully started
s6-rc: info: service cpcd: starting
[21:51:05] INFO: Starting cpcd...
s6-rc: info: service cpcd successfully started
s6-rc: info: service zigbeed: starting
s6-rc: info: service otbr-agent: starting
s6-rc: info: service zigbeed successfully started
[21:51:06] INFO: Starting zigbeed...
[21:51:05:625] Info : [CPCd v4.1.4.0] [Library API v2] [RCP Protocol v2]
[21:51:05:626] Info : Git commit: 5df3ef9fb8891987b623b623694ec4c435ea5644 / branch: 
[21:51:05:626] Info : Sources hash: 2606b603ff85938a832e691804f2d1fcf86745370d236a1a9c47f03bdf95898e
[21:51:05:626] Info : Reading cli arguments
[21:51:05:626] Info : /usr/local/bin/cpcd 
[21:51:05:645] Info : Reading configuration
[21:51:05:645] Info : file_path = /usr/local/etc/cpcd.conf
[21:51:05:645] Info : instance_name = cpcd_0
[21:51:05:645] Info : socket_folder = /dev/shm
[21:51:05:645] Info : operation_mode = MODE_NORMAL
[21:51:05:645] Info : use_encryption = false
[21:51:05:645] Info : binding_key_file = /etc/binding-key.key
[21:51:05:645] Info : binding_method = 
[21:51:05:645] Info : stdout_tracing = false
[21:51:05:645] Info : file_tracing = false
[21:51:05:645] Info : lttng_tracing = false
[21:51:05:645] Info : enable_frame_trace = false
[21:51:05:645] Info : traces_folder = /dev/shm/cpcd-traces
[21:51:05:645] Info : bus = UART
[21:51:05:645] Info : uart_baudrate = 115200
[21:51:05:645] Info : uart_hardflow = true
[21:51:05:645] Info : uart_file = /dev/ttyUSB0
[21:51:05:645] Info : spi_file = /dev/spidev0.0
[21:51:05:645] Info : spi_bitrate = 1000000
[21:51:05:645] Info : spi_mode = SPI_MODE_0
[21:51:05:645] Info : spi_bit_per_word = 8
[21:51:05:645] Info : spi_cs_chip = gpiochip0
[21:51:05:645] Info : spi_cs_pin = 8
[21:51:05:645] Info : spi_irq_chip = gpiochip0
[21:51:05:645] Info : spi_irq_pin = 22
[21:51:05:645] Info : fu_reset_chip = gpiochip0
[21:51:05:645] Info : fu_spi_reset_pin = 23
[21:51:05:645] Info : fu_wake_chip = gpiochip0
[21:51:05:645] Info : fu_spi_wake_pin = 24
[21:51:05:645] Info : fu_recovery_enabled = false
[21:51:05:645] Info : fu_connect_to_bootloader = false
[21:51:05:646] Info : fu_enter_bootloader = false
[21:51:05:646] Info : fu_file = 
[21:51:05:646] Info : fu_restart_daemon = false
[21:51:05:646] Info : board_controller_ip_addr = 
[21:51:05:646] Info : application_version_validation = false
[21:51:05:646] Info : print_secondary_versions_and_exit = false
[21:51:05:646] Info : use_noop_keep_alive = false
[21:51:05:646] Info : reset_sequence = true
[21:51:05:646] Info : uart_validation_test_option = 
[21:51:05:646] Info : stats_interval = 0
[21:51:05:646] Info : rlimit_nofile = 2000
[21:51:05:646] Info : ENCRYPTION IS DISABLED 
[21:51:05:646] Info : Starting daemon in normal mode
[21:51:05:668] Info : Connecting to Secondary...
[21:51:05:752] Info : Connected to Secondary
[21:51:05:758] Info : Secondary Protocol v2
[21:51:05:771] Info : Secondary CPC v4.1.4
[21:51:05:778] Info : Secondary APP vUNDEFINED
[21:51:05:778] Info : Daemon startup was successful. Waiting for client connections
[21:51:06] INFO: Setup OTBR firewall...
[21:51:07] INFO: Starting otbr-agent...
otbr-agent[269]: [NOTE]-AGENT---: Running 0.3.0
otbr-agent[269]: [NOTE]-AGENT---: Thread version: 1.3.0
otbr-agent[269]: [NOTE]-AGENT---: Thread interface: wpan0
otbr-agent[269]: [NOTE]-AGENT---: Backbone interface: enp1s0
otbr-agent[269]: [NOTE]-AGENT---: Radio URL: spinel+cpc://cpcd_0?iid=2
otbr-agent[269]: 49d.17:07:50.784 [C] Platform------: mCpcBusSpeed = 115200
[21:51:07:110] Info : Client is using library v2
[21:51:07:117] Info : Opened connection socket for ep#12
[21:51:07:117] Info : Endpoint socket #12: Client connected. 1 connections
[21:51:07:716] Info : Client is using library v2
[21:51:07:727] Info : Endpoint socket #12: Client connected. 2 connections
otbr-agent[269]: 49d.17:07:52.858 [N] Platform------: RCP API Version: 6
otbr-agent[269]: 00:00:00.148 [W] Platform------: Error processing result: NotFound
otbr-agent[269]: 00:00:00.148 [W] Platform------: Error waiting response: NotFound
otbr-agent[269]: 00:00:00.150 [N] BorderRouter--: BR ULA prefix: xxxx:xxxx:xxxx::/48 (loaded)
otbr-agent[269]: 00:00:00.151 [N] BorderRouter--: Local on-link prefix: xxxx:xxxx:beef:cafe::/64
otbr-agent[269]: 00:00:00.165 [N] BorderRouter--: Local on-link prefix: xxxx:xxxxbeef:cafe::/64
s6-rc: info: service otbr-agent successfully started
s6-rc: info: service otbr-agent-rest-discovery: starting
s6-rc: info: service otbr-web: starting
s6-rc: info: service otbr-web successfully started
[21:51:09] INFO: Starting otbr-web...
otbr-web[360]: [INFO]-WEB-----: Running 0.3.0
otbr-web[360]: [INFO]-WEB-----: Border router web started on wpan0
[21:51:10] INFO: Successfully sent discovery information to Home Assistant.
s6-rc: info: service otbr-agent-rest-discovery successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Listening on port 9999 for connection...
Accepting connection.
```

**Comment by ALutz273** [comment]
The problem looks exactly the same for me. 
With 230400 or with 115200
[run1.txt](https://github.com/home-assistant/addons/files/10611715/run1.txt)
[run2.txt](https://github.com/home-assistant/addons/files/10611716/run2.txt)

**Comment by DiaboloVampire** [comment]
I have exactly the same issues as you described. Hopefully they fix it soon. Don’t want to flash firmware manually.

**Comment by miniminne** [comment]
> 

Hey, I'm having the same issues as listed here but even when I try to manually flash I'm hit with "Error: failed to probe application type". Any advice? This fails when trying to probe ApplicationType.EZSP

**Comment by Moqume** [comment]
To note, I resolved the `Failed to connect to Secondary.` loop (after disabling the `Automatically flash firmware` option) the following way (whilst the Silicon Labs Multiprotocol add-on was running):

1. Disconnect the Skyconnect from the USB
2. Delete the `Zigbee Home Automation` device.
3. Plug the Skyconnect back in (while the Silicon Labs Multiprotocol add-on was already running).

HA will discover a new device at this point, `SkyConnect Multi-PAN` (also Zigbee Home Automation, but didn't show it as `Multi-PAN` AFAICR).  It already had the right details pre-set (The USB ID, EZSP, etc), so didn't have to change anything setting up the device.

Then the add-on stopped looping at  `Failed to connect to Secondary.`:

```
[20:35:45:219] Info : Connecting to Secondary...
[20:35:45:303] Info : Connected to Secondary
[20:35:45:309] Info : Secondary Protocol v2
[20:35:45:322] Info : Secondary CPC v4.1.4
[20:35:45:328] Info : Secondary APP vUNDEFINED
[20:35:45:329] Info : Daemon startup was successful. Waiting for client connections
[20:35:46] INFO: Setup OTBR firewall...
[20:35:46] INFO: Starting otbr-agent...
otbr-agent[268]: [NOTE]-AGENT---: Running 0.3.0
otbr-agent[268]: [NOTE]-AGENT---: Thread version: 1.3.0
otbr-agent[268]: [NOTE]-AGENT---: Thread interface: wpan0
otbr-agent[268]: [NOTE]-AGENT---: Backbone interface: enp1s0
otbr-agent[268]: [NOTE]-AGENT---: Radio URL: spinel+cpc://cpcd_0?iid=2
otbr-agent[268]: [INFO]-NCP-----: OpenThread log level changed to 4
otbr-agent[268]: 51d.15:04:10.331 [C] Platform------: mCpcBusSpeed = 115200
otbr-agent[268]: 51d.15:04:10.331 [I] Platform------: RCP reset: RESET_SOFTWARE
[20:35:46:605] Info : Client is using library v2
[20:35:46:612] Info : Opened connection socket for ep#12
[20:35:46:612] Info : Endpoint socket #12: Client connected. 1 connections
[20:35:47:174] Info : Client is using library v2
[20:35:47:184] Info : Endpoint socket #12: Client connected. 2 connections
otbr-agent[268]: 51d.15:04:12.405 [I] Platform------: RCP reset: RESET_UNKNOWN
otbr-agent[268]: 51d.15:04:12.457 [N] Platform------: RCP API Version: 6
otbr-agent[268]: 51d.15:04:12.469 [I] Platform------: Backbone interface is configured to enp1s0 (2)
...etc...
```

YMMV.

**Comment by mlacayoemery** [comment]
> Context: [NabuCasa/silabs-firmware#9](https://github.com/NabuCasa/silabs-firmware/issues/9)
> 
> This is happening because the SkyConnect has firmware configured for a baudrate of `230400` and the addon is trying to flash the device connecting at a baudrate of `115200`:
> 
> ```
> [17:22:39] INFO: Starting universal-silabs-flasher with /dev/ttyUSB0 (baudrate 115200)
> ```
> 
> I don't own a SkyConnect but I'm guessing that either the addon flashed a `230400` baudrate firmware in the past or users having issues flashed a `230400` baudrate firmware manually. By the git history, I guess it was the later.
> 
> For @regevbr just flash manually the SkyConnect again like this:
> 
> ```shell
> universal-silabs-flasher --device /dev/ttyUSB1 --baudrate 230400 flash --firmware NabuCasa_SkyConnect_RCP_v4.1.4_rcp-uart-hw-802154_115200.gbl
> ```
> 
> You can grab the firmware file from here: https://github.com/home-assistant/addons/tree/master/silabs-multiprotocol/rootfs/root

Thanks to @skgsergio this sent me down the right path. I followed the instructions in the wiki (https://github.com/NabuCasa/silabs-firmware/wiki/Flash-Silicon-Labs-radio-firmware-manually) and was able to flash [version 4.2.0](https://github.com/NabuCasa/silabs-firmware/blob/main/RCPMultiPAN/NabuCasa_SkyConnect_RCP_v4.2.0_rcp-uart-hw-802154_115200.gbl) after connecting it to my computer and this problem was resolved. I was not able to flash directly from Home Assistant OS.

Now I have issue #2872

**Comment by HabelStefan** [comment]
I'm trying to flash from my Mac, but even that does not work.

**Comment by slider162** [comment]
2023-03-07 10:39:22 core-silabs-multiprotocol universal_silabs_flasher.flasher[236] INFO Probing ApplicationType.EZSP
Error: Failed to probe running application type

I get the same error at either baud rate.  Same error in HA or manually flashing.

**Comment by agners** [comment]
The universal-silabs-flasher got updated recently.

@ALutz273 (or someone else) is this still a problem for you?

**Comment by Mrsash2020** [comment]
Yup not working for me currently

**Comment by EddieDSuza** [comment]
Adding some context here - please check the logs and confirm which baudrate its reporting. Update the configuration with that value and restart. Thats how I was able to add both protocols to my HA instance

**Comment by agners** [comment]
If automatic firmware updating is enabled (by default), with the recent versions of this add-on the baudrate configuration is *always* taken from the firmware metadata (since we *know* the firmware communicates at this baud rate). The user configuration is not really doing anything in that case. It doesn't hurt to update the baudrate, but it also doesn't change anything really.

So if changing the baudrate helped, then it is because you had to restart the add-on due to that.
