### ISSUE TITLE
Silicon Labs Multiprotocol Broken with version 1.0.0

### ISSUE THREAD

**Issue by Mrsash2020** [home-assistant/addons#2901]
After upgrade it does not work. broke Z2MQTT as well

```
[12:29:39] INFO: The otbr-web is disabled.
s6-rc: info: service mdns: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service mdns successfully started
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
[12:29:39] INFO: Starting mDNS Responder...
Default: mDNSResponder (Engineering Build) (Mar  1 2023 17:42:59) starting
Default: mDNS_AddDNSServer: Lock not held! mDNS_busy (0) mDNS_reentrancy (0)
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/check-cpcd-shm.sh
cont-init: info: /etc/cont-init.d/check-cpcd-shm.sh exited 0
cont-init: info: running /etc/cont-init.d/config.sh
[12:29:40] INFO: Generating cpcd configuration.
cont-init: info: /etc/cont-init.d/config.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service banner: starting
-----------------------------------------------------------
 Add-on: Silicon Labs Multiprotocol
 Zigbee and OpenThread multiprotocol add-on
-----------------------------------------------------------
 Add-on version: 1.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (amd64 / qemux86-64)
 Home Assistant Core: 2023.3.1
 Home Assistant Supervisor: 2023.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service universal-silabs-flasher: starting
[12:29:40] INFO: Checking /dev/ttyUSB0 identifying SkyConnect v1.0 from Nabu Casa.
[12:29:40] INFO: Starting universal-silabs-flasher with /dev/ttyUSB0 (baudrate 115200)
2023-03-04 12:29:41 core-silabs-multiprotocol universal_silabs_flasher.flash[237] INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version=<AwesomeVersion SemVer '4.2.1'>, ezsp_version=None, fw_type=<FirmwareImageType.RCP_UART_802154: 'rcp-uart-802154'>)
2023-03-04 12:29:41 core-silabs-multiprotocol universal_silabs_flasher.flasher[237] INFO Probing ApplicationType.GECKO_BOOTLOADER
2023-03-04 12:29:43 core-silabs-multiprotocol universal_silabs_flasher.flasher[237] INFO Probing ApplicationType.CPC
2023-03-04 12:29:47 core-silabs-multiprotocol universal_silabs_flasher.flasher[237] INFO Probing ApplicationType.EZSP
Error: Failed to probe running application type
2023-03-04 12:29:52 core-silabs-multiprotocol concurrent.futures[237] ERROR exception calling callback for <Future at 0x7f2ce1d35550 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.9/asyncio/futures.py", line 398, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 791, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
s6-rc: warning: unable to start service universal-silabs-flasher: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service mdns: stopping
s6-rc: info: service banner: stopping
Default: mDNSResponder (Engineering Build) (Mar  1 2023 17:42:59) stopping
s6-rc: info: service banner successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
[12:29:52] INFO: mDNS ended with exit code 4 (signal 0)...
s6-rc: info: service mdns successfully stopped
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

1.0

### Steps to reproduce the issue

1upgraded to the latest version
2.
3.
...

### System Health information

There are currently no repairs available

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:124
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 12:05:57 PM (12 occurrences)
Last logged: 12:29:35 PM

Failed to to call /addons/core_silabs_multiprotocol/stats - Container addon_core_silabs_multiprotocol is not running
Failed to to call /addons/45df7312_zigbee2mqtt/stats - Container addon_45df7312_zigbee2mqtt is not running
Failed to to call /addons/core_silabs_multiprotocol/stats - 404 Client Error for http+docker://localhost/v1.41/containers/addon_core_silabs_multiprotocol/json: Not Found ("No such container: addon_core_silabs_multiprotocol")

Logger: homeassistant.config_entries
Source: config_entries.py:1244
First occurred: 12:05:10 PM (1 occurrences)
Last logged: 12:05:10 PM

Config entry 'Open Thread Border Router' for otbr integration not ready yet: Unable to connect; Retrying in background
```

**Comment by MattWestb** [comment]
> Error: Failed to probe running application type

Its looks your system have lost connection to the SC dongle.
Try one re power by pulling the power cord out and back and looking if it finding it.

**Comment by Mrsash2020** [comment]
> > Error: Failed to probe running application type
> 
> Its looks your system have lost connection to the SC dongle. Try one re power by pulling the power cord out and back and looking if it finding it.

OMG I did so many things for this to work and unplugging and plugging it back is what fixed it. Still cant get Zigbee2MQTT working after that.
Thanks

**Comment by MattWestb** [comment]
Great !

And you was having Z2M working with  the addon and many user have trying and not getting it working at all :-))

The Zigbeed demon is having little timing problems with ZHA and can being killed then ZHA is loosing contact with it and zigbeed is doing one reset and ZHA is timing out.

I dont knowing how tricky Z2M is with the timing on the comport.

**Comment by Mrsash2020** [comment]
Before all the updates day before everything was working with skyconnect wilth multi and Zigbee2MQTT as well. After all the updates yesterday its been crazy.

**Comment by MattWestb** [comment]
I is testing getting the new IKEA Symfonisk 2 working OK with ZHA and then i restarting ZHA the addon is logging this on the disconnection and new connection with the addon:
```
Socket connection has been closed, restarting...
Listening on port 9999 for connection...
Accepting connection.
Accepted connection 17.
Restarting
[13:48:23:168771] Info : Endpoint socket #12: Client disconnected. 1 connections
[13:48:23:169177] Info : Client disconnected
[13:48:24:189143] Info : New client connection using library v4.2.1.0
[13:48:24:200613] Info : Endpoint socket #12: Client connected. 2 connections
Reusing socket from previous instance.
```
By the way HomeKitt thread devices like Nanoleaf lights is super fast then being connected with the addon and thread integration in HA :-)))

**Comment by tommyjlong** [comment]
I'll add a cross reference https://github.com/home-assistant/addons/issues/2899#issuecomment-1454146967 as I am also having issues with zigbee2mqtt with multiprotocol. Multiprotocol version 0.13.1 worked for the most part (but not always), but v1.0.0 I can't get to work.

**Comment by Mrsash2020** [comment]
Is this being debugged or fixed?

**Comment by samuelthng** [comment]
Also having issues on Z2M. Whenever connection is initiated, the following shows:
```
Listening on port 9999 for connection...
Accepting connection.
s6-rc: info: service legacy-services successfully started
otbr-agent[297]: 00:00:02.290 [N] Mle-----------: RLOC16 0000 -> fffe
otbr-agent[297]: 00:00:02.976 [N] Mle-----------: Attach attempt 1, AnyPartition reattaching with Active Dataset
otbr-agent[297]: 00:00:09.478 [N] RouterTable---: Allocate router id 0
otbr-agent[297]: 00:00:09.478 [N] Mle-----------: RLOC16 fffe -> 0000
otbr-agent[297]: 00:00:09.484 [N] Mle-----------: Role detached -> leader
otbr-agent[297]: 00:00:09.486 [N] Mle-----------: Leader partition id 0x26ff46cf
otbr-agent[297]: [NOTE]-BBA-----: BackboneAgent: Backbone Router becomes Primary!
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::28d1:5eff:fee8:5196/veth8821136/28
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::28d1:5eff:fee8:5196/veth8821136/28
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::28d1:5eff:fee8:5196/veth8821136/28
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::28d1:5eff:fee8:5196/veth8821136/28
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::28d1:5eff:fee8:5196/veth8821136/28
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::28d1:5eff:fee8:5196/veth8821136/28
Accepted connection 7.
Restarting
[11:54:10:098680] Info : Endpoint socket #12: Client disconnected. 1 connections
[11:54:10:098738] Info : Client disconnected
[11:54:11:195717] Info : New client connection using library v4.2.1.0
[11:54:11:206789] Info : Endpoint socket #12: Client connected. 2 connections
Reusing socket from previous instance.
Socket connection has been closed, restarting...
Listening on port 9999 for connection...
Accepting connection.
```

Reboot or remounting device does not resolve the issue.

**Comment by MattWestb** [comment]
For Z2M updating to last edge that was getting one fix yesterday and looks working with the addon.
https://github.com/Koenkk/zigbee2mqtt/issues/16908

**Comment by Mrsash2020** [comment]
I read the thread but unsure what I must do. Can you explain in detail please?

**Comment by MattWestb** [comment]
As Z2M user you must reading that in Z2M how to do that and its oft instruction liked in issues for instructions.

**Comment by Mrsash2020** [comment]
Ah right. You have to remove Zigbee2MQTT and install Dev version. Zigbee2MQTT Edge.

**Comment by samuelthng** [comment]
Z2M Edge didn't work for me, still getting same mDNS errors it seems.

**Comment by mex1254** [comment]
Hey there,



> Ah right. You have to remove Zigbee2MQTT and install Dev version. Zigbee2MQTT Edge.

has this been the solution? - I am also expieriencing the same issues. Has anyone managed to bring his z2m back to life?

**Comment by Mrsash2020** [comment]
Had a similar issue after the update. Try physically unplugging the dongle and plug back in. Then restart HA and report it that worked without going to Edge(developer version). if that falls then it's developer version.

**Comment by mex1254** [comment]
i found a workaround for me. i flashed back the EmberZ Firmware manually with the the homepage

https://skyconnect.home-assistant.io/firmware-update/

. Started z2m without Silicon Labs Multiprotocol addon - and all went back to normal.
I tried to reinstall the addon and flashed back the FW that comes with the plugin, but same behavior.

For now i dont need any Multiprotocol stuff so I will stay with this solution for now - will give it another try when i have the first devices that use matter...

thank you all for your advices
