### ISSUE TITLE
Multiprotocol (Thread) Boot Loop issue

### ISSUE THREAD

**Issue by dcmeglio** [home-assistant/addons#2905]
### Describe the issue you are experiencing

I had a power failure today and noticed the addon is now bootlooping. Had this before with my SkyConnect and was working with @puddly. Just hoping maybe the new logs provide something useful.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Silicon Labs Multiprotocol

### What is the version of the add-on?

1.0.0

### Steps to reproduce the issue

Start addon after a power failure

## System Information

version | core-2023.3.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.15.84-v8
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4956
Installed Version | 1.30.1
Stage | running
Available Repositories | 1254
Downloaded Repositories | 27
HACS Data | ok

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 31

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | June 25, 2023 at 8:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | us-east-1-4.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | beta
supervisor_version | supervisor-2023.03.1
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 109.3 GB
disk_used | 15.9 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Z-Wave JS UI (1.7.1), File editor (5.5.0), WeatherFlow to MQTT (3.1.6), Mosquitto broker (6.1.3), Emulated HUE (dev) (0.3.0), Samba Backup (5.2.0), ESPHome (2023.2.4), SSH & Web Terminal (13.0.3), Ring-MQTT with Video Streaming (5.1.3), Silicon Labs Multiprotocol (1.0.0), Matter Server (4.1.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 11
views | 16
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | February 24, 2023 at 12:49 AM
-- | --
current_recorder_run | March 7, 2023 at 8:25 PM
estimated_db_size | 747.33 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Anything in the add-on logs that might be useful for us?

```txt
[20:36:07] INFO: The otbr-web is disabled.
s6-rc: info: service mdns: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service mdns successfully started
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/check-cpcd-shm.sh
[20:36:07] INFO: Starting mDNS Responder...
Default: mDNSResponder (Engineering Build) (Mar  1 2023 17:49:54) starting
Default: mDNS_AddDNSServer: Lock not held! mDNS_busy (0) mDNS_reentrancy (0)
cont-init: info: /etc/cont-init.d/check-cpcd-shm.sh exited 0
cont-init: info: running /etc/cont-init.d/config.sh
[20:36:09] INFO: Generating cpcd configuration.
cont-init: info: /etc/cont-init.d/config.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service banner: starting
-----------------------------------------------------------
 Add-on: Silicon Labs Multiprotocol
 Zigbee and OpenThread multiprotocol add-on
-----------------------------------------------------------
 Add-on version: 1.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.3.1
 Home Assistant Supervisor: 2023.03.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service universal-silabs-flasher: starting
[20:36:12] INFO: Checking /dev/ttyUSB2 identifying SkyConnect v1.0 from Nabu Casa.
[20:36:12] INFO: Starting universal-silabs-flasher with /dev/ttyUSB2 (baudrate 115200)
2023-03-07 20:36:13 core-silabs-multiprotocol universal_silabs_flasher.flash[239] INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version=<AwesomeVersion SemVer '4.2.1'>, ezsp_version=None, fw_type=<FirmwareImageType.RCP_UART_802154: 'rcp-uart-802154'>)
2023-03-07 20:36:13 core-silabs-multiprotocol universal_silabs_flasher.flasher[239] INFO Probing ApplicationType.GECKO_BOOTLOADER
2023-03-07 20:36:15 core-silabs-multiprotocol universal_silabs_flasher.flasher[239] INFO Probing ApplicationType.CPC
2023-03-07 20:36:20 core-silabs-multiprotocol universal_silabs_flasher.flasher[239] INFO Probing ApplicationType.EZSP
Error: Failed to probe running application type
2023-03-07 20:36:25 core-silabs-multiprotocol concurrent.futures[239] ERROR exception calling callback for <Future at 0x7fa2f46550 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.9/asyncio/futures.py", line 398, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 791, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
s6-rc: warning: unable to start service universal-silabs-flasher: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service mdns: stopping
Default: mDNSResponder (Engineering Build) (Mar  1 2023 17:49:54) stopping
s6-rc: info: service banner: stopping
s6-rc: info: service banner successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
[20:36:25] INFO: mDNS ended with exit code 4 (signal 0)...
s6-rc: info: service mdns successfully stopped
```

**Comment by puddly** [comment]
Does the issue resolve after you physically unplug the SkyConnect and plug it back in?

**Comment by dcmeglio** [comment]
Power down first or just yank it?

**Comment by puddly** [comment]
No need to power down, just unplug it and plug it back in.

**Comment by dcmeglio** [comment]
Yup. Works after that

**Comment by wienans** [comment]
I had the same issue, and reconnecting the SkyConnect worked but power off and power on does not.

**Comment by ekobres** [comment]
I'm having similar issues with SkyConnect (Thread only) running on HAOS on a Pi4.
Anecdotally it seems to be worse with more devices on the mesh.
I currently have 62 devices - up from 31. When I had 31 everything was pretty good.

I have another Pi with a different radio that I have working as a reference OTBR which could fill in the gap here - but I cannot keep this integration from restarting - even when it's set not to start on boot. (I'll open a new issue for that.)

I do have a theory: The existing firmware limits the communication speed to 115200bps - which isn't particularly fast. With a lot of traffic, it seems like we could easily see bursts of traffic that exceed that bandwidth. This would explain why this problem appeared when I moved from 31 devices to 62 devices.

I wonder if it's not worth trying to build a version of the firmware to run at a faster UART speed.

As for the logs, here is what I am seeing:

It will run for a while, then eventually I get a nonstop loop of this:

```
[14:02:22] INFO: Starting otbr-agent...
otbr-agent[13597]: [NOTE]-AGENT---: Running 0.3.0
otbr-agent[13597]: [NOTE]-AGENT---: Thread version: 1.3.0
otbr-agent[13597]: [NOTE]-AGENT---: Thread interface: wpan0
otbr-agent[13597]: [NOTE]-AGENT---: Radio URL: spinel+cpc://cpcd_0?iid=2
otbr-agent[13597]: [NOTE]-ILS-----: Infra link selected: eth0
otbr-agent[13597]: 49d.17:28:15.361 [C] Platform------: mCpcBusSpeed = 115200
[14:02:22:296845] Info : New client connection using library v4.2.2.0
[14:02:22:304253] Info : Opened connection socket for ep#12
[14:02:22:304579] Info : Endpoint socket #12: Client connected. 1 connections
otbr-agent[13597]: 49d.17:28:19.405 [W] Platform------: Wait for response timeout
otbr-agent[13597]: 49d.17:28:19.406 [C] Platform------: HandleRcpTimeout() at radio_spinel_impl.hpp:2297: RadioSpinelNoResponse
[14:02:26] INFO: otbr-agent ended with exit code 6 (signal 0)...
OTBR_FORWARD_INGRESS  all opt    in * out wpan0  ::/0  -> ::/0  
Chain OTBR_FORWARD_INGRESS (0 references)
target     prot opt source               destination         
DROP       all      anywhere             anywhere             PKTTYPE = unicast
DROP       all      anywhere             anywhere             match-set otbr-ingress-deny-src src
ACCEPT     all      anywhere             anywhere             match-set otbr-ingress-allow-dst dst
DROP       all      anywhere             anywhere             PKTTYPE = unicast
ACCEPT     all      anywhere             anywhere            
otbr-ingress-deny-src
otbr-ingress-deny-src-swap
otbr-ingress-allow-dst
otbr-ingress-allow-dst-swap
OTBR_FORWARD_EGRESS  all opt    in wpan0 out *  ::/0  -> ::/0  
Chain OTBR_FORWARD_EGRESS (0 references)
target     prot opt source               destination         
ACCEPT     all      anywhere             anywhere            
[14:02:26] INFO: OTBR firewall teardown completed.
[14:02:26:349999] Info : Endpoint socket #12: Client disconnected. 0 connections
[14:02:26:352123] Info : Client disconnected
[14:02:28] INFO: Setup OTBR firewall...
[14:02:28] INFO: Starting otbr-agent...
```

If I power-cycle the radio, it will run for a while, but will more and more frequently disconnect with the `RadioSpinelNoResponse ` issue.

Here is what the startup looks like after restarting the SkyConnect:

```
s6-rc: info: service otbr-agent: starting
s6-rc: info: service zigbeed successfully started
[14:07:23] INFO: Starting zigbeed...
[14:07:22:657892] Info : [CPCd v4.2.2.0] [Library API v3] [RCP Protocol v3]
[14:07:22:658056] Info : Git commit: a4f53d8357b5432689773ec2eea117654f526705 / branch: 
[14:07:22:658060] Info : Sources hash: 24f9802026e003036eec3dda618f8cf060114efc9551b2fdd5eb331416b64f31
[14:07:22:658082] WARNING : In function 'main' in file /usr/src/cpc-daemon/main.c at line #188 : Running CPCd as 'root' is not recommended. Proceed at your own risk.
[14:07:22:658266] Info : Reading cli arguments
[14:07:22:658279] Info : /usr/local/bin/cpcd 
[14:07:22:664907] Info : Reading configuration
[14:07:22:664975] Info : file_path = /usr/local/etc/cpcd.conf
[14:07:22:664979] Info : instance_name = cpcd_0
[14:07:22:664982] Info : socket_folder = /dev/shm
[14:07:22:664984] Info : operation_mode = MODE_NORMAL
[14:07:22:664987] Info : use_encryption = false
[14:07:22:664989] Info : binding_key_file = /etc/binding-key.key
[14:07:22:664992] Info : binding_key_override = false
[14:07:22:664994] Info : binding_method = 
[14:07:22:664996] Info : stdout_tracing = false
[14:07:22:664998] Info : file_tracing = false
[14:07:22:665000] Info : lttng_tracing = false
[14:07:22:665003] Info : enable_frame_trace = false
[14:07:22:665005] Info : traces_folder = /dev/shm/cpcd-traces
[14:07:22:665007] Info : bus = UART
[14:07:22:665009] Info : uart_baudrate = 115200
[14:07:22:665012] Info : uart_hardflow = true
[14:07:22:665015] Info : uart_file = /dev/ttyUSB1
[14:07:22:665017] Info : spi_file = /dev/spidev0.0
[14:07:22:665019] Info : spi_bitrate = 1000000
[14:07:22:665022] Info : spi_mode = SPI_MODE_0
[14:07:22:665024] Info : spi_bit_per_word = 8
[14:07:22:665026] Info : spi_cs_chip = gpiochip0
[14:07:22:665028] Info : spi_cs_pin = 8
[14:07:22:665030] Info : spi_irq_chip = gpiochip0
[14:07:22:665033] Info : spi_irq_pin = 22
[14:07:22:665035] Info : fu_reset_chip = gpiochip0
[14:07:22:665037] Info : fu_spi_reset_pin = 23
[14:07:22:665039] Info : fu_wake_chip = gpiochip0
[14:07:22:665041] Info : fu_spi_wake_pin = 24
[14:07:22:665043] Info : fu_recovery_enabled = false
[14:07:22:665045] Info : fu_connect_to_bootloader = false
[14:07:22:665047] Info : fu_enter_bootloader = false
[14:07:22:665050] Info : fu_file = 
[14:07:22:665052] Info : restart_cpcd = false
[14:07:22:665054] Info : board_controller_ip_addr = 
[14:07:22:665056] Info : application_version_validation = false
[14:07:22:665058] Info : print_secondary_versions_and_exit = false
[14:07:22:665060] Info : use_noop_keep_alive = false
[14:07:22:665063] Info : reset_sequence = true
[14:07:22:665065] Info : uart_validation_test_option = 
[14:07:22:665067] Info : stats_interval = 0
[14:07:22:665069] Info : rlimit_nofile = 2000
[14:07:22:665071] Info : ENCRYPTION IS DISABLED 
[14:07:22:665074] Info : Starting daemon in normal mode
[14:07:22:681687] Info : Connecting to Secondary...
[14:07:22:771525] Info : Connected to Secondary
[14:07:22:777319] Info : Secondary Protocol v3
[14:07:22:789912] Info : Secondary CPC v4.2.2
[14:07:22:795796] Info : Secondary bus speed is 115200
[14:07:22:802203] Info : Secondary APP vUNDEFINED
[14:07:22:802513] Info : Daemon startup was successful. Waiting for client connections
[14:07:23] INFO: Setup OTBR firewall...
[14:07:24] INFO: Starting otbr-agent...
otbr-agent[294]: [NOTE]-AGENT---: Running 0.3.0
otbr-agent[294]: [NOTE]-AGENT---: Thread version: 1.3.0
otbr-agent[294]: [NOTE]-AGENT---: Thread interface: wpan0
otbr-agent[294]: [NOTE]-AGENT---: Radio URL: spinel+cpc://cpcd_0?iid=2
otbr-agent[294]: [NOTE]-ILS-----: Infra link selected: eth0
otbr-agent[294]: 49d.17:33:17.109 [C] Platform------: mCpcBusSpeed = 115200
[14:07:24:041866] Info : New client connection using library v4.2.2.0
[14:07:24:048910] Info : Opened connection socket for ep#12
[14:07:24:049268] Info : Endpoint socket #12: Client connected. 1 connections
[14:07:24:351693] Info : New client connection using library v4.2.2.0
[14:07:24:358746] Info : Endpoint socket #12: Client connected. 2 connections
otbr-agent[294]: 49d.17:33:19.183 [N] Platform------: RCP API Version: 6
otbr-agent[294]: 00:00:00.191 [N] BorderRouter--: BR ULA prefix: fd01:9d58:b4d9::/48 (loaded)
otbr-agent[294]: 00:00:00.192 [N] BorderRouter--: Local on-link prefix: fda6:838f:bbf8:88bb::/64
otbr-agent[294]: 00:00:00.200 [N] BorderRouter--: Local on-link prefix: fda6:838f:bbf8:88bb::/64
otbr-agent[294]: 00:00:00.275 [N] Mle-----------: Role disabled -> detached
otbr-agent[294]: 00:00:00.305 [N] Platform------: [netif] Changing interface state to up.
otbr-agent[294]: 00:00:00.346 [N] Mle-----------: RLOC16 1805 -> fffe
s6-rc: info: service otbr-agent successfully started
s6-rc: info: service otbr-agent-rest-discovery: starting
s6-rc: info: service otbr-web: starting
s6-rc: info: service otbr-web successfully started
otbr-agent[294]: 00:00:00.408 [N] Mle-----------: Attach attempt 1, AnyPartition reattaching with Active Dataset
[14:07:26] INFO: Starting otbr-web...
otbr-web[388]: [INFO]-WEB-----: Running 0.3.0
otbr-web[388]: [INFO]-WEB-----: Border router web started on wpan0
[14:07:27] INFO: Successfully sent discovery information to Home Assistant.
s6-rc: info: service otbr-agent-rest-discovery successfully started
s6-rc: info: service legacy-services: starting
Listening on port 9999 for connection...
Accepting connection.
s6-rc: info: service legacy-services successfully started
otbr-agent[294]: 00:00:01.264 [N] Mle-----------: RLOC16 fffe -> e42d
otbr-agent[294]: 00:00:01.270 [N] Mle-----------: Role detached -> child
otbr-agent[294]: 00:00:05.355 [N] MeshForwarder-: Failed to send IPv6 UDP msg, len:92, chksum:2241, ecn:no, to:0xe400, sec:yes, error:NoAck, prio:net
otbr-agent[294]: 00:00:05.355 [N] MeshForwarder-:     src:[fd7d:e897:7f23:a698:0:ff:fe00:e42d]:61631
otbr-agent[294]: 00:00:05.355 [N] MeshForwarder-:     dst:[fd7d:e897:7f23:a698:0:ff:fe00:3000]:61631
```
Then - after 1:22 it happens again:
```
otbr-agent[548]: 00:01:19.285 [N] MeshForwarder-:     dst:[fd01:9d58:b4d9:1:5708:e593:3f1f:f2]:5683
otbr-agent[548]: 00:01:22.240 [W] Platform------: radio tx timeout
otbr-agent[548]: 00:01:22.241 [C] Platform------: HandleRcpTimeout() at radio_spinel_impl.hpp:2297: RadioSpinelNoResponse
[14:09:30] INFO: otbr-agent ended with exit code 6 (signal 0)...
```

**Comment by dcmeglio** [comment]
Happened again. Seems to be related to having a power flash. I've had this happen 4 times, 3 times I can 100% confirm were during a power flash.

**Comment by dcmeglio** [comment]
I don’t think this should be closed. I still continue to have this issue any time there is a power flash.

**Comment by agners** [comment]
By power flash you refer to a power outage?

Does a regular reboot reproduces the problem too? (maybe try 3-4 reboots, as it doesn't happen always it seems?)

**Comment by agners** [comment]
Also, are you sure that there is no other integration or add-on trying to accessing the same UART?

**Comment by dcmeglio** [comment]
@agners sorry I missed your questions. Yes I mean a power outage (happened again yesterday). I have not reproduced it with a regular reboot. It happens 100% of the time though during a power outage or if I unplug the power cable. No, no other addons using the same UART.

**Comment by dcmeglio** [comment]
This is not stale it’s just not receiving any attention. The issue is consistently reproducible

**Comment by puddly** [comment]
Can you provide some more info about what you mean by "if I unplug the power cable"? What exact hardware are you using (hardware/SBC, USB hubs, power supply, etc.) and what steps do you follow to trigger this outside of a power flash event?

**Comment by dcmeglio** [comment]
Sure. If I unplug the power cable to my rpi4 I can reproduce it consistently. The solution is then to unplug the skyconnect, plug it back in, then restart the multiprotocol addon.

Hardware:
rpi4 Model B 8GB using the supplied power cable
SkyConnect is connected to a powered USB hub, https://www.amazon.com/gp/product/B00SCX6I8A/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

Let me know if you need more details.

**Comment by ekobres** [comment]
I agree - I also have a powered hub. My theory is that the Skyconnect doesn’t handle losing connection to the Pi while still powered. With a short power glitch, the Pi may reboot and the USB hub stays powered for a few seconds. Whatever the case if the Pi loses power and the Skyconnect doesn’t - multiprotocol firmware hangs until you power cycle the Skyconnect.The thread firmware doesn’t seem to have this problem.On Jul 15, 2023, at 12:33 PM, dcmeglio ***@***.***> wrote:﻿
Sure. If I unplug the power cable to my rpi4 I can reproduce it consistently. The solution is then to unplug the skyconnect, plug it back in, then restart the multiprotocol addon.
Hardware:
rpi4 Model B 8GB using the supplied power cable
SkyConnect is connected to a powered USB hub, https://www.amazon.com/gp/product/B00SCX6I8A/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
Let me know if you need more details.

**Comment by agners** [comment]
@dcmeglio is this still reproducible with the latest add-on and firmware?

I've previously tested with a powered hub, and rebooted my host, but I wasn't able to reproduce. However, I did not use the same USB Hub/Raspberry Pi combination.

**Comment by ekobres** [comment]
Happened to me just yesterday.On Aug 16, 2023, at 5:16 PM, Stefan Agner ***@***.***> wrote:﻿
@dcmeglio is this still reproducible with the latest add-on and firmware?
I've previously tested with a powered hub, and rebooted my host, but I wasn't able to reproduce. However, I did not use the same USB Hub/Raspberry Pi combination.

**Comment by puddly** [comment]
I'll pick up that specific hub and see if I can reproduce your issue.

There were some recent bugfixes in the multiprotocol firmware that related to crashes so if you haven't upgraded to the latest version of the addon, try it out.

**Comment by puddly** [comment]
@ekobres I'm testing with:

 - The official Raspberry Pi power supply
 - 8GB Raspberry Pi 4
 - The hub you linked to: https://www.amazon.com/gp/product/B00SCX6I8A

The SkyConnect is plugged into a USB extension cable and into one of the hub's ports, and the hub's USB 3.0 connector is plugged into a blue USB port on the Pi. If I unplug the Pi's USB-C connection for a second and plug it back in to simulate power loss, everything reboots after a minute or two. Multi-PAN continues to work without issues.

If you have a reliable way to reproduce this problem with your setup, let me know! I'd like to figure out the root cause and fix this problem.

**Comment by ekobres** [comment]
@puddly That’s not my hub or procedure to re-create - you may have me confused with another user. I switched to the thread-only firmware and have only had to reset the SkyConnect or OTBR once in 60 days versus almost daily.On Aug 28, 2023, at 4:38 PM, puddly ***@***.***> wrote:﻿
@ekobres I'm testing with:

The official Raspberry Pi power supply
8GB Raspberry Pi 4
The hub you linked to: https://www.amazon.com/gp/product/B00SCX6I8A

The SkyConnect is plugged into a USB extension cable and into one of the hub's ports, and the hub's USB 3.0 connector is plugged into a blue USB port on the Pi. If I unplug the Pi's USB-C connection for a second and plug it back in to simulate power loss, everything reboots after a minute or two. Multi-PAN continues to work without issues.
If you have a reliable way to reproduce this problem with your setup, let me know! I'd like to figure out the root cause and fix this problem.

**Comment by dcmeglio** [comment]
@puddly I am the one with that hub. I haven't had an issue in a few weeks even after a couple power flashes. I'll keep an eye on it.

**Comment by dcmeglio** [comment]
Still experiencing this.

**Comment by puddly** [comment]
I'm trying to reproduce this issue and provide enough information to Silicon Labs to fix it.

Can you describe what specific Thread devices you have on your network? I suspect that the crash is happening on the Thread side of things, as I have been completely unable to reproduce it with just Zigbee.
