### ISSUE TITLE
Silicon Labs Multiprotocol starts OTBR on HASS reboot regardless of Add-On UI "Start on boot" setting.

### ISSUE THREAD

**Issue by ekobres** [home-assistant/addons#2921]
### Describe the issue you are experiencing

This is version 1.0.2 of the Silicon Labs Multiprotocol Add-on.

I have an experimental OTBR installed on a separate Pi with an nRF52840 dongle.
I am currently having issues with the Add-on, and would like to use my experimental OTBR instead of the SkyConnect.
The problem is that I cannot get the Add-on to not start its own OTBR when I restart HASS.

Even though "Start on Boot" and "Watchdog" are disabled, the Add-on starts anyway.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Silicon Labs Multiprotocol

### What is the version of the add-on?

1.02

### Steps to reproduce the issue

1.Disable Start on Boot for the Add on
2.Boot
3.Observe Add-on starts anyway.
...

## System Information

version | core-2023.3.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.15.84-v8
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4775
Installed Version | 1.31.0
Stage | running
Available Repositories | 1250
Downloaded Repositories | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.03.1
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 116.5 GB
disk_used | 10.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.5.0), SSH & Web Terminal (13.0.3), Z-Wave JS UI (1.7.1), ESPHome (dev) (dev), Mosquitto broker (6.1.3), Silicon Labs Multiprotocol (1.0.2), Matter Server (4.1.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 6
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 9, 2023, 9:29 AM
-- | --
current_recorder_run | March 19, 2023, 2:35 PM
estimated_db_size | 114.23 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
23-03-19 14:28:35 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:28:42 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:28:48 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:28:55 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:29:03 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:29:09 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:29:16 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:29:22 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:29:28 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:29:35 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:29:41 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:29:48 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:29:54 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:30:01 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:30:07 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:30:13 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:30:20 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:30:26 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:30:33 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:30:39 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:30:46 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:30:52 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:30:58 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:31:05 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:31:11 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:31:18 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:31:24 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:31:28 INFO (SyncWorker_1) [supervisor.docker.interface] Stopping addon_core_silabs_multiprotocol application
23-03-19 14:31:34 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_core_silabs_multiprotocol application
23-03-19 14:32:00 INFO (SyncWorker_6) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/raspberrypi4-64-homeassistant
23-03-19 14:32:30 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
23-03-19 14:32:37 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
23-03-19 14:32:37 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-03-19 14:32:39 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-03-19 14:32:39 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-03-19 14:32:39 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-03-19 14:32:39 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-03-19 14:32:41 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove
23-03-19 14:32:41 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove
23-03-19 14:33:30 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-silabs-multiprotocol with version 1.0.2
23-03-19 14:33:34 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
23-03-19 14:33:43 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:34:02 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:34:10 INFO (SyncWorker_7) [supervisor.docker.interface] Stopping addon_core_silabs_multiprotocol application
23-03-19 14:34:15 INFO (SyncWorker_7) [supervisor.docker.interface] Cleaning addon_core_silabs_multiprotocol application
23-03-19 14:34:32 INFO (SyncWorker_6) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/raspberrypi4-64-homeassistant
23-03-19 14:35:51 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
23-03-19 14:35:58 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
23-03-19 14:35:58 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-03-19 14:36:00 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-03-19 14:36:00 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-03-19 14:36:00 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-03-19 14:36:00 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-03-19 14:36:02 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 184, in block_bad_requests
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 200, in system_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 267, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 279, in core_proxy
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 62, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/api/store.py", line 178, in store_info
    ATTR_ADDONS: [
  File "/usr/src/supervisor/supervisor/api/store.py", line 179, in <listcomp>
    self._generate_addon_information(self.sys_addons.store[addon])
  File "/usr/src/supervisor/supervisor/api/store.py", line 114, in _generate_addon_information
    ATTR_ADVANCED: addon.advanced,
  File "/usr/src/supervisor/supervisor/addons/model.py", line 227, in advanced
    return self.data[ATTR_ADVANCED]
  File "/usr/src/supervisor/supervisor/store/addon.py", line 19, in data
    return self.sys_store.data.addons[self.slug]
KeyError: '5c53de3b_esphome-dev'
23-03-19 14:36:03 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove
23-03-19 14:36:03 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove
23-03-19 14:36:49 INFO (SyncWorker_6) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-silabs-multiprotocol with version 1.0.2
23-03-19 14:36:52 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
23-03-19 14:37:02 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:37:07 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-03-19 14:37:20 INFO (SyncWorker_0) [supervisor.docker.interface] Stopping addon_core_silabs_multiprotocol application
23-03-19 14:37:25 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_core_silabs_multiprotocol application
23-03-19 14:37:39 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
23-03-19 14:37:39 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM
23-03-19 14:37:39 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
23-03-19 14:38:55 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
23-03-19 14:38:55 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
23-03-19 14:38:55 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
23-03-19 14:38:55 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.NO_CURRENT_BACKUP/ContextType.SYSTEM
23-03-19 14:39:34 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
```

**Comment by ekobres** [comment]
No longer occurring in most recent t version.
