### ISSUE TITLE
MQTT broker on HassOS 10.0.rc1: Error: Unable to create websockets listener on port 1884.

### ISSUE THREAD

**Issue by casakampa** [home-assistant/addons#2935]
### Describe the issue you are experiencing

After upgrading the HassOS to version 10.0.rc1, the MQTT broker halts after being unable to create a websocket listener on port 1884.

When downgrading back to HassOS 9.5, everything is working as expected.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.1.3

### Steps to reproduce the issue

1. Upgrade HassOS 9.5 to 10.0.rc1

## System Information

version | core-2023.3.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 6.1.21
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 12

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.0.rc1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.03.2
agent_version | 1.5.1
docker_version | 23.0.1
disk_total | 30.8 GB
disk_used | 9.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.1.3), Terminal & SSH (9.6.1), Studio Code Server (5.5.4), MariaDB (2.5.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 2
views | 12
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 18 maart 2023 om 16:11
-- | --
current_recorder_run | 25 maart 2023 om 07:54
estimated_db_size | 92.42 MiB
database_engine | mysql
database_version | 10.6.10

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
23-03-25 07:54:09 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-mariadb with version 2.5.2
23-03-25 07:54:09 INFO (SyncWorker_2) [supervisor.docker.interface] Attaching to homeassistant/amd64-addon-ssh with version 9.6.1
23-03-25 07:54:09 INFO (SyncWorker_3) [supervisor.docker.interface] Attaching to ghcr.io/hassio-addons/vscode/amd64 with version 5.5.4
23-03-25 07:54:09 INFO (MainThread) [supervisor.backups.manager] Found 7 backup files
23-03-25 07:54:09 INFO (MainThread) [supervisor.discovery] Loaded 1 messages
23-03-25 07:54:09 INFO (MainThread) [supervisor.ingress] Loaded 0 ingress sessions
23-03-25 07:54:09 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.SETUP
23-03-25 07:54:09 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-03-25 07:54:09 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
23-03-25 07:54:09 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-03-25 07:54:09 INFO (MainThread) [supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not running - CoreState.SETUP
23-03-25 07:54:09 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
23-03-25 07:54:09 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-03-25 07:54:09 INFO (MainThread) [__main__] Running Supervisor
23-03-25 07:54:09 INFO (MainThread) [supervisor.os.manager] Rauc: A - marked slot kernel.0 as good
23-03-25 07:54:09 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.INITIALIZE' starting 0 add-ons
23-03-25 07:54:09 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SYSTEM' starting 2 add-ons
23-03-25 07:54:09 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-25 07:54:10 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mariadb with version 2.5.2
23-03-25 07:54:12 INFO (MainThread) [supervisor.services.modules.mysql] Set core_mariadb as service provider for MySQL
23-03-25 07:54:15 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SERVICES' starting 2 add-ons
23-03-25 07:54:15 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-ssh with version 9.6.1
23-03-25 07:54:16 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/vscode/amd64 with version 5.5.4
23-03-25 07:54:16 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-25 07:54:16 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-25 07:54:16 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-25 07:54:21 INFO (MainThread) [supervisor.core] Start Home Assistant Core
23-03-25 07:54:21 INFO (SyncWorker_4) [supervisor.docker.interface] Starting homeassistant
23-03-25 07:54:21 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
23-03-25 07:54:22 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-25 07:54:22 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-25 07:54:23 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-25 07:54:25 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.STARTUP
23-03-25 07:54:25 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-03-25 07:54:26 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-03-25 07:54:26 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-03-25 07:54:26 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-03-25 07:54:26 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-03-25 07:54:27 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove
23-03-25 07:54:27 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove
23-03-25 07:54:28 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-25 07:54:28 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-25 07:54:28 ERROR (SyncWorker_5) [supervisor.docker.interface] Can't read stats from addon_core_mosquitto: Expecting value: line 1 column 1 (char 0)
23-03-25 07:54:29 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-25 07:54:34 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-25 07:54:34 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-25 07:54:35 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-25 07:54:40 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-25 07:54:40 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-25 07:54:41 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-25 07:54:46 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-25 07:54:46 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-25 07:54:46 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-25 07:54:47 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
23-03-25 07:54:47 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.APPLICATION' starting 0 add-ons
23-03-25 07:54:47 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled
23-03-25 07:54:47 INFO (MainThread) [supervisor.core] Supervisor is up and running
23-03-25 07:54:47 INFO (MainThread) [supervisor.host.info] Updating local host information
23-03-25 07:54:47 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-03-25 07:54:47 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
23-03-25 07:54:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM
23-03-25 07:54:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
23-03-25 07:54:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
23-03-25 07:54:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
23-03-25 07:54:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
23-03-25 07:54:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.NO_CURRENT_BACKUP/ContextType.SYSTEM
23-03-25 07:54:47 INFO (MainThread) [supervisor.resolution.module] Create new suggestion SuggestionType.CREATE_FULL_BACKUP - ContextType.SYSTEM / None
23-03-25 07:54:47 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.NO_CURRENT_BACKUP - ContextType.SYSTEM / None
23-03-25 07:54:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
23-03-25 07:54:47 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
23-03-25 07:54:48 INFO (MainThread) [supervisor.host.services] Updating service information
23-03-25 07:54:48 INFO (MainThread) [supervisor.host.network] Updating local network information
23-03-25 07:54:48 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-03-25 07:54:48 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
23-03-25 07:54:48 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
23-03-25 07:54:48 INFO (MainThread) [supervisor.host.manager] Host information reload completed
23-03-25 07:54:48 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-03-25 07:54:48 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
23-03-25 07:54:48 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-03-25 07:54:52 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-25 07:54:52 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-25 07:54:52 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-25 07:54:57 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-25 07:54:57 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-25 07:54:58 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-25 07:55:03 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-25 07:55:03 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-25 07:55:04 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-25 07:55:09 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-25 07:55:09 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-25 07:55:09 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-25 07:55:15 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1062' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:989> exception=AddonsJobError('Rate limit exceeded, more then 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1003, in watchdog_container
    await self._restart_after_problem(self, event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 144, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more then 10 calls in 0:30:00
```

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/mosquitto.sh
[07:55:10] INFO: SSL is not enabled
cont-init: info: /etc/cont-init.d/mosquitto.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun mosquitto (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
[07:55:10] INFO: Starting NGINX for authentication handling...
[07:55:11] INFO: Starting mosquitto MQTT broker...
2023-03-25 07:55:11: Warning: Mosquitto should not be run as root/administrator.
2023-03-25 07:55:11: mosquitto version 2.0.11 starting
2023-03-25 07:55:11: Config loaded from /etc/mosquitto/mosquitto.conf.
2023-03-25 07:55:11: Loading plugin: /usr/share/mosquitto/go-auth.so
2023-03-25 07:55:11:  ├── Username/password checking enabled.
2023-03-25 07:55:11:  ├── TLS-PSK checking enabled.
2023-03-25 07:55:11:  └── Extended authentication not enabled.
2023-03-25 07:55:11: Opening ipv4 listen socket on port 1883.
2023-03-25 07:55:11: Opening ipv6 listen socket on port 1883.
2023-03-25 07:55:11: Opening websockets listen socket on port 1884.
2023-03-25 07:55:11: Error: Unable to create websockets listener on port 1884.
[06:55:11] WARNING: Halt add-on
s6-rc: info: service legacy-services: stopping
[06:55:11] INFO: Service restart after closing
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Additional information

````
Logger: homeassistant.components.mqtt.client
Source: components/mqtt/client.py:424
Integration: MQTT (documentation, issues)
First occurred: 07:54:32 (1 occurrences)
Last logged: 07:54:32

Failed to connect to MQTT server due to exception: [Errno 111] Connection refused
````

and

````
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:842
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 07:54:28 (1 occurrences)
Last logged: 07:54:28

Could not fetch stats for core_mosquitto: Can't read stats from addon_core_mosquitto: Expecting value: line 1 column 1 (char 0)
````

**Comment by AlbertDijksma** [comment]
Same problemen after update

**Comment by waseltzer** [comment]
downgraded os to resolve problem:
`ha os update --version 9.5`

**Comment by irresisti** [comment]
Same issue here.

**Comment by ResteNarquois** [comment]
Seems it was already [reported for the HassOS dev version a few weeks ago](https://github.com/home-assistant/addons/issues/2904), and a [PR submitted to address the issue](https://github.com/home-assistant/addons/pull/2923). Downgrading does seem to be the best option in the meantime.

**Comment by agners** [comment]
This very much looks like the same as #2904: It seems that the newer Kernel version (6.1.20) of HAOS 10.0.rc1 triggers a bug in libwebsockets.

**Comment by FrancoLoco** [comment]
thanks!!
