### ISSUE TITLE
Error when try to do Mosquito update 6.2.0

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [home-assistant/addons#2942]
### Describe the issue you are experiencing

When I try to do update of Mosquito add-on to V6.2.0 I get following error

Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:169
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 20:34:02 (1 occurrences)
Last logged: 20:34:02

[281472385221104] Error updating Mosquitto broker: Can't install homeassistant/aarch64-addon-mosquitto:6.2.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=6.2.0&fromImage=homeassistant%2Faarch64-addon-mosquitto&platform=linux%2Farm64: Not Found ("manifest for homeassistant/aarch64-addon-mosquitto:6.2.0 not found: manifest unknown: manifest unknown")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 51, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install homeassistant/aarch64-addon-mosquitto:6.2.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=6.2.0&fromImage=homeassistant%2Faarch64-addon-mosquitto&platform=linux%2Farm64: Not Found ("manifest for homeassistant/aarch64-addon-mosquitto:6.2.0 not found: manifest unknown: manifest unknown")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 726, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 156, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 417, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Mosquitto broker: Can't install homeassistant/aarch64-addon-mosquitto:6.2.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=6.2.0&fromImage=homeassistant%2Faarch64-addon-mosquitto&platform=linux%2Farm64: Not Found ("manifest for homeassistant/aarch64-addon-mosquitto:6.2.0 not found: manifest unknown: manifest unknown")

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.1.3

### Steps to reproduce the issue

1.
2.
3.
...
1. Try to update from V6.1.3 to V6.2.0

### System Health information

None

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:169
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 20:34:02 (1 occurrences)
Last logged: 20:34:02

[281472385221104] Error updating Mosquitto broker: Can't install homeassistant/aarch64-addon-mosquitto:6.2.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=6.2.0&fromImage=homeassistant%2Faarch64-addon-mosquitto&platform=linux%2Farm64: Not Found ("manifest for homeassistant/aarch64-addon-mosquitto:6.2.0 not found: manifest unknown: manifest unknown")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 51, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install homeassistant/aarch64-addon-mosquitto:6.2.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=6.2.0&fromImage=homeassistant%2Faarch64-addon-mosquitto&platform=linux%2Farm64: Not Found ("manifest for homeassistant/aarch64-addon-mosquitto:6.2.0 not found: manifest unknown: manifest unknown")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 726, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 156, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 417, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Mosquitto broker: Can't install homeassistant/aarch64-addon-mosquitto:6.2.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=6.2.0&fromImage=homeassistant%2Faarch64-addon-mosquitto&platform=linux%2Farm64: Not Found ("manifest for homeassistant/aarch64-addon-mosquitto:6.2.0 not found: manifest unknown: manifest unknown")
```

### Anything in the add-on logs that might be useful for us?

```txt
None
```

### Additional information

None

**Comment by K-RAD** [comment]
Same here

**Comment by ludeeus** [comment]
It's still building.
<https://github.com/home-assistant/addons/actions/runs/4534642566>

**Comment by smarthomefamilyverrips** [comment]
@ludeeus so just have to wait and try again later? .... is strange if not ready that HA already prompt to do update 🤔

**Comment by ludeeus** [comment]
Yes, wait, you can follow the status in the link I posted. When that completes for your architecture, you can hit the button.

**Comment by ludeeus** [comment]
Now its done and you can click it 👍
