### ISSUE TITLE
Cannot get SkyConnect working on VM Box

### ISSUE THREAD

**Issue by GoRingo-cz** [home-assistant/addons#2965]
### Describe the issue you are experiencing

After many many hours I need help :(

I migrated my HA from PI3 to IBM ThinClient with Windows 10, installed VM Box as described in official tutorial and restored my backup.

Since than I have an issues to run the SkyConnect. Plugin, uplugging, changing port, restarts / reboots both VM and host.. nothing helps.

VM Box - USB passed to HA

Hardware log:
```
ttyUSB0
/dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_bcaea3367d18ec11a4fdaf9347486eb0-if00-port0
Subsystem:
tty
Device path:
/dev/ttyUSB0
ID:
/dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_bcaea3367d18ec11a4fdaf9347486eb0-if00-port0
Attributes:
DEVLINKS: >-
  /dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_bcaea3367d18ec11a4fdaf9347486eb0-if00-port0
  /dev/serial/by-path/pci-0000:00:06.0-usb-0:3:1.0-port0
DEVNAME: /dev/ttyUSB0
DEVPATH: /devices/pci0000:00/0000:00:06.0/usb2/2-3/2-3:1.0/ttyUSB0/tty/ttyUSB0
ID_BUS: usb
ID_MODEL: SkyConnect_v1.0
ID_MODEL_ENC: SkyConnect\x20v1.0
ID_MODEL_ID: ea60
ID_PATH: pci-0000:00:06.0-usb-0:3:1.0
ID_PATH_TAG: pci-0000_00_06_0-usb-0_3_1_0
ID_REVISION: '0100'
ID_SERIAL: Nabu_Casa_SkyConnect_v1.0_bcaea3367d18ec11a4fdaf9347486eb0
ID_SERIAL_SHORT: bcaea3367d18ec11a4fdaf9347486eb0
ID_TYPE: generic
ID_USB_DRIVER: cp210x
ID_USB_INTERFACES: ':ff0000:'
ID_USB_INTERFACE_NUM: '00'
ID_VENDOR: Nabu_Casa
ID_VENDOR_ENC: Nabu\x20Casa
ID_VENDOR_ID: 10c4
MAJOR: '188'
MINOR: '0'
SUBSYSTEM: tty
TAGS: ':systemd:'
USEC_INITIALIZED: '135059094'
```
Silicon Labs Multiprotocol 1.0.2 log

```
 Add-on: Silicon Labs Multiprotocol
 Zigbee and OpenThread multiprotocol add-on
-----------------------------------------------------------
 Add-on version: 1.0.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (amd64 / qemux86-64)
 Home Assistant Core: 2023.3.6
 Home Assistant Supervisor: 2023.03.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service universal-silabs-flasher: starting
[18:51:22] INFO: Checking /dev/ttyUSB0 identifying SkyConnect v1.0 from Nabu Casa.
[18:51:22] INFO: Starting universal-silabs-flasher with /dev/ttyUSB0 (baudrate 115200)
2023-04-02 18:51:22 homeassistant universal_silabs_flasher.flash[238] INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version=<AwesomeVersion SemVer '4.2.2'>, ezsp_version=None, fw_type=<FirmwareImageType.RCP_UART_802154: 'rcp-uart-802154'>)
2023-04-02 18:51:22 homeassistant universal_silabs_flasher.flasher[238] INFO Probing ApplicationType.GECKO_BOOTLOADER
2023-04-02 18:51:24 homeassistant universal_silabs_flasher.flasher[238] INFO Probing ApplicationType.CPC
2023-04-02 18:51:29 homeassistant universal_silabs_flasher.flasher[238] INFO Probing ApplicationType.EZSP
Error: Failed to probe running application type
2023-04-02 18:51:34 homeassistant concurrent.futures[238] ERROR exception calling callback for <Future at 0x7f5bd7376670 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.9/asyncio/futures.py", line 398, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 791, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
s6-rc: warning: unable to start service universal-silabs-flasher: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service mdns: stopping
s6-rc: info: service banner: stopping
Default: mDNSResponder (Engineering Build) (Mar 14 2023 18:20:40) stopping
s6-rc: info: service banner successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
[18:51:34] INFO: mDNS ended with exit code 4 (signal 0)...
s6-rc: info: service mdns successfully stopped
```

SkyConnec Multi-PAN

```
Logger: homeassistant.config_entries
Source: components/zha/core/gateway.py:185
First occurred: 18:38:16 (3 occurrences)
Last logged: 18:52:59

Error setting up entry SkyConnect Multi-PAN for zha
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/zha/__init__.py", line 122, in async_setup_entry
    await zha_gateway.async_initialize()
  File "/usr/src/homeassistant/homeassistant/components/zha/core/gateway.py", line 200, in async_initialize
    raise exc
  File "/usr/src/homeassistant/homeassistant/components/zha/core/gateway.py", line 185, in async_initialize
    self.application_controller = await app_controller_cls.new(
  File "/usr/local/lib/python3.10/site-packages/zigpy/application.py", line 171, in new
    await app.startup(auto_form=auto_form)
  File "/usr/local/lib/python3.10/site-packages/zigpy/application.py", line 145, in startup
    await self.connect()
  File "/usr/local/lib/python3.10/site-packages/bellows/zigbee/application.py", line 124, in connect
    self._ezsp = await bellows.ezsp.EZSP.initialize(self.config)
  File "/usr/local/lib/python3.10/site-packages/bellows/ezsp/__init__.py", line 105, in initialize
    await ezsp._startup_reset()
  File "/usr/local/lib/python3.10/site-packages/bellows/ezsp/__init__.py", line 96, in _startup_reset
    await self.reset()
  File "/usr/local/lib/python3.10/site-packages/bellows/ezsp/__init__.py", line 125, in reset
    await self._gw.reset()
  File "/usr/local/lib/python3.10/site-packages/bellows/uart.py", line 260, in reset
    return await asyncio.wait_for(self._reset_future, timeout=RESET_TIMEOUT)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```

I cannot migrate radio ("failed to connect"), I cannot update configuration (does nothing) .. I dont know.
Any help would be appreciated,

Tomas

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Silicon Labs Multiprotocol

### What is the version of the add-on?

1.0.2

### Steps to reproduce the issue

1. Rebooting HA
2.
3.
...

### System Health information

```
## System Information

version | core-2023.3.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.15.90
arch | x86_64
timezone | Europe/Prague
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4470
Installed Version | 1.30.1
Stage | running
Available Repositories | 1247
Downloaded Repositories | 16

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | April 25, 2023 at 02:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-5.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.03.3
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 30.8 GB
disk_used | 7.6 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.2.0), Spotify Connect (0.12.3), Samba share (10.0.0), Duck DNS (1.15.0), Studio Code Server (5.5.6), Home Assistant Google Drive Backup (0.110.3), Filebrowser (2.23.0-5), Silicon Labs Multiprotocol (1.0.2), Terminal & SSH (9.6.1), ESPHome (2023.3.2), TasmoAdmin (0.24.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 9
views | 17
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 24, 2023 at 19:25
-- | --
current_recorder_run | April 2, 2023 at 18:37
estimated_db_size | 202.04 MiB
database_engine | sqlite
database_version | 3.38.5

</details>
```

**Comment by GoRingo-cz** [comment]
Sometimes, Silicon gives me this log:

```
-----------------------------------------------------------
 Add-on: Silicon Labs Multiprotocol
 Zigbee and OpenThread multiprotocol add-on
-----------------------------------------------------------
 Add-on version: 1.0.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (amd64 / qemux86-64)
 Home Assistant Core: 2023.3.6
 Home Assistant Supervisor: 2023.03.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service universal-silabs-flasher: starting
[19:20:23] INFO: Checking /dev/ttyUSB0 identifying SkyConnect v1.0 from Nabu Casa.
[19:20:23] INFO: Starting universal-silabs-flasher with /dev/ttyUSB0 (baudrate 115200)
2023-04-02 19:20:23 homeassistant universal_silabs_flasher.flash[238] INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version=<AwesomeVersion SemVer '4.2.2'>, ezsp_version=None, fw_type=<FirmwareImageType.RCP_UART_802154: 'rcp-uart-802154'>)
2023-04-02 19:20:23 homeassistant universal_silabs_flasher.flasher[238] INFO Probing ApplicationType.GECKO_BOOTLOADER
2023-04-02 19:20:25 homeassistant universal_silabs_flasher.flasher[238] INFO Probing ApplicationType.CPC
2023-04-02 19:20:25 homeassistant universal_silabs_flasher.flasher[238] INFO Detected ApplicationType.CPC, version 4.2.2
2023-04-02 19:20:25 homeassistant universal_silabs_flasher.flash[238] INFO Detected running firmware ApplicationType.CPC, version 4.2.2
2023-04-02 19:20:25 homeassistant universal_silabs_flasher.flash[238] INFO Firmware version 4.2.2 is flashed, not upgrading
s6-rc: info: service universal-silabs-flasher successfully started
s6-rc: info: service cpcd: starting
[19:20:25] INFO: Starting cpcd...
WARNING in function 'main' in file /usr/src/cpc-daemon/main.c at line #188 : Running CPCd as 'root' is not recommended. Proceed at your own risk.
s6-rc: info: service cpcd successfully started
s6-rc: info: service zigbeed: starting
s6-rc: info: service otbr-agent: starting
s6-rc: info: service zigbeed successfully started
[19:20:26] INFO: Starting zigbeed...
[19:20:26] INFO: Setup OTBR firewall...
[19:20:26] INFO: Starting otbr-agent...
otbr-agent[290]: [NOTE]-AGENT---: Running 0.3.0
otbr-agent[290]: [NOTE]-AGENT---: Thread version: 1.3.0
otbr-agent[290]: [NOTE]-AGENT---: Thread interface: wpan0
otbr-agent[290]: [NOTE]-AGENT---: Radio URL: spinel+cpc://cpcd_0?iid=2
otbr-agent[290]: [NOTE]-ILS-----: Infra link selected: enp0s3
otbr-agent[290]: 49d.17:10:59.865 [C] Platform------: mCpcBusSpeed = 115200
[19:20:25:824637] Info : [CPCd v4.2.2.0] [Library API v3] [RCP Protocol v3]
[19:20:25:824713] Info : Git commit: a4f53d8357b5432689773ec2eea117654f526705 / branch: 
[19:20:25:824714] Info : Sources hash: 24f9802026e003036eec3dda618f8cf060114efc9551b2fdd5eb331416b64f31
[19:20:25:824716] WARNING : In function 'main' in file /usr/src/cpc-daemon/main.c at line #188 : Running CPCd as 'root' is not recommended. Proceed at your own risk.
[19:20:25:824740] Info : Reading cli arguments
[19:20:25:824743] Info : /usr/local/bin/cpcd 
[19:20:25:866753] Info : Reading configuration
[19:20:25:866759] Info : file_path = /usr/local/etc/cpcd.conf
[19:20:25:866760] Info : instance_name = cpcd_0
[19:20:25:866761] Info : socket_folder = /dev/shm
[19:20:25:866761] Info : operation_mode = MODE_NORMAL
[19:20:25:866762] Info : use_encryption = false
[19:20:25:866762] Info : binding_key_file = /etc/binding-key.key
[19:20:25:866763] Info : binding_key_override = false
[19:20:25:866763] Info : binding_method = 
[19:20:25:866764] Info : stdout_tracing = false
[19:20:25:866764] Info : file_tracing = false
[19:20:25:866765] Info : lttng_tracing = false
[19:20:25:866765] Info : enable_frame_trace = false
[19:20:25:866766] Info : traces_folder = /dev/shm/cpcd-traces
[19:20:25:866766] Info : bus = UART
[19:20:25:866766] Info : uart_baudrate = 115200
[19:20:25:866767] Info : uart_hardflow = true
[19:20:25:866768] Info : uart_file = /dev/ttyUSB0
[19:20:25:866768] Info : spi_file = /dev/spidev0.0
[19:20:25:866769] Info : spi_bitrate = 1000000
[19:20:25:866769] Info : spi_mode = SPI_MODE_0
[19:20:25:866770] Info : spi_bit_per_word = 8
[19:20:25:866770] Info : spi_cs_chip = gpiochip0
[19:20:25:866770] Info : spi_cs_pin = 8
[19:20:25:866771] Info : spi_irq_chip = gpiochip0
[19:20:25:866771] Info : spi_irq_pin = 22
[19:20:25:866772] Info : fu_reset_chip = gpiochip0
[19:20:25:866772] Info : fu_spi_reset_pin = 23
[19:20:25:866773] Info : fu_wake_chip = gpiochip0
[19:20:25:866773] Info : fu_spi_wake_pin = 24
[19:20:25:866774] Info : fu_recovery_enabled = false
[19:20:25:866774] Info : fu_connect_to_bootloader = false
[19:20:25:866775] Info : fu_enter_bootloader = false
[19:20:25:866775] Info : fu_file = 
[19:20:25:866775] Info : restart_cpcd = false
[19:20:25:866776] Info : board_controller_ip_addr = 
[19:20:25:866776] Info : application_version_validation = false
[19:20:25:866777] Info : print_secondary_versions_and_exit = false
[19:20:25:866777] Info : use_noop_keep_alive = false
[19:20:25:866778] Info : reset_sequence = true
[19:20:25:866778] Info : uart_validation_test_option = 
[19:20:25:866778] Info : stats_interval = 0
[19:20:25:866779] Info : rlimit_nofile = 2000
[19:20:25:866780] Info : ENCRYPTION IS DISABLED 
[19:20:25:866781] Info : Starting daemon in normal mode
[19:20:25:903712] Info : Connecting to Secondary...
[19:20:26:008928] Info : Connected to Secondary
[19:20:26:016428] Info : Secondary Protocol v3
[19:20:26:031073] Info : Secondary CPC v4.2.2
[19:20:26:038324] Info : Secondary bus speed is 115200
[19:20:26:045142] Info : Secondary APP vUNDEFINED
[19:20:26:045277] Info : Daemon startup was successful. Waiting for client connections
[19:20:26:644337] Info : New client connection using library v4.2.2.0
[19:20:26:671508] Info : Opened connection socket for ep#12
[19:20:26:671577] Info : Endpoint socket #12: Client connected. 1 connections
```

ZHA after "Reload Integration" still fails with same log as above
