### ISSUE TITLE
Unable to connect using https

### ISSUE THREAD

**Issue by Ayuus** [home-assistant/addons#3005]
### Describe the issue you are experiencing

Hello,
The DuckDNS add-on does not allow https connections to HA.

Config yaml:
---
domains:
  - <my domain>.duckdns.org
token: <my token>
aliases: []
lets_encrypt:
  accept_terms: true
  algo: secp384r1
  certfile: fullchain.pem
  keyfile: privkey.pem
seconds: 300
---
Log says:
---
Logger: aiohttp.server
Source: /usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py:403
First occurred: 23:01:29 (4 occurrences)
Last logged: 23:01:29

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
---

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Duck DNS

### What is the version of the add-on?

1,15, downloaded today

### Steps to reproduce the issue

1.Create account at duckdns.org, copy token
2.Download and install DuckDNS addon
3.Set port forwarding in router 8123 > <ha server>:8123

Observer that http://<<my domain>.duckdns.org:8123 works, but https://<<my domain>.duckdns.org:8123 does not.
Also, local https access fails.
In system Log, every https call results in the same error:
---
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"---
...

## System Information

version | core-2023.4.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 6.1.24
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4974
Installed Version | 1.32.1
Stage | running
Available Repositories | 1270
Downloaded Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.0
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.1
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 56.6 GB
disk_used | 4.1 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.15.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 21 april 2023 om 09:43
-- | --
current_recorder_run | 24 april 2023 om 22:59
estimated_db_size | 8.32 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: aiohttp.server
Source: /usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py:403
First occurred: 23:01:29 (4 occurrences)
Last logged: 23:01:29

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
```

**Comment by Ayuus** [comment]
Turns out you need File Editor add-on, and add

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

in configuration.yaml, as described [here](https://www.makeuseof.com/access-home-assistant-server-remotely-duckdns-letsencrypt/)
