### ISSUE TITLE
Matter Integration Fails to Connect to Matter Server 4.5.0

### ISSUE THREAD

**Issue by BillyFKidney** [home-assistant/addons#3063]
### Describe the issue you are experiencing

Upon upgrading the Matter Server Add-On from 4.4.0 to 4.5.0 the integration is unable to connect.

Restarting the Add-On then the Integration did not resolve.
Restarting Home Assistant did not resolve.

I had to roll back to 4.4.0 (so logs might be wrong)
Let me know if you need me to try the upgrade (again)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

4.5.0

### Steps to reproduce the issue

Upon upgrading the Matter Server Add-On from 4.4.0 to 4.5.0 the integration is unable to connect.

## System Information

version | core-2023.5.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 6.1.25
arch | x86_64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4991
Installed Version | 1.32.1
Stage | running
Available Repositories | 1295
Downloaded Repositories | 13

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 26

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | February 8, 2024 at 4:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | us-east-1-9.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.1
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 228.8 GB
disk_used | 11.4 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Terminal & SSH (9.7.0), Samba share (10.0.1), Mosquitto broker (6.2.1), Node-RED (14.2.0), Samba Backup (5.2.0), WeatherFlow to MQTT (3.1.6), eufy-security-ws (1.5.2), Silicon Labs Multiprotocol (1.1.3), Matter Server (4.4.0), Network UPS Tools (0.11.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 9
-- | --
resources | 1
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 15, 2023 at 4:43 PM
-- | --
current_recorder_run | May 23, 2023 at 7:56 PM
estimated_db_size | 619.04 MiB
database_engine | sqlite
database_version | 3.40.1

</details>

### Anything in the add-on logs that might be useful for us?

```txt
2023-05-24 08:07:46 core-matter-server chip.EM[126] INFO <<< [E:23213r S:26936 M:154812576 (Ack:774990)] (S) Msg TX to 1:0000000000000005 [6704] --- Type 0001:01 (IM:StatusResponse)
2023-05-24 08:07:46 core-matter-server chip.IN[126] INFO (S) Sending msg 154812576 on secure session with LSID: 26936
2023-05-24 08:07:46 core-matter-server chip.EM[126] INFO >>> [E:23213r S:26936 M:774991 (Ack:154812576)] (S) Msg RX from 1:0000000000000005 [6704] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-05-24 08:07:46 core-matter-server asyncio[126] ERROR Task exception was never retrieved
future: <Task finished name='Task-114' coro=<StorageController.async_save() done, defined at /usr/local/lib/python3.11/site-packages/matter_server/server/storage.py:138> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/storage.py", line 154, in async_save
    await self.server.loop.run_in_executor(None, do_save)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/storage.py", line 150, in do_save
    with open(self.filename, "w", encoding="utf-8") as _file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/6976234351317051140.json'
2023-05-24 08:07:46 core-matter-server chip.EM[126] INFO >>> [E:5276r S:26937 M:100778254] (S) Msg RX from 1:0000000000000006 [6704] --- Type 0001:05 (IM:ReportData)
2023-05-24 08:07:46 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 124224 milliseconds with SubscriptionId = 0xedc298e4 Peer = 01:0000000000000006
2023-05-24 08:07:46 core-matter-server chip.EM[126] INFO <<< [E:5276r S:26937 M:127143166 (Ack:100778254)] (S) Msg TX to 1:0000000000000006 [6704] --- Type 0001:01 (IM:StatusResponse)
2023-05-24 08:07:46 core-matter-server chip.IN[126] INFO (S) Sending msg 127143166 on secure session with LSID: 26937
2023-05-24 08:07:46 core-matter-server chip.EM[126] INFO >>> [E:5276r S:26937 M:100778255 (Ack:127143166)] (S) Msg RX from 1:0000000000000006 [6704] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-05-24 08:09:45 core-matter-server chip.EM[126] INFO >>> [E:7197r S:26935 M:12585907] (S) Msg RX from 1:0000000000000004 [6704] --- Type 0001:05 (IM:ReportData)
2023-05-24 08:09:45 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 124224 milliseconds with SubscriptionId = 0x9d30c1ac Peer = 01:0000000000000004
2023-05-24 08:09:45 core-matter-server chip.EM[126] INFO <<< [E:7197r S:26935 M:149502099 (Ack:12585907)] (S) Msg TX to 1:0000000000000004 [6704] --- Type 0001:01 (IM:StatusResponse)
2023-05-24 08:09:45 core-matter-server chip.IN[126] INFO (S) Sending msg 149502099 on secure session with LSID: 26935
2023-05-24 08:09:45 core-matter-server chip.EM[126] INFO >>> [E:7197r S:26935 M:12585908 (Ack:149502099)] (S) Msg RX from 1:0000000000000004 [6704] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-05-24 08:09:45 core-matter-server chip.EM[126] INFO >>> [E:3732r S:26938 M:64220870] (S) Msg RX from 1:0000000000000007 [6704] --- Type 0001:05 (IM:ReportData)
2023-05-24 08:09:46 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 124224 milliseconds with SubscriptionId = 0x63933499 Peer = 01:0000000000000007
2023-05-24 08:09:46 core-matter-server chip.EM[126] INFO <<< [E:3732r S:26938 M:194402647 (Ack:64220870)] (S) Msg TX to 1:0000000000000007 [6704] --- Type 0001:01 (IM:StatusResponse)
2023-05-24 08:09:46 core-matter-server chip.IN[126] INFO (S) Sending msg 194402647 on secure session with LSID: 26938
2023-05-24 08:09:46 core-matter-server chip.EM[126] INFO >>> [E:3732r S:26938 M:64220871 (Ack:194402647)] (S) Msg RX from 1:0000000000000007 [6704] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-05-24 08:09:46 core-matter-server chip.EM[126] INFO >>> [E:23214r S:26936 M:774992] (S) Msg RX from 1:0000000000000005 [6704] --- Type 0001:05 (IM:ReportData)
2023-05-24 08:09:46 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 124224 milliseconds with SubscriptionId = 0x3894f49f Peer = 01:0000000000000005
2023-05-24 08:09:46 core-matter-server chip.EM[126] INFO <<< [E:23214r S:26936 M:154812577 (Ack:774992)] (S) Msg TX to 1:0000000000000005 [6704] --- Type 0001:01 (IM:StatusResponse)
2023-05-24 08:09:46 core-matter-server chip.IN[126] INFO (S) Sending msg 154812577 on secure session with LSID: 26936
2023-05-24 08:09:46 core-matter-server chip.EM[126] INFO >>> [E:23214r S:26936 M:774993 (Ack:154812577)] (S) Msg RX from 1:0000000000000005 [6704] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-05-24 08:09:47 core-matter-server chip.EM[126] INFO >>> [E:5277r S:26937 M:100778256] (S) Msg RX from 1:0000000000000006 [6704] --- Type 0001:05 (IM:ReportData)
2023-05-24 08:09:47 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 124224 milliseconds with SubscriptionId = 0xedc298e4 Peer = 01:0000000000000006
2023-05-24 08:09:47 core-matter-server chip.EM[126] INFO <<< [E:5277r S:26937 M:127143167 (Ack:100778256)] (S) Msg TX to 1:0000000000000006 [6704] --- Type 0001:01 (IM:StatusResponse)
2023-05-24 08:09:47 core-matter-server chip.IN[126] INFO (S) Sending msg 127143167 on secure session with LSID: 26937
2023-05-24 08:09:47 core-matter-server chip.EM[126] INFO >>> [E:5277r S:26937 M:100778257 (Ack:127143167)] (S) Msg RX from 1:0000000000000006 [6704] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-05-24 08:11:46 core-matter-server chip.EM[126] INFO >>> [E:7198r S:26935 M:12585909] (S) Msg RX from 1:0000000000000004 [6704] --- Type 0001:05 (IM:ReportData)
2023-05-24 08:11:46 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 124224 milliseconds with SubscriptionId = 0x9d30c1ac Peer = 01:0000000000000004
2023-05-24 08:11:46 core-matter-server chip.EM[126] INFO <<< [E:7198r S:26935 M:149502100 (Ack:12585909)] (S) Msg TX to 1:0000000000000004 [6704] --- Type 0001:01 (IM:StatusResponse)
2023-05-24 08:11:46 core-matter-server chip.IN[126] INFO (S) Sending msg 149502100 on secure session with LSID: 26935
2023-05-24 08:11:46 core-matter-server chip.EM[126] INFO >>> [E:7198r S:26935 M:12585910 (Ack:149502100)] (S) Msg RX from 1:0000000000000004 [6704] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-05-24 08:11:46 core-matter-server chip.EM[126] INFO >>> [E:3733r S:26938 M:64220872] (S) Msg RX from 1:0000000000000007 [6704] --- Type 0001:05 (IM:ReportData)
2023-05-24 08:11:46 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 124224 milliseconds with SubscriptionId = 0x63933499 Peer = 01:0000000000000007
2023-05-24 08:11:46 core-matter-server chip.EM[126] INFO <<< [E:3733r S:26938 M:194402648 (Ack:64220872)] (S) Msg TX to 1:0000000000000007 [6704] --- Type 0001:01 (IM:StatusResponse)
2023-05-24 08:11:46 core-matter-server chip.IN[126] INFO (S) Sending msg 194402648 on secure session with LSID: 26938
2023-05-24 08:11:46 core-matter-server chip.EM[126] INFO >>> [E:3733r S:26938 M:64220873 (Ack:194402648)] (S) Msg RX from 1:0000000000000007 [6704] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-05-24 08:11:46 core-matter-server chip.EM[126] INFO >>> [E:23215r S:26936 M:774994] (S) Msg RX from 1:0000000000000005 [6704] --- Type 0001:05 (IM:ReportData)
2023-05-24 08:11:46 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 124224 milliseconds with SubscriptionId = 0x3894f49f Peer = 01:0000000000000005
2023-05-24 08:11:46 core-matter-server chip.EM[126] INFO <<< [E:23215r S:26936 M:154812578 (Ack:774994)] (S) Msg TX to 1:0000000000000005 [6704] --- Type 0001:01 (IM:StatusResponse)
2023-05-24 08:11:46 core-matter-server chip.IN[126] INFO (S) Sending msg 154812578 on secure session with LSID: 26936
2023-05-24 08:11:46 core-matter-server chip.EM[126] INFO >>> [E:23215r S:26936 M:774995 (Ack:154812578)] (S) Msg RX from 1:0000000000000005 [6704] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-05-24 08:11:47 core-matter-server chip.EM[126] INFO >>> [E:5278r S:26937 M:100778258] (S) Msg RX from 1:0000000000000006 [6704] --- Type 0001:05 (IM:ReportData)
2023-05-24 08:11:47 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 124224 milliseconds with SubscriptionId = 0xedc298e4 Peer = 01:0000000000000006
2023-05-24 08:11:47 core-matter-server chip.EM[126] INFO <<< [E:5278r S:26937 M:127143168 (Ack:100778258)] (S) Msg TX to 1:0000000000000006 [6704] --- Type 0001:01 (IM:StatusResponse)
2023-05-24 08:11:47 core-matter-server chip.IN[126] INFO (S) Sending msg 127143168 on secure session with LSID: 26937
2023-05-24 08:11:47 core-matter-server chip.EM[126] INFO >>> [E:5278r S:26937 M:100778259 (Ack:127143168)] (S) Msg RX from 1:0000000000000006 [6704] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-05-24 08:13:46 core-matter-server chip.EM[126] INFO >>> [E:7199r S:26935 M:12585911] (S) Msg RX from 1:0000000000000004 [6704] --- Type 0001:05 (IM:ReportData)
2023-05-24 08:13:46 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 124224 milliseconds with SubscriptionId = 0x9d30c1ac Peer = 01:0000000000000004
2023-05-24 08:13:46 core-matter-server chip.EM[126] INFO <<< [E:7199r S:26935 M:149502101 (Ack:12585911)] (S) Msg TX to 1:0000000000000004 [6704] --- Type 0001:01 (IM:StatusResponse)
2023-05-24 08:13:46 core-matter-server chip.IN[126] INFO (S) Sending msg 149502101 on secure session with LSID: 26935
2023-05-24 08:13:46 core-matter-server chip.EM[126] INFO >>> [E:7199r S:26935 M:12585912 (Ack:149502101)] (S) Msg RX from 1:0000000000000004 [6704] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-05-24 08:13:46 core-matter-server chip.EM[126] INFO >>> [E:3734r S:26938 M:64220874] (S) Msg RX from 1:0000000000000007 [6704] --- Type 0001:05 (IM:ReportData)
2023-05-24 08:13:46 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 124224 milliseconds with SubscriptionId = 0x63933499 Peer = 01:0000000000000007
2023-05-24 08:13:46 core-matter-server chip.EM[126] INFO <<< [E:3734r S:26938 M:194402649 (Ack:64220874)] (S) Msg TX to 1:0000000000000007 [6704] --- Type 0001:01 (IM:StatusResponse)
2023-05-24 08:13:46 core-matter-server chip.IN[126] INFO (S) Sending msg 194402649 on secure session with LSID: 26938
2023-05-24 08:13:46 core-matter-server chip.EM[126] INFO >>> [E:3734r S:26938 M:64220875 (Ack:194402649)] (S) Msg RX from 1:0000000000000007 [6704] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-05-24 08:13:46 core-matter-server chip.EM[126] INFO >>> [E:23216r S:26936 M:774996] (S) Msg RX from 1:0000000000000005 [6704] --- Type 0001:05 (IM:ReportData)
2023-05-24 08:13:46 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 124224 milliseconds with SubscriptionId = 0x3894f49f Peer = 01:0000000000000005
2023-05-24 08:13:46 core-matter-server chip.EM[126] INFO <<< [E:23216r S:26936 M:154812579 (Ack:774996)] (S) Msg TX to 1:0000000000000005 [6704] --- Type 0001:01 (IM:StatusResponse)
2023-05-24 08:13:46 core-matter-server chip.IN[126] INFO (S) Sending msg 154812579 on secure session with LSID: 26936
2023-05-24 08:13:47 core-matter-server chip.EM[126] INFO >>> [E:23216r S:26936 M:774997 (Ack:154812579)] (S) Msg RX from 1:0000000000000005 [6704] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-05-24 08:13:47 core-matter-server chip.EM[126] INFO >>> [E:5279r S:26937 M:100778260] (S) Msg RX from 1:0000000000000006 [6704] --- Type 0001:05 (IM:ReportData)
2023-05-24 08:13:47 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 124224 milliseconds with SubscriptionId = 0xedc298e4 Peer = 01:0000000000000006
2023-05-24 08:13:47 core-matter-server chip.EM[126] INFO <<< [E:5279r S:26937 M:127143169 (Ack:100778260)] (S) Msg TX to 1:0000000000000006 [6704] --- Type 0001:01 (IM:StatusResponse)
2023-05-24 08:13:47 core-matter-server chip.IN[126] INFO (S) Sending msg 127143169 on secure session with LSID: 26937
2023-05-24 08:13:47 core-matter-server chip.EM[126] INFO >>> [E:5279r S:26937 M:100778261 (Ack:127143169)] (S) Msg RX from 1:0000000000000006 [6704] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-05-24 08:15:46 core-matter-server chip.EM[126] INFO >>> [E:7200r S:26935 M:12585913] (S) Msg RX from 1:0000000000000004 [6704] --- Type 0001:05 (IM:ReportData)
2023-05-24 08:15:46 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 124224 milliseconds with SubscriptionId = 0x9d30c1ac Peer = 01:0000000000000004
2023-05-24 08:15:46 core-matter-server chip.EM[126] INFO <<< [E:7200r S:26935 M:149502102 (Ack:12585913)] (S) Msg TX to 1:0000000000000004 [6704] --- Type 0001:01 (IM:StatusResponse)
2023-05-24 08:15:46 core-matter-server chip.IN[126] INFO (S) Sending msg 149502102 on secure session with LSID: 26935
2023-05-24 08:15:46 core-matter-server chip.EM[126] INFO >>> [E:7200r S:26935 M:12585914 (Ack:149502102)] (S) Msg RX from 1:0000000000000004 [6704] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-05-24 08:15:46 core-matter-server chip.EM[126] INFO >>> [E:3735r S:26938 M:64220876] (S) Msg RX from 1:0000000000000007 [6704] --- Type 0001:05 (IM:ReportData)
2023-05-24 08:15:46 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 124224 milliseconds with SubscriptionId = 0x63933499 Peer = 01:0000000000000007
2023-05-24 08:15:46 core-matter-server chip.EM[126] INFO <<< [E:3735r S:26938 M:194402650 (Ack:64220876)] (S) Msg TX to 1:0000000000000007 [6704] --- Type 0001:01 (IM:StatusResponse)
2023-05-24 08:15:46 core-matter-server chip.IN[126] INFO (S) Sending msg 194402650 on secure session with LSID: 26938
2023-05-24 08:15:46 core-matter-server chip.EM[126] INFO >>> [E:3735r S:26938 M:64220877 (Ack:194402650)] (S) Msg RX from 1:0000000000000007 [6704] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-05-24 08:15:47 core-matter-server chip.EM[126] INFO >>> [E:23217r S:26936 M:774998] (S) Msg RX from 1:0000000000000005 [6704] --- Type 0001:05 (IM:ReportData)
2023-05-24 08:15:47 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 124224 milliseconds with SubscriptionId = 0x3894f49f Peer = 01:0000000000000005
2023-05-24 08:15:47 core-matter-server chip.EM[126] INFO <<< [E:23217r S:26936 M:154812580 (Ack:774998)] (S) Msg TX to 1:0000000000000005 [6704] --- Type 0001:01 (IM:StatusResponse)
2023-05-24 08:15:47 core-matter-server chip.IN[126] INFO (S) Sending msg 154812580 on secure session with LSID: 26936
2023-05-24 08:15:47 core-matter-server chip.EM[126] INFO >>> [E:23217r S:26936 M:774999 (Ack:154812580)] (S) Msg RX from 1:0000000000000005 [6704] --- Type 0000:10 (SecureChannel:StandaloneAck)
2023-05-24 08:15:47 core-matter-server chip.EM[126] INFO >>> [E:5280r S:26937 M:100778262] (S) Msg RX from 1:0000000000000006 [6704] --- Type 0001:05 (IM:ReportData)
2023-05-24 08:15:47 core-matter-server chip.DMG[126] INFO Refresh LivenessCheckTime for 124224 milliseconds with SubscriptionId = 0xedc298e4 Peer = 01:0000000000000006
2023-05-24 08:15:47 core-matter-server chip.EM[126] INFO <<< [E:5280r S:26937 M:127143170 (Ack:100778262)] (S) Msg TX to 1:0000000000000006 [6704] --- Type 0001:01 (IM:StatusResponse)
2023-05-24 08:15:47 core-matter-server chip.IN[126] INFO (S) Sending msg 127143170 on secure session with LSID: 26937
2023-05-24 08:15:47 core-matter-server chip.EM[126] INFO >>> [E:5280r S:26937 M:100778263 (Ack:127143170)] (S) Msg RX from 1:0000000000000006 [6704] --- Type 0000:10 (SecureChannel:StandaloneAck)
```

**Comment by agners** [comment]
```
FileNotFoundError: [Errno 2] No such file or directory: '/data/6976234351317051140.json'
```

Hm, looks like the server side storage file disappeared for some reason :thinking: Did you made a backup when upgrading the add-on? Can you download it and check if the file is in that backup?

**Comment by BillyFKidney** [comment]
> ```
> FileNotFoundError: [Errno 2] No such file or directory: '/data/6976234351317051140.json'
> ```
> 
> 
>     
>   
> 
> Hm, looks like the server side storage file disappeared for some reason 🤔 Did you made a backup when upgrading the add-on? Can you download it and check if the file is in that backup?

I restored the back-up of Add-On: Matter Server v4.4.0 and everything started working again.
I do not know how to extract that file from the back-up.

**Comment by agners** [comment]
> I restored the back-up of Add-On: Matter Server v4.4.0 and everything started working again.
> I do not know how to extract that file from the back-up.

You would need the a tool which can extract tarballs (e.g. 7-Zip).

Can you try upgrading again and see if that was a one-off issue? You should be able to restore the backup again in case that fails again.

**Comment by BillyFKidney** [comment]
I tried the upgrade again and it appears to have succeed. Uncertain what the issue was prior.
