### ISSUE TITLE
Issue with Silicon Labs Multiprotocol Connecting to Sonoff Zigbee Model-E

### ISSUE THREAD

**Issue by keithdw1972** [home-assistant/addons#3082]
### Describe the issue you are experiencing

Every 24 hours or so, the Silicon Labs Multiprotocol addon seems unable to connect to the USB device, this causes Zigbee2MQTT to stop working correctly. To fix this, I need to remove the USB device and replace it, in a different USB port.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

2.0.0

### Steps to reproduce the issue

1. Install Sonoff Zigbee 3.0 USB Dongle Plus
2. Flashing the Sonoff ZBDongle-E with https://github.com/darkxst firmware Multi PAN (RCP) firmware.
3. Configure Silicon Labs Multiprotocol with correct device at baudrate 460800
4. Install and configure Zigbee2MQTT

This then works, Zigbee network can be formed and controlled, but over the next 12-24 hours, the Silicon Labs Multiprotocol Add on starts to develop a problem.

## System Information

version | core-2023.6.0b4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.3
os_name | Linux
os_version | 6.1.29
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1284
Downloaded Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.2
-- | --
update_channel | beta
supervisor_version | supervisor-2023.06.0
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 30.8 GB
disk_used | 8.5 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.6.1), Mosquitto broker (6.2.1), Zigbee2MQTT (1.31.0-1), Grafana (8.3.0), PostgreSQL (1.0.0), TeslaMate (0.19.0), Advanced SSH & Web Terminal (15.0.2), Matter Server (4.5.1), Silicon Labs Multiprotocol (2.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 30 May 2023 at 21:50
-- | --
current_recorder_run | 5 June 2023 at 01:27
estimated_db_size | 71.34 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
ValueError: Set of Tasks/Futures is empty.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 160, in wrapper
    raise JobException() from err
supervisor.exceptions.JobException
[31m23-06-05 10:28:01 ERROR (MainThread) [supervisor.jobs] Unhandled exception: Set of Tasks/Futures is empty.[0m
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/mounts/manager.py", line 145, in reload
    await asyncio.wait(
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 408, in wait
    raise ValueError('Set of Tasks/Futures is empty.')
ValueError: Set of Tasks/Futures is empty.
[32m23-06-05 10:28:03 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[33m23-06-05 10:28:08 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[32m23-06-05 10:28:41 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/matt-FFFFFF/hassio-addon-repository repository[0m
[32m23-06-05 10:28:41 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository[0m
[32m23-06-05 10:28:41 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/thomasmauerer/hassio-addons repository[0m
[32m23-06-05 10:28:41 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository[0m
[32m23-06-05 10:28:41 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m23-06-05 10:28:41 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository[0m
[32m23-06-05 10:28:41 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/alexbelgium/hassio-addons repository[0m
[32m23-06-05 10:29:02 INFO (MainThread) [supervisor.store] Loading add-ons from store: 158 all - 0 new - 0 remove[0m
[32m23-06-05 10:29:02 INFO (MainThread) [supervisor.store] Loading add-ons from store: 158 all - 0 new - 0 remove[0m
[33m23-06-05 10:29:39 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Silicon Labs Multiprotocol is unhealthy, restarting...[0m
[32m23-06-05 10:29:39 INFO (SyncWorker_4) [supervisor.docker.interface] Stopping addon_core_silabs_multiprotocol application[0m
[32m23-06-05 10:29:49 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_core_silabs_multiprotocol application[0m
[32m23-06-05 10:29:50 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-silabs-multiprotocol with version 2.0.0[0m
[33m23-06-05 10:32:11 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Silicon Labs Multiprotocol is unhealthy, restarting...[0m
[32m23-06-05 10:32:11 INFO (SyncWorker_2) [supervisor.docker.interface] Stopping addon_core_silabs_multiprotocol application[0m
[32m23-06-05 10:32:21 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_core_silabs_multiprotocol application[0m
[32m23-06-05 10:32:21 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-silabs-multiprotocol with version 2.0.0[0m
[33m23-06-05 10:33:14 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[33m23-06-05 10:34:42 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Silicon Labs Multiprotocol is unhealthy, restarting...[0m
[32m23-06-05 10:34:42 INFO (SyncWorker_1) [supervisor.docker.interface] Stopping addon_core_silabs_multiprotocol application[0m
[32m23-06-05 10:34:52 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_core_silabs_multiprotocol application[0m
[32m23-06-05 10:34:52 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-silabs-multiprotocol with version 2.0.0[0m
[33m23-06-05 10:37:13 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Silicon Labs Multiprotocol is unhealthy, restarting...[0m
[32m23-06-05 10:37:13 INFO (SyncWorker_1) [supervisor.docker.interface] Stopping addon_core_silabs_multiprotocol application[0m
[32m23-06-05 10:37:23 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_core_silabs_multiprotocol application[0m
[32m23-06-05 10:37:23 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-silabs-multiprotocol with version 2.0.0[0m
[33m23-06-05 10:38:20 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[33m23-06-05 10:39:44 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Silicon Labs Multiprotocol is unhealthy, restarting...[0m
[32m23-06-05 10:39:44 INFO (SyncWorker_4) [supervisor.docker.interface] Stopping addon_core_silabs_multiprotocol application[0m
[32m23-06-05 10:39:54 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_core_silabs_multiprotocol application[0m
[32m23-06-05 10:39:55 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-silabs-multiprotocol with version 2.0.0[0m
[33m23-06-05 10:42:16 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Silicon Labs Multiprotocol is unhealthy, restarting...[0m
[32m23-06-05 10:42:16 INFO (SyncWorker_3) [supervisor.docker.interface] Stopping addon_core_silabs_multiprotocol application[0m
[32m23-06-05 10:42:26 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_core_silabs_multiprotocol application[0m
[32m23-06-05 10:42:26 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-silabs-multiprotocol with version 2.0.0[0m
[31m23-06-05 10:43:01 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-30826' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=JobException()>[0m
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/mounts/manager.py", line 145, in reload
    await asyncio.wait(
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 408, in wait
    raise ValueError('Set of Tasks/Futures is empty.')
ValueError: Set of Tasks/Futures is empty.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 160, in wrapper
    raise JobException() from err
supervisor.exceptions.JobException
[31m23-06-05 10:43:01 ERROR (MainThread) [supervisor.jobs] Unhandled exception: Set of Tasks/Futures is empty.[0m
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/mounts/manager.py", line 145, in reload
    await asyncio.wait(
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 408, in wait
    raise ValueError('Set of Tasks/Futures is empty.')
ValueError: Set of Tasks/Futures is empty.
[33m23-06-05 10:43:26 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[33m23-06-05 10:44:47 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Silicon Labs Multiprotocol is unhealthy, restarting...[0m
[32m23-06-05 10:44:47 INFO (SyncWorker_5) [supervisor.docker.interface] Stopping addon_core_silabs_multiprotocol application[0m
[32m23-06-05 10:44:57 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_core_silabs_multiprotocol application[0m
[32m23-06-05 10:44:57 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-silabs-multiprotocol with version 2.0.0[0m
[33m23-06-05 10:47:18 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Silicon Labs Multiprotocol is unhealthy, restarting...[0m
[32m23-06-05 10:47:18 INFO (SyncWorker_0) [supervisor.docker.interface] Stopping addon_core_silabs_multiprotocol application[0m
[32m23-06-05 10:47:28 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_core_silabs_multiprotocol application[0m
[32m23-06-05 10:47:28 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-silabs-multiprotocol with version 2.0.0[0m
```

### Anything in the add-on logs that might be useful for us?

```txt
[10:47:30:548230] Info : fu_reset_chip = gpiochip0
[10:47:30:548231] Info : fu_spi_reset_pin = 23
[10:47:30:548232] Info : fu_wake_chip = gpiochip0
[10:47:30:548232] Info : fu_spi_wake_pin = 24
[10:47:30:548233] Info : fu_recovery_enabled = false
[10:47:30:548233] Info : fu_connect_to_bootloader = false
[10:47:30:548234] Info : fu_enter_bootloader = false
[10:47:30:548234] Info : fu_file = 
[10:47:30:548235] Info : restart_cpcd = false
[10:47:30:548235] Info : board_controller_ip_addr = 
[10:47:30:548236] Info : application_version_validation = false
[10:47:30:548237] Info : print_secondary_versions_and_exit = false
[10:47:30:548237] Info : use_noop_keep_alive = false
[10:47:30:548238] Info : reset_sequence = true
[10:47:30:548238] Info : uart_validation_test_option = 
[10:47:30:548239] Info : stats_interval = 0
[10:47:30:548239] Info : rlimit_nofile = 2000
[10:47:30:548240] Info : [31;1mENCRYPTION IS DISABLED [0m
[10:47:30:548241] Info : Starting daemon in normal mode
[10:47:30:559242] Info : Connecting to Secondary...
[10:47:32:559430] Info : Failed to connect, secondary seems unresponsive
[10:47:32:559445] Info : Connecting to Secondary...
[10:47:34:559564] Info : Failed to connect, secondary seems unresponsive
[10:47:34:559582] Info : Connecting to Secondary...
[10:47:36:559691] Info : Failed to connect, secondary seems unresponsive
[10:47:36:559708] Info : Connecting to Secondary...
[10:47:38:559808] Info : Failed to connect, secondary seems unresponsive
[10:47:38:559824] Info : Connecting to Secondary...
[10:47:40:560091] Info : Failed to connect, secondary seems unresponsive
[10:47:40:560107] Info : Connecting to Secondary...
[10:47:42:560239] Info : Failed to connect, secondary seems unresponsive
[10:47:42:560275] Info : Connecting to Secondary...
[10:47:44:560441] Info : Failed to connect, secondary seems unresponsive
[10:47:44:560457] Info : Connecting to Secondary...
[10:47:46:560665] Info : Failed to connect, secondary seems unresponsive
[10:47:46:560680] Info : Connecting to Secondary...
[10:47:48:561022] Info : Failed to connect, secondary seems unresponsive
[10:47:48:561037] Info : Connecting to Secondary...
[10:47:50:561405] Info : Failed to connect, secondary seems unresponsive
[10:47:50:561421] Info : Connecting to Secondary...
[10:47:52:561694] Info : Failed to connect, secondary seems unresponsive
[10:47:52:561710] Info : Connecting to Secondary...
[10:47:54:562053] Info : Failed to connect, secondary seems unresponsive
[10:47:54:562069] Info : Connecting to Secondary...
[10:47:56:562414] Info : Failed to connect, secondary seems unresponsive
[10:47:56:562430] Info : Connecting to Secondary...
[10:47:58:562658] Info : Failed to connect, secondary seems unresponsive
[10:47:58:562673] Info : Connecting to Secondary...
[10:48:00:563018] Info : Failed to connect, secondary seems unresponsive
[10:48:00:563034] Info : Connecting to Secondary...
[10:48:02:563288] Info : Failed to connect, secondary seems unresponsive
[10:48:02:563304] Info : Connecting to Secondary...
[10:48:04:563532] Info : Failed to connect, secondary seems unresponsive
[10:48:04:563548] Info : Connecting to Secondary...
[10:48:06:563700] Info : Failed to connect, secondary seems unresponsive
[10:48:06:563716] Info : Connecting to Secondary...
[10:48:08:563862] Info : Failed to connect, secondary seems unresponsive
[10:48:08:563878] Info : Connecting to Secondary...
[10:48:10:564028] Info : Failed to connect, secondary seems unresponsive
[10:48:10:564044] Info : Connecting to Secondary...
[10:48:12:564192] Info : Failed to connect, secondary seems unresponsive
[10:48:12:564208] Info : Connecting to Secondary...
[10:48:14:564331] Info : Failed to connect, secondary seems unresponsive
[10:48:14:564347] Info : Connecting to Secondary...
[10:48:16:564643] Info : Failed to connect, secondary seems unresponsive
[10:48:16:564659] Info : Connecting to Secondary...
[10:48:18:565004] Info : Failed to connect, secondary seems unresponsive
[10:48:18:565019] Info : Connecting to Secondary...
[10:48:20:565171] Info : Failed to connect, secondary seems unresponsive
[10:48:20:565187] Info : Connecting to Secondary...
[10:48:22:565331] Info : Failed to connect, secondary seems unresponsive
[10:48:22:565347] Info : Connecting to Secondary...
[10:48:24:565561] Info : Failed to connect, secondary seems unresponsive
[10:48:24:565577] Info : Connecting to Secondary...
[10:48:26:565771] Info : Failed to connect, secondary seems unresponsive
[10:48:26:565787] Info : Connecting to Secondary...
[10:48:28:566150] Info : Failed to connect, secondary seems unresponsive
[10:48:28:566165] Info : Connecting to Secondary...
[10:48:30:566309] Info : Failed to connect, secondary seems unresponsive
[10:48:30:566325] Info : Connecting to Secondary...
[10:48:32:566660] Info : Failed to connect, secondary seems unresponsive
[10:48:32:566675] Info : Connecting to Secondary...
[10:48:34:567019] Info : Failed to connect, secondary seems unresponsive
[10:48:34:567035] Info : Connecting to Secondary...
[10:48:36:567379] Info : Failed to connect, secondary seems unresponsive
[10:48:36:567395] Info : Connecting to Secondary...
[10:48:38:567526] Info : Failed to connect, secondary seems unresponsive
[10:48:38:567542] Info : Connecting to Secondary...
[10:48:40:567663] Info : Failed to connect, secondary seems unresponsive
[10:48:40:567677] Info : Connecting to Secondary...
[10:48:42:567873] Info : Failed to connect, secondary seems unresponsive
[10:48:42:567889] Info : Connecting to Secondary...
[10:48:44:568045] Info : Failed to connect, secondary seems unresponsive
[10:48:44:568061] Info : Connecting to Secondary...
[10:48:46:568195] Info : Failed to connect, secondary seems unresponsive
[10:48:46:568209] Info : Connecting to Secondary...
[10:48:48:568599] Info : Failed to connect, secondary seems unresponsive
[10:48:48:568615] Info : Connecting to Secondary...
[10:48:50:568923] Info : Failed to connect, secondary seems unresponsive
[10:48:50:568938] Info : Connecting to Secondary...
```

**Comment by keithdw1972** [comment]
and this is what a 'working' log from Silicon Labs Multiprotocol looks like:

[12:13:51:179723] Info : fu_connect_to_bootloader = false
[12:13:51:179724] Info : fu_enter_bootloader = false
[12:13:51:179725] Info : fu_file = 
[12:13:51:179725] Info : restart_cpcd = false
[12:13:51:179726] Info : board_controller_ip_addr = 
[12:13:51:179726] Info : application_version_validation = false
[12:13:51:179727] Info : print_secondary_versions_and_exit = false
[12:13:51:179727] Info : use_noop_keep_alive = false
[12:13:51:179728] Info : reset_sequence = true
[12:13:51:179728] Info : uart_validation_test_option = 
[12:13:51:179729] Info : stats_interval = 0
[12:13:51:179729] Info : rlimit_nofile = 2000
[12:13:51:179730] Info : [31;1mENCRYPTION IS DISABLED [0m
[12:13:51:179731] Info : Starting daemon in normal mode
[12:13:51:194400] Info : Connecting to Secondary...
[12:13:51:266821] Info : Connected to Secondary
[12:13:51:268482] Info : Secondary Protocol v3
[12:13:51:271963] Info : Secondary CPC v4.2.3
[12:13:51:273842] Info : Secondary bus speed is 460800
[12:13:51:275700] Info : Secondary APP vUNDEFINED
[12:13:51:275782] Info : Daemon startup was successful. Waiting for client connections
[12:13:52] INFO: [32mStarting zigbeed...[0m
[12:13:52] INFO: [32mSetup OTBR firewall...[0m
[12:13:53] INFO: [32mStarting otbr-agent...[0m
otbr-agent[301]: [NOTE]-AGENT---: Running 0.3.0
otbr-agent[301]: [NOTE]-AGENT---: Thread version: 1.3.0
otbr-agent[301]: [NOTE]-AGENT---: Thread interface: wpan0
otbr-agent[301]: [NOTE]-AGENT---: Radio URL: spinel+cpc://cpcd_0?iid=2
otbr-agent[301]: [NOTE]-ILS-----: Infra link selected: enp6s18
otbr-agent[301]: 49d.17:03:42.682 [C] Platform------: mCpcBusSpeed = 115200
[12:13:53:281192] Info : New client connection using library v4.2.2.0
[12:13:53:283269] Info : Opened connection socket for ep#12
[12:13:53:283682] Info : Endpoint socket #12: Client connected. 1 connections
[12:13:53:439899] Info : New client connection using library v4.2.2.0
[12:13:53:442093] Info : Endpoint socket #12: Client connected. 2 connections
otbr-agent[301]: 49d.17:03:44.717 [N] Platform------: RCP API Version: 6
otbr-agent[301]: 00:00:00.030 [N] BorderRouter--: No valid /48 BR ULA prefix found in settings, generating new one
otbr-agent[301]: 00:00:00.038 [N] BorderRouter--: BR ULA prefix: fd5f:fd73:1202::/48 (generated)
otbr-agent[301]: 00:00:00.038 [N] BorderRouter--: Local on-link prefix: fdde:ad00:beef:cafe::/64
otbr-agent[301]: 00:00:00.040 [N] BorderRouter--: Local on-link prefix: fdde:ad00:beef:cafe::/64
s6-rc: info: service otbr-agent successfully started
s6-rc: info: service otbr-agent-rest-discovery: starting
[12:13:55] INFO: [32mSuccessfully sent discovery information to Home Assistant.[0m
s6-rc: info: service otbr-agent-rest-discovery successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Listening on port 9999 for connection...
Accepting connection.
otbr-agent[301]: 00:00:58.700 [N] BorderRouter--: Local on-link prefix: fda5:99ff:2cb8:a316::/64
otbr-agent[301]: 00:00:58.726 [N] Mle-----------: Role disabled -> detached
otbr-agent[301]: 00:00:58.729 [N] Platform------: [netif] Changing interface state to up.
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::6c95:d8ff:fe38:a3fc/veth78e0eaf/27
otbr-agent[301]: 00:00:59.062 [N] Mle-----------: Attach attempt 1, AnyPartition reattaching with Active Dataset
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::6c95:d8ff:fe38:a3fc/veth78e0eaf/27
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::6c95:d8ff:fe38:a3fc/veth78e0eaf/27
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::fcdf:1dff:feec:b52a/veth7ab845c/29
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::6c95:d8ff:fe38:a3fc/veth78e0eaf/27
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::fcdf:1dff:feec:b52a/veth7ab845c/29
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::6c95:d8ff:fe38:a3fc/veth78e0eaf/27
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::fcdf:1dff:feec:b52a/veth7ab845c/29
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::6c95:d8ff:fe38:a3fc/veth78e0eaf/27
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::fcdf:1dff:feec:b52a/veth7ab845c/29
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::6c95:d8ff:fe38:a3fc/veth78e0eaf/27
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::fcdf:1dff:feec:b52a/veth7ab845c/29
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::fcdf:1dff:feec:b52a/veth7ab845c/29
Default: mDNS_Execute: SendResponses didn't send all its responses; will try again in one second
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::fcdf:1dff:feec:b52a/veth7ab845c/29
Default: mDNS_Execute: SendResponses didn't send all its responses; will try again in one second
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::fcdf:1dff:feec:b52a/veth7ab845c/29
Default: mDNS_Execute: SendResponses didn't send all its responses; will try again in one second
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::fcdf:1dff:feec:b52a/veth7ab845c/29
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::fcdf:1dff:feec:b52a/veth7ab845c/29
otbr-agent[301]: 00:01:05.562 [N] RouterTable---: Allocate router id 45
otbr-agent[301]: 00:01:05.562 [N] Mle-----------: RLOC16 fffe -> b400
otbr-agent[301]: 00:01:05.565 [N] Mle-----------: Role detached -> leader
otbr-agent[301]: 00:01:05.565 [N] Mle-----------: Leader partition id 0x65a74e38
Accepted connection 7.
Restarting
otbr-agent[301]: [NOTE]-BBA-----: BackboneAgent: Backbone Router becomes Primary!
[12:15:00:949115] Info : Endpoint socket #12: Client disconnected. 1 connections
[12:15:00:949147] Info : Client disconnected
[12:15:01:949514] Info : New client connection using library v4.2.2.0
[12:15:01:951466] Info : Endpoint socket #12: Client connected. 2 connections
Reusing socket from previous instance.
Socket connection has been closed, restarting...
Listening on port 9999 for connection...
Accepting connection.
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::ac13:8aff:fe77:9416/veth4d73150/31
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::ac13:8aff:fe77:9416/veth4d73150/31
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::ac13:8aff:fe77:9416/veth4d73150/31
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::ac13:8aff:fe77:9416/veth4d73150/31
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::ac13:8aff:fe77:9416/veth4d73150/31
Default: mDNSPlatformSendUDP got error 99 (Cannot assign requested address) sending packet to ff02::fb on interface fe80::ac13:8aff:fe77:9416/veth4d73150/31
Accepted connection 8.
Restarting
[12:15:18:379062] Info : Endpoint socket #12: Client disconnected. 1 connections
[12:15:18:379090] Info : Client disconnected
[12:15:19:380835] Info : New client connection using library v4.2.2.0
[12:15:19:383961] Info : Endpoint socket #12: Client connected. 2 connections
Reusing socket from previous instance.

**Comment by keithdw1972** [comment]
Except of course I now seem to have lost my Zigbee network...?!

**Comment by agners** [comment]
We've seen hangs on the SkyConnect firmware, but not as consistently. I also think that the recent versions really got stable, to a point where I've not seen new issues being reported lately. But not sure about the Sonoff stick.

@darkxst do you have thoughts?

**Comment by MattWestb** [comment]
Im running 3 addons with EFR32MG1P and all is stable as long USB connected devices is not having problems with  the USB interface (or UART if direct chip connected). 
Still one RCP firmware 4.2.1.0 but current add-on.

@kirovilya is you still running one older version then you testing the RCP or have you updated your test system ?
Its looks being one timing problems like ZHA was having before and  the host is resetting then its thinking it have lost communication with the RCP (Zigbeed not the OTBR part but one chip reset is restarting the RCP firmware with both).

**Comment by darkxst** [comment]
I've seen the USB connection to the ZBDongle-E lock up sometimes after a system (VM) reboot, however I dont think I have ever seen it just hang during normal operation like that. Its generally been very stable.

**Comment by agners** [comment]
From the "Home Assistant Supervisor" version it seems o be `ova`, so virtualization indeed.

@keithdw1972 what VM are you using?

**Comment by darkxst** [comment]
I've not been able to reproduce these USB lockups reliably, It will happen eventually if  I detach active dongle from the VM (without clean shutdown of connection), usually takes a few attempts to fail though. Makes me wonder if the USB connection is dropping out for some reason. 

Once they happen the only thing that will unfreeze it is the DTR/RTS reset sequence into bootloader and relaunch app.
https://github.com/NabuCasa/universal-silabs-flasher/blob/9e07800770f44e6cb39b0eaee51aa84cb9fc37d4/universal_silabs_flasher/flasher.py#L105
