### ISSUE TITLE
Matter Server still fails even after latest update

### ISSUE THREAD

**Issue by robertfgoodworth** [home-assistant/addons#3084]
### Describe the issue you are experiencing

Matter Server still fails even after latest update to 4.6.0, seems to get further than it did on previous version. Details below

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Matter Server

### What is the version of the add-on?

4.6.0

### Steps to reproduce the issue

1. After updating Matter server to v 4.6.0, go into addons and select Matter Server.
2. start the addon.
3. while starting review log in log screen
4. after a while the startup fails with errors.
...

## System Information

version | core-2023.5.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 6.1.29
arch | x86_64
timezone | Australia/Sydney
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | failed to load: timeout
GitHub Web | ok
GitHub API Calls Remaining | 4993
Installed Version | 1.32.1
Stage | running
Available Repositories | 1363
Downloaded Repositories | 68

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | October 14, 2023 at 11:00 AM
relayer_connected | true
relayer_region | ap-southeast-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | ap-southeast-1-1.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | failed to load: timeout
can_reach_cloud_auth | failed to load: timeout
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 146.9 GB
disk_used | 80.0 GB
healthy | true
supported | failed to load: Unsupported
board | ova
supervisor_api | ok
version_api | failed to load: timeout
installed_addons | chrony (2.6.0), Node-RED (14.2.2), phpMyAdmin (0.8.6), deCONZ (6.19.0), AppDaemon (0.13.0), InfluxDB (4.7.0), MariaDB (2.6.1), Log Viewer (0.15.1), Samba share (10.0.2), Advanced SSH & Web Terminal (15.0.2), Studio Code Server (5.6.1), Grocy (0.19.1), VLC (0.2.0), TasmoAdmin (0.24.4), Uptime Kuma (0.7.4), EMQX (0.2.10), Zigbee2MQTT (1.31.0-1), Whisper (0.2.0), Piper (0.1.3), Matter Server (4.6.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 40
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 29, 2023 at 9:04 PM
-- | --
current_recorder_run | June 4, 2023 at 8:49 AM
estimated_db_size | 1130.58 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | failed to load: timeout
-- | --

</details>

<details><summary>Xiaomi Miot Auto</summary>

error | failed to load: timeout
-- | --

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
no errors here, there all green
```

### Anything in the add-on logs that might be useful for us?

```txt
Matter Server startup log:
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
-----------------------------------------------------------
 Add-on: Matter Server
 Matter WebSocket Server for Home Assistant Matter support.
-----------------------------------------------------------
 Add-on version: 4.6.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.2  (amd64 / qemux86-64)
 Home Assistant Core: 2023.5.4
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service matter-server: starting
s6-rc: info: service matter-server successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[16:27:25] INFO: Starting Matter Server...
[16:27:26] INFO: Successfully send discovery information to Home Assistant.
2023-06-06 16:27:27 core-matter-server matter_server.server.stack[126] INFO Initializing CHIP/Matter Controller Stack...
[1686032847.672226][126:126] CHIP:CTL: Setting attestation nonce to random value
[1686032847.672374][126:126] CHIP:CTL: Setting CSR nonce to random value
[1686032847.695979][126:126] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_kvs
[1686032847.767373][126:126] CHIP:DL: writing settings to file (/tmp/chip_kvs-OKqm6I)
[1686032847.767577][126:126] CHIP:DL: renamed tmp file to file (/tmp/chip_kvs)
[1686032847.767771][126:126] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /data/chip_factory.ini
[1686032847.795474][126:126] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /data/chip_config.ini
[1686032847.819614][126:126] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /data/chip_counters.ini
[1686032847.847096][126:126] CHIP:DL: writing settings to file (/data/chip_counters.ini-QwMJFH)
[1686032847.847462][126:126] CHIP:DL: renamed tmp file to file (/data/chip_counters.ini)
[1686032847.847491][126:126] CHIP:DL: NVS set: chip-counters/reboot-count = 26 (0x1A)
[1686032847.848412][126:126] CHIP:DL: Got Ethernet interface: enp2s1
[1686032847.848966][126:126] CHIP:DL: Found the primary Ethernet interface:enp2s1
[1686032847.850516][126:126] CHIP:DL: Failed to get WiFi interface
[1686032847.850539][126:126] CHIP:DL: Failed to reset WiFi statistic counts
2023-06-06 16:27:27 core-matter-server PersistentStorage[126] WARNING Initializing persistent storage from file: /data/chip.json
2023-06-06 16:27:27 core-matter-server PersistentStorage[126] WARNING Loading configuration from /data/chip.json...
2023-06-06 16:27:27 core-matter-server chip.TS[126] INFO Last Known Good Time: 2023-06-02T10:24:24
2023-06-06 16:27:27 core-matter-server PersistentStorage[126] INFO SetSdkKey: g/gcc = b'\x90e\x00\x00'
2023-06-06 16:27:27 core-matter-server PersistentStorage[126] INFO Committing...
2023-06-06 16:27:27 core-matter-server PersistentStorage[126] INFO SetSdkKey: g/gdc = b'\x90e\x00\x00'
2023-06-06 16:27:27 core-matter-server PersistentStorage[126] INFO Committing...
2023-06-06 16:27:27 core-matter-server chip.ZCL[126] INFO Using ZAP configuration...
2023-06-06 16:27:27 core-matter-server chip.DL[126] ERROR MDNS failed to join multicast group on veth316d5ca for address type IPv4: src/inet/UDPEndPointImplSockets.cpp:764: Inet Error 0x00000110: Address not found
2023-06-06 16:27:27 core-matter-server chip.DL[126] ERROR MDNS failed to join multicast group on vethc2047f2 for address type IPv4: src/inet/UDPEndPointImplSockets.cpp:764: Inet Error 0x00000110: Address not found
2023-06-06 16:27:27 core-matter-server chip.DL[126] ERROR MDNS failed to join multicast group on veth802d5f7 for address type IPv4: src/inet/UDPEndPointImplSockets.cpp:764: Inet Error 0x00000110: Address not found
2023-06-06 16:27:27 core-matter-server chip.DL[126] ERROR MDNS failed to join multicast group on veth0188c63 for address type IPv4: src/inet/UDPEndPointImplSockets.cpp:764: Inet Error 0x00000110: Address not found
2023-06-06 16:27:27 core-matter-server chip.DL[126] ERROR MDNS failed to join multicast group on veth8100781 for address type IPv4: src/inet/UDPEndPointImplSockets.cpp:764: Inet Error 0x00000110: Address not found
2023-06-06 16:27:27 core-matter-server chip.DL[126] ERROR MDNS failed to join multicast group on veth6362909 for address type IPv4: src/inet/UDPEndPointImplSockets.cpp:764: Inet Error 0x00000110: Address not found
2023-06-06 16:27:27 core-matter-server chip.DL[126] ERROR MDNS failed to join multicast group on veth99a9154 for address type IPv4: src/inet/UDPEndPointImplSockets.cpp:764: Inet Error 0x00000110: Address not found
2023-06-06 16:27:27 core-matter-server chip.DL[126] ERROR MDNS failed to join multicast group on veth629be32 for address type IPv4: src/inet/UDPEndPointImplSockets.cpp:764: Inet Error 0x00000110: Address not found
2023-06-06 16:27:27 core-matter-server chip.DL[126] ERROR MDNS failed to join multicast group on veth8823062 for address type IPv4: src/inet/UDPEndPointImplSockets.cpp:764: Inet Error 0x00000110: Address not found
2023-06-06 16:27:27 core-matter-server chip.DL[126] ERROR MDNS failed to join multicast group on veth52d2380 for address type IPv4: src/inet/UDPEndPointImplSockets.cpp:764: Inet Error 0x00000110: Address not found
2023-06-06 16:27:27 core-matter-server chip.DL[126] ERROR MDNS failed to join multicast group on veth87a9347 for address type IPv4: src/inet/UDPEndPointImplSockets.cpp:764: Inet Error 0x00000110: Address not found
2023-06-06 16:27:27 core-matter-server chip.DL[126] ERROR MDNS failed to join multicast group on veth23251e9 for address type IPv4: src/inet/UDPEndPointImplSockets.cpp:764: Inet Error 0x00000110: Address not found
2023-06-06 16:27:27 core-matter-server chip.DL[126] ERROR MDNS failed to join multicast group on vethd4d76a5 for address type IPv4: src/inet/UDPEndPointImplSockets.cpp:764: Inet Error 0x00000110: Address not found
2023-06-06 16:27:27 core-matter-server chip.DL[126] ERROR MDNS failed to join multicast group on veth58b7a7f for address type IPv4: src/inet/UDPEndPointImplSockets.cpp:764: Inet Error 0x00000110: Address not found
2023-06-06 16:27:27 core-matter-server chip.DL[126] ERROR MDNS failed to join multicast group on vethb30715c for address type IPv4: src/inet/UDPEndPointImplSockets.cpp:764: Inet Error 0x00000110: Address not found
2023-06-06 16:27:27 core-matter-server chip.DL[126] ERROR MDNS failed to join multicast group on veth2af21ed for address type IPv4: src/inet/UDPEndPointImplSockets.cpp:764: Inet Error 0x00000110: Address not found
2023-06-06 16:27:27 core-matter-server chip.DL[126] ERROR MDNS failed to join multicast group on vethd0b200e for address type IPv4: src/inet/UDPEndPointImplSockets.cpp:764: Inet Error 0x00000110: Address not found
2023-06-06 16:27:27 core-matter-server chip.DL[126] ERROR MDNS failed to join multicast group on veth6f7daba for address type IPv4: src/inet/UDPEndPointImplSockets.cpp:764: Inet Error 0x00000110: Address not found
2023-06-06 16:27:27 core-matter-server chip.DL[126] ERROR MDNS failed to join multicast group on vethc0456b9 for address type IPv4: src/inet/UDPEndPointImplSockets.cpp:764: Inet Error 0x00000110: Address not found
2023-06-06 16:27:27 core-matter-server chip.DL[126] ERROR MDNS failed to join multicast group on veth2a60bd2 for address type IPv4: src/inet/UDPEndPointImplSockets.cpp:764: Inet Error 0x00000110: Address not found
2023-06-06 16:27:27 core-matter-server CertificateAuthorityManager[126] WARNING Loading certificate authorities from storage...
2023-06-06 16:27:27 core-matter-server CertificateAuthority[126] WARNING New CertificateAuthority at index 1
2023-06-06 16:27:27 core-matter-server CertificateAuthority[126] WARNING Loading fabric admins from storage...
2023-06-06 16:27:27 core-matter-server FabricAdmin[126] WARNING New FabricAdmin: FabricId: 0x0000000000000002, VendorId = 0x134B
2023-06-06 16:27:27 core-matter-server PersistentStorage[126] INFO SetReplKey: caList = {'1': [{'fabricId': 2, 'vendorId': 4939}]}
2023-06-06 16:27:27 core-matter-server PersistentStorage[126] INFO Committing...
2023-06-06 16:27:27 core-matter-server matter_server.server.stack[126] INFO CHIP Controller Stack initialized.
2023-06-06 16:27:27 core-matter-server matter_server.server.server[126] INFO Starting the Matter Server...
2023-06-06 16:27:27 core-matter-server matter_server.server.helpers.paa_certificates[126] INFO Fetching the latest PAA root certificates from DCL.
2023-06-06 16:27:47 core-matter-server matter_server.server.helpers.paa_certificates[126] INFO Fetched 89 PAA root certificates from DCL.
2023-06-06 16:27:47 core-matter-server matter_server.server.helpers.paa_certificates[126] INFO Fetching the latest PAA root certificates from Git.
2023-06-06 16:32:48 core-matter-server asyncio[126] ERROR Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:227> exception=TimeoutError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 237, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/server.py", line 94, in start
    await self.device_controller.initialize()
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 73, in initialize
    await fetch_certificates()
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/helpers/paa_certificates.py", line 153, in fetch_certificates
    fetch_count += await fetch_git_certificates()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/helpers/paa_certificates.py", line 126, in fetch_git_certificates
    async with http_session.get(f"{GIT_URL}/{cert}.pem") as response:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 467, in _request
    with timer:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError
```

### Additional information

noting to add

**Comment by agners** [comment]
This is most likely related to https://github.com/home-assistant-libs/python-matter-server/issues/284.

There are some debugging suggestion in [this comment](https://github.com/home-assistant-libs/python-matter-server/issues/284#issuecomment-1548037576), can you try them out?

**Comment by marcelveldt** [comment]
closing here. If there may still be issues, please open an issue report on the HA core repository where we track all Matter issues.

**Comment by DarthSonic** [comment]
I also see those errors in my log and I am not able to add any matter devices as they cannot validate the network connection on setup.

2023-07-14 10:28:49 core-matter-server chip.DL[126] ERROR MDNS failed to join multicast group on veth63e16b6 for address type IPv4: src/inet/UDPEndPointImplSockets.cpp:764: Inet Error 0x00000110: Address not found

**Comment by agners** [comment]
@DarthSonic this issue is not about the `ERROR MDNS failed to join multicast group`, but the Python stack trace after it. The `ERROR MDNS failed to join multicast group` should not be an issue, as this is more informational, it is complaining about the virtual interfaces used by the system (`veth..`), not the actual network interface.

> I also see those errors in my log and I am not able to add any matter devices as they cannot validate the network connection on setup.

Can you report a new issue at the [Core repository](https://github.com/home-assistant/core/), along with the exact steps you take, the device you are trying to connect, and details about your setup?
