### ISSUE TITLE
Commission of shared Aqara P2 from Apple Home Hub fails

### ISSUE THREAD

**Issue by mluecke09** [home-assistant/addons#3133]
### Describe the issue you are experiencing

Commission fails for a shared Aqara P2 sensor from Apple Home Hub. Sharing to Google Home or Homey (despite the fact that device type is not supported) is working. It also worked for another Aqara P2 with Matter server 4.8.2.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Matter Server

### What is the version of the add-on?

4.8.3

### Steps to reproduce the issue

1. Turn on Pairing mode for Device in Apple Home App & Copy Pairing code
2. Add new Matter device in HA with Setup code
3. Wait for Connecting to Accessory
4. Stops with message "Unable to Pair"

### System Health information

There are currently no repairs available

### Anything in the add-on logs that might be useful for us?

```txt
2023-07-14 09:27:48 core-matter-server matter_server.server.helpers.paa_certificates[126] INFO Fetching the latest PAA root certificates from DCL.
2023-07-14 09:27:48 core-matter-server matter_server.server.helpers.paa_certificates[126] INFO Fetched 0 PAA root certificates from DCL.
2023-07-14 09:27:48 core-matter-server matter_server.server.helpers.paa_certificates[126] INFO Fetching the latest PAA root certificates from Git.
2023-07-14 09:27:48 core-matter-server matter_server.server.helpers.paa_certificates[126] INFO Fetched 0 PAA root certificates from Git.
2023-07-14 09:27:48 core-matter-server chip.BLE[126] ERROR Failed to set discovery filters: GDBus.Error:org.bluez.Error.NotReady: Resource Not Ready
2023-07-14 09:27:48 core-matter-server chip.BLE[126] ERROR Failed to start discovery: GDBus.Error:org.bluez.Error.NotReady: Resource Not Ready
2023-07-14 09:27:48 core-matter-server chip.BLE[126] ERROR Failed to start BLE scan.
2023-07-14 09:27:48 core-matter-server chip.BLE[126] ERROR Failed to start a BLE can: src/platform/Linux/bluez/ChipDeviceScanner.cpp:136: CHIP Error 0x000000AC: Internal error
2023-07-14 09:27:48 core-matter-server chip.CTL[126] ERROR Commissioning discovery over BLE failed: src/platform/Linux/bluez/ChipDeviceScanner.cpp:136: CHIP Error 0x000000AC: Internal error
2023-07-14 09:27:48 core-matter-server chip.-[126] ERROR src/platform/Linux/bluez/ChipDeviceScanner.cpp:136: CHIP Error 0x000000AC: Internal error at src/controller/SetUpCodePairer.cpp:299
2023-07-14 09:28:18 core-matter-server chip.CTL[126] ERROR Discovery timed out
2023-07-14 09:28:18 core-matter-server chip.ZCL[126] ERROR Secure Pairing Failed
2023-07-14 09:28:18 core-matter-server matter_server.server.client_handler[126] ERROR [548287126672] Error handling message: CommandMessage(message_id='e91a1586420349feb267a3fec639e7d9', command='commission_with_code', args={'code': '15708026297'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/client_handler.py", line 188, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 174, in commission_with_code
    raise NodeCommissionFailed(
matter_server.common.errors.NodeCommissionFailed: Commission with code failed for node 10
2023-07-14 09:28:19 core-matter-server chip.DIS[126] ERROR Timeout waiting for mDNS resolution.
```

**Comment by mluecke09** [comment]
Resolved after reinstalling Matter Server Addon
