### ISSUE TITLE
Zwave-JS with Remotec ZRC-90 (BW8510) is not discovering the Manufacture or Model

### ISSUE THREAD

**Issue by nickolas1969** [home-assistant/addons#3136]
### Describe the issue you are experiencing

Just purchased a Remotec ZRC-90 (BW8510) and added to my Home Assistant (RPi Image) and added the blueprint for the ZRC-90. My Node added with the basics, but did not discover a Manufacture or Model, so the Blueprint is unable to detect any devices.

How can I help find out what went wrong?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

0.1.84

### Steps to reproduce the issue

1. Batteries in remote
2. Add Device in Z-Wave JS Add-on (currently 31 nodes) with Aotek gen 5 stick
3. After device is discovered, look at device list and Manufacture and Model are -
4. Notice in blueprint that it needs Remotec and BW8510.
...

## System Information

version | core-2023.7.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1337
Downloaded Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 116.5 GB
disk_used | 13.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Tautulli (3.2.7), Network UPS Tools (0.12.0), File editor (5.6.0), Terminal & SSH (9.7.0), Mosquitto broker (6.2.1), Samba share (10.0.2), Node-RED (14.3.0), Let's Encrypt (4.12.9), TasmoAdmin (0.24.4), ESPHome (2023.6.5), Advanced SSH & Web Terminal (15.0.3), Home Assistant Google Drive Backup (0.111.1), Home Panel (2.6.1), Z-Wave JS (0.1.84), HiSense Air Conditioners (0.3.14)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 2
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 6, 2023 at 1:38 AM
-- | --
current_recorder_run | July 5, 2023 at 6:48 PM
estimated_db_size | 189.74 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
Not that I can tell..

23-07-14 16:11:27 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 16:16:33 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
23-07-14 16:16:33 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 16:16:33 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 16:21:39 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
23-07-14 16:21:39 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 16:21:39 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 16:22:31 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-07-14 16:26:45 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
23-07-14 16:26:45 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 16:26:45 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 16:29:48 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 8:0 is not WSMsgType.TEXT
23-07-14 16:29:48 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 8:0 is not WSMsgType.TEXT
23-07-14 16:29:48 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
23-07-14 16:29:48 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 8:0 is not WSMsgType.TEXT
23-07-14 16:29:48 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
23-07-14 16:29:48 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
23-07-14 16:29:53 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
23-07-14 16:29:53 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
23-07-14 16:29:53 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
23-07-14 16:29:53 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
23-07-14 16:29:53 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
23-07-14 16:29:53 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
23-07-14 16:29:53 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
23-07-14 16:29:53 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
23-07-14 16:29:53 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
23-07-14 16:31:51 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
23-07-14 16:31:51 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 16:31:51 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 16:36:57 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
23-07-14 16:36:57 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 16:36:57 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 16:42:03 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
23-07-14 16:42:03 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 16:42:03 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 16:47:09 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
23-07-14 16:47:09 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 16:47:09 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 16:47:51 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
23-07-14 16:47:51 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
23-07-14 16:47:51 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DOCKER_CONFIG/ContextType.SYSTEM
23-07-14 16:47:51 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.MULTIPLE_DATA_DISKS/ContextType.SYSTEM
23-07-14 16:47:51 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
23-07-14 16:47:51 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.NO_CURRENT_BACKUP/ContextType.SYSTEM
23-07-14 16:47:51 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM
23-07-14 16:47:51 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
23-07-14 16:47:51 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
23-07-14 16:47:51 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
23-07-14 16:47:51 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
23-07-14 16:47:51 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-07-14 16:47:51 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
23-07-14 16:47:52 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-07-14 16:47:52 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
23-07-14 16:47:52 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-07-14 16:51:37 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-07-14 16:52:15 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
23-07-14 16:52:15 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 16:52:15 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 16:52:31 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-07-14 16:57:21 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
23-07-14 16:57:21 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 16:57:21 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 17:02:27 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
23-07-14 17:02:27 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 17:02:27 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 17:07:33 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
23-07-14 17:07:33 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 17:07:33 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 17:12:39 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
23-07-14 17:12:39 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 17:12:39 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 17:17:45 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
23-07-14 17:17:45 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 17:17:45 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 17:22:32 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-07-14 17:22:51 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
23-07-14 17:22:51 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 17:22:51 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 17:27:57 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
23-07-14 17:27:57 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 17:27:57 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 17:33:03 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
23-07-14 17:33:03 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
23-07-14 17:33:03 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
```

### Anything in the add-on logs that might be useful for us?

```txt
2023-07-14T22:34:04.445Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T22:34:05.446Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T22:34:06.448Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T22:34:07.450Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T22:34:08.441Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T22:34:09.443Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T22:34:10.446Z CNTRLR » [Node 036] Sending node back to sleep...
2023-07-14T22:34:10.471Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2023-07-14T22:34:10.476Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T22:34:10.595Z CNTRLR   [Node 036] The node is now asleep.
2023-07-14T22:43:28.441Z CNTRLR » [Node 028] Notification CC values may be stale, refreshing...
2023-07-14T22:43:28.444Z CNTRLR » [Node 028] querying notification status for Power Management...
2023-07-14T23:06:27.228Z CNTRLR   [Node 032] treating BasicCC::Set as a report
2023-07-14T23:06:41.732Z CNTRLR   [Node 032] treating BasicCC::Set as a report
2023-07-14T23:07:07.914Z CNTRLR   [Node 032] treating BasicCC::Set as a report
2023-07-14T23:07:20.838Z CNTRLR   [Node 032] treating BasicCC::Set as a report
2023-07-14T23:07:42.461Z CNTRLR   [Node 032] treating BasicCC::Set as a report
2023-07-14T23:07:55.382Z CNTRLR   [Node 032] treating BasicCC::Set as a report
2023-07-14T23:13:12.367Z CNTRLR   [Node 032] treating BasicCC::Set as a report
2023-07-14T23:13:25.304Z CNTRLR   [Node 032] treating BasicCC::Set as a report
2023-07-14T23:14:37.695Z CNTRLR   [Node 032] treating BasicCC::Set as a report
2023-07-14T23:14:50.619Z CNTRLR   [Node 032] treating BasicCC::Set as a report
Client disconnected
Code 1000: 
New client
2023-07-14T23:46:31.182Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:46:31.186Z CNTRLR   [Node 036] The node is now awake.
2023-07-14T23:46:31.209Z CNTRLR   [Node 036] Beginning interview - last completed stage: None
2023-07-14T23:46:31.210Z CNTRLR   [Node 036] new node, doing a full interview...
2023-07-14T23:46:31.212Z CNTRLR » [Node 036] querying protocol info...
2023-07-14T23:46:31.254Z CNTRLR   [Node 036] The node is now alive.
2023-07-14T23:46:31.304Z CNTRLR « [Node 036] received response for protocol info:
                                  basic device class:    Controller
                                  generic device class:  Remote Controller
                                  specific device class: Simple Remote Control
                                  node type:             Controller
                                  is always listening:   false
                                  is frequent listening: false
                                  can route messages:    false
                                  supports security:     false
                                  supports beaming:      true
                                  maximum data rate:     100000 kbps
                                  protocol version:      3
2023-07-14T23:46:31.305Z CNTRLR   [Node 036] The node is now awake.
2023-07-14T23:46:31.308Z CNTRLR   [Node 036] Interview stage completed: ProtocolInfo
2023-07-14T23:46:31.309Z CNTRLR » [Node 036] querying node info...
2023-07-14T23:46:31.381Z CNTRLR « [Node 036] node info received
                                  supported CCs:
2023-07-14T23:46:31.382Z CNTRLR « [Node 036] node info received
                                  supported CCs:
2023-07-14T23:46:31.383Z CNTRLR   [Node 036] Interview stage completed: NodeInfo
2023-07-14T23:46:31.385Z CNTRLR   [Node 036] Interviewing Basic...
2023-07-14T23:46:31.386Z CNTRLR » [Node 036] querying Basic CC state...
2023-07-14T23:46:32.469Z CNTRLR   [Node 036] Timed out while waiting for a response from the node (ZW0201)
2023-07-14T23:46:32.470Z CNTRLR   [Node 036] No response to Basic Get command, assuming the node does not suppor
                                  t Basic CC...
2023-07-14T23:46:32.473Z CNTRLR   [Node 036] Interview stage completed: CommandClasses
2023-07-14T23:46:32.475Z CNTRLR   [Node 036] Interview stage completed: OverwriteConfig
2023-07-14T23:46:32.476Z CNTRLR   [Node 036] Interview completed
2023-07-14T23:46:32.477Z CNTRLR   [Node 036] The node is ready to be used
2023-07-14T23:46:34.472Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:46:35.474Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:46:36.472Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:46:37.464Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:46:38.475Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:46:39.477Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:46:40.479Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:46:41.480Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:46:44.094Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:46:45.870Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:46:46.877Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:46:47.881Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:46:48.883Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:46:49.869Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:46:50.880Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:46:51.874Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:46:52.886Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:46:53.884Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:46:54.884Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:46:55.888Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:46:56.878Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:46:57.893Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:46:58.891Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:46:59.893Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:47:00.895Z CNTRLR « [Node 036] received wakeup notification
2023-07-14T23:47:01.893Z CNTRLR « [Node 036] received wakeup notification
2023-07-15T00:03:58.326Z CNTRLR « [Node 015] received wakeup notification
2023-07-15T00:03:58.328Z CNTRLR   [Node 015] The node is now awake.
2023-07-15T00:03:59.335Z CNTRLR » [Node 015] Sending node back to sleep...
2023-07-15T00:03:59.370Z CNTRLR   [Node 015] The node is now asleep.
2023-07-15T00:32:29.670Z CNTRLR   [Node 035] Timed out while waiting for a response from the node (ZW0201)
Z-Wave error ZWaveError: Cannot check for firmware updates for node 35: Failed to query firmware version from the node! (ZW0260)
    at ZWaveController.getAvailableFirmwareUpdates (/usr/src/node_modules/zwave-js/src/lib/controller/Controller.ts:5815:10)
    at Function.handle (/usr/src/node_modules/@zwave-js/server/dist/lib/controller/message_handler.js:205:30)
    at Client.receiveMessage (/usr/src/node_modules/@zwave-js/server/dist/lib/server.js:106:62) {
  code: 260,
  context: undefined,
  transactionSource: undefined
}
```

**Comment by nickolas1969** [comment]
I should say that when I enable the successfull recieved entity it does increment each time I press a button, so something is happening.

**Comment by nickolas1969** [comment]
(sigh) Ok, removal and rediscover worked, then 6th time... Blueprint is functional now, and I have 4 lights under control.
