### ISSUE TITLE
Piper doesn't start - Service exited with code 1 (by signal 0)

### ISSUE THREAD

**Issue by katsaplias** [home-assistant/addons#3163]
### Describe the issue you are experiencing

Piper would not start when I choose the "el-gr-rapunzelina-low" voice model from the addon configuration drop-down menu, even though the rest voice models seem to work without any issues

also, when I search to the [https://huggingface.co/rhasspy/piper-voices/tree/main/el/el_GR/rapunzelina/low](url) voices repository I can see the requested voice model

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Piper

### What is the version of the add-on?

1.2.0

### Steps to reproduce the issue

1. install addon
2. configure addon with "el-gr-rapunzelina-low" voice 
3. start the addon

## System Information

version | core-2023.8.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.34
arch | x86_64
timezone | Europe/Athens
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4244
Installed Version | 1.32.1
Stage | running
Available Repositories | 1280
Downloaded Repositories | 59

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 219.4 GB
disk_used | 85.7 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.2), DSS VoIP Notifier (4.0.0), Mosquitto broker (6.2.1), Terminal & SSH (9.7.1), Hyperion.NG (2.0.15), DahuaVTO2MQTT (1.0.14), Double Take (1.13.1), Cloudflared (4.2.2), Asterisk (4.1.1), ESPHome (2023.7.1), File editor (5.6.0), Exadel CompreFace (1.1.0), Frigate (0.12.1), Traccar (0.20.0), MariaDB (2.6.1), Frigate Proxy (1.3), Whisper (1.0.0), Piper (1.2.0)

</details>

<details><summary>LedFx</summary>

version | 3.0.0
-- | --
10.251.107.79:8888 () | unreachable

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 40
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 4, 2023 at 10:33
-- | --
current_recorder_run | August 3, 2023 at 11:09
estimated_db_size | 1610.45 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Sonoff</summary>

version | 3.5.2 (2ad1cd7)
-- | --
cloud_online | 0 / 1
local_online | 0 / 0

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
23-08-03 11:07:55 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/AlexxIT/hassio-addons repository
23-08-03 11:07:55 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/synesthesiam/hassio-addons repository
23-08-03 11:07:55 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/bradsjm/hassio-addons repository
23-08-03 11:07:55 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sdesalve/hassio-addons repository
23-08-03 11:07:55 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/TECH7Fox/Asterisk-add-on repository
23-08-03 11:07:55 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/OPHoperHPO/hassio-addons repository
23-08-03 11:07:55 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/Poeschl/Hassio-Addons repository
23-08-03 11:07:55 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/brenner-tobias/ha-addons repository
23-08-03 11:07:55 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/pssc/ha-addon-lms/ repository
23-08-03 11:07:55 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/elad-bar/Hassio-addons repository
23-08-03 11:07:55 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/jakowenko/double-take-hassio-addons repository
23-08-03 11:07:55 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-08-03 11:07:55 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-08-03 11:07:55 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository-beta repository
23-08-03 11:07:55 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-08-03 11:07:55 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository-edge repository
23-08-03 11:07:56 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/rhasspy/hassio-addons repository
23-08-03 11:08:01 WARNING (SyncWorker_6) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate (Full Access) Beta (0.12.0)
23-08-03 11:08:03 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 185, in block_bad_requests
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 201, in system_validation
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 268, in token_validation
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 280, in core_proxy
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/utils.py", line 62, in wrap_api
    answer = await method(api, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/store.py", line 178, in store_info
    ATTR_ADDONS: [
                 ^
  File "/usr/src/supervisor/supervisor/api/store.py", line 179, in <listcomp>
    self._generate_addon_information(self.sys_addons.store[addon])
  File "/usr/src/supervisor/supervisor/api/store.py", line 114, in _generate_addon_information
    ATTR_ADVANCED: addon.advanced,
                   ^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/addons/model.py", line 227, in advanced
    return self.data[ATTR_ADVANCED]
           ^^^^^^^^^
  File "/usr/src/supervisor/supervisor/store/addon.py", line 19, in data
    return self.sys_store.data.addons[self.slug]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'df843657_tailscale'
23-08-03 11:08:05 WARNING (SyncWorker_0) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate (Full Access) Beta (0.12.0)
23-08-03 11:08:06 INFO (MainThread) [supervisor.store] Loading add-ons from store: 223 all - 0 new - 0 remove
23-08-03 11:08:06 INFO (MainThread) [supervisor.store] Loading add-ons from store: 223 all - 0 new - 0 remove
23-08-03 11:08:40 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon Piper to start, took more then 120 seconds
23-08-03 11:08:49 INFO (SyncWorker_3) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/generic-x86-64-homeassistant
23-08-03 11:09:16 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
23-08-03 11:09:23 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
23-08-03 11:09:23 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-08-03 11:09:25 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-08-03 11:09:25 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/rhasspy/hassio-addons repository
23-08-03 11:09:25 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/blakeblackshear/frigate-hass-addons repository
23-08-03 11:09:25 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/AlexxIT/hassio-addons repository
23-08-03 11:09:25 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/synesthesiam/hassio-addons repository
23-08-03 11:09:25 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/bradsjm/hassio-addons repository
23-08-03 11:09:25 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sdesalve/hassio-addons repository
23-08-03 11:09:25 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/TECH7Fox/Asterisk-add-on repository
23-08-03 11:09:25 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/OPHoperHPO/hassio-addons repository
23-08-03 11:09:25 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/Poeschl/Hassio-Addons repository
23-08-03 11:09:25 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/brenner-tobias/ha-addons repository
23-08-03 11:09:25 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/pssc/ha-addon-lms/ repository
23-08-03 11:09:25 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/elad-bar/Hassio-addons repository
23-08-03 11:09:25 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/jakowenko/double-take-hassio-addons repository
23-08-03 11:09:25 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-08-03 11:09:25 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-08-03 11:09:25 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository-beta repository
23-08-03 11:09:25 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-08-03 11:09:25 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository-edge repository
23-08-03 11:09:27 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-08-03 11:09:31 WARNING (SyncWorker_3) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate (Full Access) Beta (0.12.0)
23-08-03 11:09:35 WARNING (SyncWorker_4) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate (Full Access) Beta (0.12.0)
23-08-03 11:09:35 INFO (MainThread) [supervisor.store] Loading add-ons from store: 223 all - 0 new - 0 remove
23-08-03 11:09:35 INFO (MainThread) [supervisor.store] Loading add-ons from store: 223 all - 0 new - 0 remove
23-08-03 11:09:42 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
23-08-03 11:10:03 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
23-08-03 11:14:49 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
23-08-03 11:15:19 INFO (MainThread) [supervisor.host.info] Updating local host information
23-08-03 11:15:20 INFO (MainThread) [supervisor.host.services] Updating service information
23-08-03 11:15:20 INFO (MainThread) [supervisor.host.network] Updating local network information
23-08-03 11:15:20 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
23-08-03 11:15:20 INFO (MainThread) [supervisor.host.manager] Host information reload completed
```

### Anything in the add-on logs that might be useful for us?

```txt
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/wyoming_piper/__main__.py", line 148, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/wyoming_piper/__main__.py", line 116, in main
    await process_manager.get_process()
  File "/usr/local/lib/python3.9/dist-packages/wyoming_piper/process.py", line 114, in get_process
    ensure_voice_exists(
  File "/usr/local/lib/python3.9/dist-packages/wyoming_piper/download.py", line 37, in ensure_voice_exists
    raise VoiceNotFoundError(name)
wyoming_piper.download.VoiceNotFoundError: el-gr-rapunzelina-low
[11:10:14] INFO: Service exited with code 1 (by signal 0)
```

**Comment by frankidem** [comment]
I have the same issue

**Comment by Vitani** [comment]
Try stopping the add-on in dev tools -> services

```
service: hassio.addon_stop
data:
  addon: core_piper
```

and then going to the add-on config, changing the voice, saving, then starting the add-on again. If that solves the issuer you can then change the voice back to the original value and restarting the add-on.

**Comment by jp3dro** [comment]
I am having the same issue. Switching to a more recent voice (released like 1-2 weeks ago) seems to crash the add-on and it won't start.

**Comment by ThePeePs** [comment]
I am also having the same issue. I've tried with a few of the en-us voices, forcing a restart every time. error is always the same:
```s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service piper: starting
s6-rc: info: service piper successfully started
s6-rc: info: service discovery: starting
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/__main__.py", line 193, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/__main__.py", line 131, in main
    custom_name = custom_config["dataset"]
                  ~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'dataset'
[13:37:16] INFO: Service exited with code 1 (by signal 0)
```

Here is my config for Piper:

```yaml
voice: en-us-ryan-high
speaker: 0
length_scale: 1
noise_scale: 0.667
noise_w: 0.333
max_piper_procs: 1
debug_logging: false
update_voices: true
```

**Comment by ThePeePs** [comment]
> I am also having the same issue. I've tried with a few of the en-us voices, forcing a restart every time. error is always the same:
> 
> ```
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service legacy-cont-init: starting
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service piper: starting
> s6-rc: info: service piper successfully started
> s6-rc: info: service discovery: starting
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/__main__.py", line 193, in <module>
>     asyncio.run(main())
>   File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/__main__.py", line 131, in main
>     custom_name = custom_config["dataset"]
>                   ~~~~~~~~~~~~~^^^^^^^^^^^
> KeyError: 'dataset'
> [13:37:16] INFO: Service exited with code 1 (by signal 0)
> ```
> 
> Here is my config for Piper:
> 
> ```yaml
> voice: en-us-ryan-high
> speaker: 0
> length_scale: 1
> noise_scale: 0.667
> noise_w: 0.333
> max_piper_procs: 1
> debug_logging: false
> update_voices: true
> ```
> 
> I have Piper version 1.3.2 currently installed, on HA 2023.8.4

I was able to fix mine by re-installing Piper

**Comment by codysaylor** [comment]
I'm also getting these errors on HA 2023.9.3 and Piper 1.3.2. No luck restarting / reinstalling / changing voices.

**Comment by synesthesiam** [comment]
Please update to add-on version 1.4.0 and try again

**Comment by codysaylor** [comment]
> Please update to add-on version 1.4.0 and try again

Updating to 1.4.0 fixed the issue. Thank you!

**Comment by synesthesiam** [comment]
@ludeeus This issue can be closed as completed, thanks
