### ISSUE TITLE
Matter server reports multiple errors

### ISSUE THREAD

**Issue by pguich** [home-assistant/addons#3180]
### Describe the issue you are experiencing

I’ve been trying to add an aquara door and window sensor P2 via matter integration. It worked once, but then I tried to add eve door and window sensors, and since then it’s impossible to add any matter devices. 

I’m pretty sure I screwed something up when trying to add 4 Eve Door sensors the day before, and the day after none of the Matter Devices worked anymore. 

I uninstalled the Matter server, I restarted and rebooted home assistant multiple times, removed the matter server add-on and re-installed it. 
i did a partial back-up restore of the matter server and silicon labs multi protocol add ons. 

Home assistant runs on a raspberry pi 4, and I use the skyconnect usb dongle. 

AnY help would be greatly appreciated. 

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Matter Server

### What is the version of the add-on?

4.9.0

### Steps to reproduce the issue

1. Add Integration
2. Add Matter device
3. Scan Matter code
4. Click “add to home assistant”
5. Wait… (connecting to Accessory)
6. Error: Unable to Add Accessory - you may need to restart Your accessory before you can add it to your home
7. Factory reset the device (multiple times)
8. Tried it the accessory can be added to Apple Home - worked on the first try
9. Tried to turn on pairing mode in Apple Home, copied set up code, and tried to add it to Home assistant again.
10. Same error. 
...

## System Information

version | core-2023.8.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Zurich
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1332
Downloaded Repositories | 23
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 11 August 2024 at 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-12.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 916.2 GB
disk_used | 10.5 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | AppDaemon (0.13.4), Dropbox Sync (1.3.0), Home Assistant Google Drive Backup (0.111.1), Mosquitto broker (6.2.1), Node-RED (14.4.5), Samba share (10.0.2), Silicon Labs Multiprotocol (2.3.1), Studio Code Server (5.10.0), Terminal & SSH (9.7.1), HassOS I2C Configurator (0.13a), ArgonOne Active Cooling (30a), Matter Server (4.9.0)

</details>

<details><summary>Husqvarna Automower</summary>

can_reach_server | ok
-- | --

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 13
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 9 August 2023 at 13:38
-- | --
current_recorder_run | 17 August 2023 at 19:23
estimated_db_size | 691.72 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.config_entries
Source: config_entries.py:1250 
First occurred: 20:55:49 (1 occurrences) 
Last logged: 20:55:49

Config entry 'Matter' for matter integration not ready yet: Failed to connect to matter server; Retrying in background
```

### Anything in the add-on logs that might be useful for us?

```txt
2023-08-17 20:56:40 core-matter-server chip.DIS[126] ERROR Timeout waiting for mDNS resolution.
2023-08-17 20:56:54 core-matter-server chip.DIS[126] ERROR OperationalSessionSetup[1:0000000000000001]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2023-08-17 20:57:25 core-matter-server chip.DIS[126] ERROR Timeout waiting for mDNS resolution.
2023-08-17 20:57:34 core-matter-server matter_server.server.helpers.paa_certificates[126] INFO Fetching the latest PAA root certificates from DCL.
2023-08-17 20:57:35 core-matter-server matter_server.server.helpers.paa_certificates[126] INFO Fetched 0 PAA root certificates from DCL.
2023-08-17 20:57:35 core-matter-server matter_server.server.helpers.paa_certificates[126] INFO Fetching the latest PAA root certificates from Git.
2023-08-17 20:57:35 core-matter-server matter_server.server.helpers.paa_certificates[126] INFO Fetched 0 PAA root certificates from Git.
2023-08-17 20:57:35 core-matter-server chip.DL[126] ERROR Long dispatch time: 130 ms, for event type 2
2023-08-17 20:57:36 core-matter-server chip.BLE[126] ERROR BleConnectionDelegate::CancelConnection is not implemented.
2023-08-17 20:57:39 core-matter-server chip.DIS[126] ERROR OperationalSessionSetup[1:0000000000000001]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2023-08-17 20:57:39 core-matter-server matter_server.server.client_handler[126] ERROR [547661283408] Error handling message: CommandMessage(message_id='9a6b471020f848cf9a8476c1f6fe42d3', command='commission_with_code', args={'code': '16181219734'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/client_handler.py", line 188, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 171, in commission_with_code
    raise NodeCommissionFailed(
matter_server.common.errors.NodeCommissionFailed: Commission with code failed for node 6
2023-08-17 20:57:44 core-matter-server chip.EM[126] ERROR Failed to Send CHIP MessageCounter:211065266 on exchange 59788i sendCount: 4 max retries: 4
2023-08-17 20:57:45 core-matter-server chip.BLE[126] ERROR BLE scan error: src/platform/Linux/bluez/ChipDeviceScanner.cpp:154: CHIP Error 0x00000032: Timeout
2023-08-17 20:57:45 core-matter-server chip.DL[126] ERROR FAIL: NULL service in BluezConnectionInit
```

### Additional information

from the Matter Server Log (this keeps repeating over and over and over:

2023-08-17 21:29:10 core-matter-server matter_server.server.device_controller[126] WARNING Unable to subscribe to Node 1 as it is unavailable, will retry later in the background.
2023-08-17 21:29:36 core-matter-server chip.DL[126] ERROR FAIL: NULL service in BluezConnectionInit
2023-08-17 21:30:33 core-matter-server chip.DL[126] ERROR FAIL: NULL service in BluezConnectionInit
2023-08-17 21:31:30 core-matter-server chip.DL[126] ERROR FAIL: NULL service in BluezConnectionInit
2023-08-17 21:31:41 core-matter-server chip.DIS[126] ERROR Timeout waiting for mDNS resolution.
2023-08-17 21:31:55 core-matter-server chip.DIS[126] ERROR OperationalSessionSetup[1:0000000000000001]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2023-08-17 21:32:26 core-matter-server chip.DIS[126] ERROR Timeout waiting for mDNS resolution.
2023-08-17 21:32:27 core-matter-server chip.DL[126] ERROR FAIL: NULL service in BluezConnectionInit
2023-08-17 21:32:40 core-matter-server chip.DIS[126] ERROR OperationalSessionSetup[1:0000000000000001]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
2023-08-17 21:33:11 core-matter-server chip.DIS[126] ERROR Timeout waiting for mDNS resolution.

**Comment by agners** [comment]
It seems that after onboarding, the device can't be found on the network:
```
2023-08-17 21:32:40 core-matter-server chip.DIS[126] ERROR OperationalSessionSetup[1:0000000000000001]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:114: CHIP Error 0x00000032: Timeout
```

The Eve Door sensors need the latest firmware. From what I understand the only way to update those currently is through the Apple Ecosystem (using Apple BR and using the iOS Home app). Do you know which firmware version your Eve devices have?

To be sure this is related to the Eve devices, I recommend uninstalling both add-ons and removing the Matter integration. Than reinstall/readd things and start from scratch (without restoring from backup).

Also, make sure to use an extension cable. I'd also try to use a longer/different extension cable, just to make sure the SkyConnect is not suffering from interference. Especially since you seem to be using USB 3.0 devices on your Raspberry Pi too.

**Comment by ArthurGuy** [comment]
I am experiencing what I believe is the same error but I am using a Meross device.
It fails when I try and commission the device directly through HA or adopt a device configured through Google Home

**Comment by a-bianucci** [comment]
> I am experiencing what I believe is the same error but I am using a Meross device. It fails when I try and commission the device directly through HA or adopt a device configured through Google Home

I probably have the same Meross device and am having an issue with 1 of 2.   They fell off the network and required readding.  Initially both added, however after renaming the one it fell off and trying to repair doesn't work now.

**Comment by ArthurGuy** [comment]
I resolved my issue by reinstalling the matter server. Once this was done everything started working as expected.
