### ISSUE TITLE
OTBR - Firmware Version Mismatch reported in Logs

### ISSUE THREAD

**Issue by ntwb** [home-assistant/addons#3195]
### Describe the issue you are experiencing

Logs for the openthread border router add on report mismatched firmware

Hardware: Raspberry Pi using HAOS
Thread Hardware: SkyConnect
SkyConnect Firmware: “Thread” firmware only (.i.e Not ZigBee, Not Multi-protocol)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

OpenThread Border Router

### What is the version of the add-on?

2.3.2

### Steps to reproduce the issue

1. Install the OpenThread Border Router AddOn
2. Flash a SkyConnect with the “Thread” firmware via web flasher https://skyconnect.home-assistant.io/firmware-update/
3. Add the OTBR

### System Health information

“There are currently no repairs available”

### Anything in the Supervisor logs that might be useful for us?

As a matter of fact, yes:

```txt

23-08-28 10:13:56 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 185, in block_bad_requests
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 201, in system_validation
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 268, in token_validation
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 280, in core_proxy
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/utils.py", line 102, in wrap_api
    msg_data = await method(api, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/store.py", line 261, in addons_addon_documentation
    if not addon.with_documentation:
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/addons/model.py", line 504, in with_documentation
    return self.path_documentation.exists()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/addons/model.py", line 569, in path_documentation
    return Path(self.path_location, "DOCS.md")
                ^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/addons/model.py", line 549, in path_location
    return Path(self.data[ATTR_LOCATON])
                ^^^^^^^^^
  File "/usr/src/supervisor/supervisor/store/addon.py", line 19, in data
    return self.sys_store.data.addons[self.slug]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'core_openthread_border_router'
```

### Anything in the add-on logs that might be useful for us?

Yes, the full logs are attached below, the key log entries are listed first here though:

Summary

```txt

2023-08-26 19:20:53 hass-home universal_silabs_flasher.flash[154] INFO Firmware version 'SL-OPENTHREAD/2.3.1.0_GitHub-e6df00dd6' (2.3.1.0) does not match expected version 'SL-OPENTHREAD/2.2.2.0_GitHub-91fa1f455' (2.2.2.0)

```

Full Log:
```
[19:20:46] INFO: Web UI and REST API port are exposed, starting otbr-web.
s6-rc: info: service mdns: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service mdns successfully started
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service banner: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
[19:20:46] INFO: Starting mDNS Responder...
Default: mDNSResponder (Engineering Build) (Aug 24 2023 10:11:29) starting
-----------------------------------------------------------
 Add-on: OpenThread Border Router
 OpenThread Border Router add-on
-----------------------------------------------------------
 Add-on version: 2.3.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.8.4
 Home Assistant Supervisor: 2023.08.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service universal-silabs-flasher: starting
[19:20:49] INFO: Checking /dev/ttyUSB0 identifying SkyConnect v1.0 from Nabu Casa.
[19:20:49] INFO: Starting universal-silabs-flasher with /dev/ttyUSB0
2023-08-26 19:20:51 hass-home universal_silabs_flasher.flash[154] INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version='4.3.1', ezsp_version=None, ot_rcp_version='SL-OPENTHREAD/2.3.1.0_GitHub-e6df00dd6' (2.3.1.0), fw_type=<FirmwareImageType.OT_RCP: 'ot-rcp'>, baudrate=460800)
2023-08-26 19:20:51 hass-home universal_silabs_flasher.flasher[154] INFO Probing ApplicationType.GECKO_BOOTLOADER at 115200 baud
2023-08-26 19:20:53 hass-home universal_silabs_flasher.flasher[154] INFO Probing ApplicationType.SPINEL at 460800 baud
2023-08-26 19:20:53 hass-home universal_silabs_flasher.flasher[154] INFO Detected ApplicationType.SPINEL, version 'SL-OPENTHREAD/2.2.2.0_GitHub-91fa1f455' (2.2.2.0) at 460800 baudrate (bootloader baudrate None)
2023-08-26 19:20:53 hass-home universal_silabs_flasher.flash[154] INFO Firmware version 'SL-OPENTHREAD/2.3.1.0_GitHub-e6df00dd6' (2.3.1.0) does not match expected version 'SL-OPENTHREAD/2.2.2.0_GitHub-91fa1f455' (2.2.2.0)
2023-08-26 19:20:53 hass-home universal_silabs_flasher.flasher[154] INFO Probing ApplicationType.GECKO_BOOTLOADER at 115200 baud
2023-08-26 19:20:53 hass-home universal_silabs_flasher.flasher[154] INFO Detected bootloader version '2.1.1'
2023-08-26 19:20:53 hass-home universal_silabs_flasher.flasher[154] INFO Detected ApplicationType.GECKO_BOOTLOADER, version '2.1.1' at 115200 baudrate (bootloader baudrate 115200)
NabuCasa_SkyConnect_OpenThread_RCP_v2.3.1.0_ot-rcp_hw_460800.gbl
s6-rc: info: service universal-silabs-flasher successfully started
s6-rc: info: service otbr-agent: starting
[19:21:17] INFO: Setup OTBR firewall...
[19:21:17] INFO: Starting otbr-agent...
otbr-agent[186]: [NOTE]-AGENT---: Running 0.3.0-9e50efa-dirty
otbr-agent[186]: [NOTE]-AGENT---: Thread version: 1.3.0
otbr-agent[186]: [NOTE]-AGENT---: Thread interface: wpan0
otbr-agent[186]: [NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyUSB0?uart-baudrate=460800&uart-flow-control
otbr-agent[186]: [NOTE]-ILS-----: Infra link selected: eth0
otbr-agent[186]: 00:00:00.037 [N] RoutingManager: No valid /48 BR ULA prefix found in settings, generating new one
otbr-agent[186]: 00:00:00.042 [N] RoutingManager: BR ULA prefix: fd89:ce8b:bf64::/48 (generated)
otbr-agent[186]: 00:00:00.042 [N] RoutingManager: Local on-link prefix: fdde:ad00:beef:cafe::/64
s6-rc: info: service otbr-agent successfully started
s6-rc: info: service otbr-agent-rest-discovery: starting
s6-rc: info: service otbr-web: starting
s6-rc: info: service otbr-web successfully started
[19:21:18] INFO: Starting otbr-web...
otbr-web[268]: [INFO]-WEB-----: Running 0.3.0-9e50efa-dirty
otbr-web[268]: [INFO]-WEB-----: Border router web started on wpan0
otbr-agent[186]: 00:00:00.836 [N] RoutingManager: Local on-link prefix: fd2f:190e:492e:f38a::/64
otbr-agent[186]: 00:00:00.861 [N] Mle-----------: Role disabled -> detached
otbr-agent[186]: 00:00:00.864 [N] Platform------: [netif] Changing interface state to up.
otbr-agent[186]: 00:00:01.042 [N] Mle-----------: Attach attempt 1, AnyPartition reattaching with Active Dataset
[19:21:18] INFO: Successfully sent discovery information to Home Assistant.
s6-rc: info: service otbr-agent-rest-discovery successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
otbr-agent[186]: 00:00:07.543 [N] RouterTable---: Allocate router id 36
otbr-agent[186]: 00:00:07.544 [N] Mle-----------: RLOC16 fffe -> 9000
otbr-agent[186]: 00:00:07.548 [N] Mle-----------: Role detached -> leader
otbr-agent[186]: 00:00:07.549 [N] Mle-----------: Partition ID 0x1e0826fb
otbr-agent[186]: [NOTE]-BBA-----: BackboneAgent: Backbone Router becomes Primary!
```

**Comment by agners** [comment]
This is the expected behavior, you see that the add-on is installing the newer firmware:

> NabuCasa_SkyConnect_OpenThread_RCP_v2.3.1.0_ot-rcp_hw_460800.gbl

On next restart, you should not see the information anymore.

**Comment by ntwb** [comment]
Thanks verified, firmware does now appear to be the latest.

```
2023-09-03 21:26:42 hass-home universal_silabs_flasher.flash[154] INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version='4.3.1', ezsp_version=None, ot_rcp_version='SL-OPENTHREAD/2.3.1.0_GitHub-e6df00dd6' (2.3.1.0), fw_type=<FirmwareImageType.OT_RCP: 'ot-rcp'>, baudrate=460800)
2023-09-03 21:26:42 hass-home universal_silabs_flasher.flasher[154] INFO Probing ApplicationType.GECKO_BOOTLOADER at 115200 baud
2023-09-03 21:26:44 hass-home universal_silabs_flasher.flasher[154] INFO Probing ApplicationType.SPINEL at 460800 baud
2023-09-03 21:26:46 hass-home universal_silabs_flasher.flasher[154] INFO Detected ApplicationType.SPINEL, version 'SL-OPENTHREAD/2.3.1.0_GitHub-e6df00dd6' (2.3.1.0) at 460800 baudrate (bootloader baudrate None)
2023-09-03 21:26:46 hass-home universal_silabs_flasher.flash[154] INFO Firmware version 'SL-OPENTHREAD/2.3.1.0_GitHub-e6df00dd6' (2.3.1.0) is flashed, not re-installing
```
