### ISSUE TITLE
Samba addon keeps restarting

### ISSUE THREAD

**Issue by michaelkuty** [home-assistant/addons#3217]
### Describe the issue you are experiencing

I have same setup for at least five years, supervised installation on ubuntu with couple addons everything was working well but couple weeks ago I found out that my samba addon is in restart loop due to
```
[10:54:52] INFO: smbd stopped, restarting...
interpret_interface: Can't find address for wlp3s0
WARNING: no network interfaces found
```
I tried full reinstalation but without any success

Could be related to not properly configured interface though supervisor ? 
https://github.com/home-assistant/addons/blob/master/samba/rootfs/etc/cont-init.d/samba.sh#L24
because I getting this kind of error when I trying to configure it

```
23-09-19 11:45:17 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 185, in block_bad_requests
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 201, in system_validation
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 268, in token_validation
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 280, in core_proxy
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/utils.py", line 62, in wrap_api
    answer = await method(api, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/network.py", line 222, in interface_update
    await asyncio.shield(self.sys_host.network.apply_changes(interface))
  File "/usr/src/supervisor/supervisor/host/network.py", line 220, in apply_changes
    settings = get_connection_from_interface(interface)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/dbus/network/setting/generate.py", line 131, in get_connection_from_interface
    "ssid": Variant("ay", interface.wifi.ssid.encode("UTF-8")),
                          ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'ssid'
```
but even with ha CLI I'm not able to disable this interface
```
root@master:~# ha network info                                                                                                                                                                                     
docker:                                                                                                  
  address: 172.30.32.0/23                                                                                                                                                                                          
  dns: 172.30.32.3                                                                                                                                                                                                 
  gateway: 172.30.32.1                                                                                   
  interface: hassio                                 
host_internet: true
interfaces:
- connected: false
  enabled: false
  interface: wlp3s0
  ipv4:
    address: []
    gateway: null
    method: disabled
    nameservers: []
    ready: false
  ipv6:
    address: []
    gateway: null
    method: disabled
    nameservers: []
    ready: false
  mac: 4A:MAC
  primary: false
  type: wireless
  vlan: null
  wifi: null
supervisor_internet: true

ha network update --disabled wlp3s0
Error: Requested Network interface update is not possible
```

Can you please help me, could be related to wrong CGroup ? But my system supports both versions
```
grep cgroup /proc/filesystems                                                             
nodev   cgroup                               
nodev   cgroup2 
```

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

Samba share

### What is the version of the add-on?

10.0.2

### Steps to reproduce the issue

1. Start addon
2.
3.
...

### System Health information

![image](https://github.com/home-assistant/addons/assets/3372169/a7b35a27-1364-4dba-900b-18f912e8271c)

### Anything in the Supervisor logs that might be useful for us?

```txt
23-09-19 10:40:44 INFO (SyncWorker_3) [supervisor.docker.manager] Cleaning addon_core_samba application
23-09-19 10:40:44 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-samba with version 10.0.2
23-09-19 10:40:44 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_samba
23-09-19 10:41:15 INFO (SyncWorker_1) [supervisor.docker.manager] Stopping addon_core_samba application
23-09-19 10:41:19 INFO (SyncWorker_1) [supervisor.docker.manager] Cleaning addon_core_samba application

23-09-19 10:44:46 INFO (MainThread) [supervisor.jobs] 'MountManager.reload' blocked from execution, mounting not supported on system
```

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/samba.sh
[10:54:51] INFO: Hostname: master
[10:54:51] INFO: Interfaces: wlp3s0 
No builtin backend found, trying to load plugin
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
account_policy_get: tdb_fetch_uint32_t failed for type 1 (min password length), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 2 (password history), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 3 (user must logon to change password), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 4 (maximum password age), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 5 (minimum password age), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 6 (lockout duration), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 7 (reset count minutes), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 8 (bad lockout attempt), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 9 (disconnect time), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 10 (refuse machine password change), returning 0
Added user michael.
cont-init: info: /etc/cont-init.d/samba.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun nmbd (no readiness notification)
services-up: info: copying legacy longrun smbd (no readiness notification)
s6-rc: info: service legacy-services successfully started
interpret_interface: Can't find address for wlp3s0
WARNING: no network interfaces found
nmbd version 4.16.10 started.
Copyright Andrew Tridgell and the Samba Team 1992-2022
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
Registered MSG_REQ_POOL_USAGE
interpret_interface: Can't find address for wlp3s0
WARNING: no network interfaces found
daemon_status: daemon 'nmbd' : No local IPv4 non-loopback interfaces available, waiting for interface ...
NOTE: NetBIOS name resolution is not supported for Internet Protocol Version 6 (IPv6).
interpret_interface: Can't find address for wlp3s0
WARNING: no network interfaces found
smbd version 4.16.10 started.
Copyright Andrew Tridgell and the Samba Team 1992-2022
uid=0 gid=0 euid=0 egid=0
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
Processing section "[config]"
Processing section "[addons]"
Processing section "[ssl]"
Processing section "[share]"
Processing section "[backup]"
Processing section "[media]"
interpret_interface: Can't find address for wlp3s0
WARNING: no network interfaces found
INFO: Profiling support unavailable in this build.
Registered MSG_REQ_POOL_USAGE
No builtin backend found, trying to load plugin
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_POOL_USAGE
open_sockets_smbd: No sockets available to bind to.
===============================================================
INTERNAL ERROR: open_sockets_smbd() failed in pid 135 (4.16.10)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 135): open_sockets_smbd() failed in 4.16.10
unable to produce a stack trace on this platform
coredump is handled by helper binary specified at /proc/sys/kernel/core_pattern
[10:54:52] INFO: smbd stopped, restarting...
interpret_interface: Can't find address for wlp3s0
WARNING: no network interfaces found
interpret_interface: Can't find address for wlp3s0
WARNING: no network interfaces found
```

**Comment by michaelkuty** [comment]
Closing as its related to supervisor network interfaces there is issue to properly load all interfaces and choose proper one to bind, so I forked it and hardcoded it to resolve my issue
