### ISSUE TITLE
Assist Microphone addon uses hardcoded HA:8123

### ISSUE THREAD

**Issue by SamJongenelen** [home-assistant/addons#3257]
### Describe the issue you are experiencing

I have to start with what an amazing Chapter4  ! Sorry for choosing Piper as the addon for this bugreport, the new addons are so fresh they arent even in the picklist.

Currently I am trying to get the `Assist Microphone` working, with a ReSpeaker usb mic/speaker device. 
However, the Assist Microphone tries to contact HA via `homeassistant:8123` - and that is, in my case, not the correct port.

Can we HA host URL configurable for this Addon?

>     raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host homeassistant:8123 ssl:default [Connect call failed ('172.30.32.1', 8123)]

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Piper

### What is the version of the add-on?

1.2.1

### Steps to reproduce the issue

1. run HA on non 8123 port
2. Install and Start addon 'Assist Microphone'
3. See error log, 
...

## System Information

version | core-2023.10.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.45
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4478
Installed Version | 1.33.0
Stage | running
Available Repositories | 1310
Downloaded Repositories | 41

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | May 29, 2024 at 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-7.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.10.0
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 56.6 GB
disk_used | 29.8 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Mosquitto broker (6.3.1), Vaultwarden (Bitwarden) (0.20.0), Check Home Assistant configuration (3.11.0), Grafana (9.0.3), Node-RED (14.6.1), Advanced SSH & Web Terminal (15.0.8), MariaDB (2.6.1), InfluxDB (4.7.0), Home Assistant Google Drive Backup (0.111.1), phpMyAdmin (0.8.8), AdGuard Home (4.8.15), Duck DNS (1.15.0), Portainer (2.0.0), ESPHome (2023.9.3), Glances (0.19.3), NGINX Home Assistant SSL proxy (3.5.0), Samba NAS (10.0.2-nas4), Filebrowser (2.23.0_reverted), FTP (4.7.2), Let's Encrypt (4.12.9), WireGuard (0.8.1), Piper (1.4.0), Whisper (1.0.0), openWakeWord (1.7.0), Assist Microphone (1.2.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 28
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 13, 2023 at 01:28
-- | --
current_recorder_run | October 13, 2023 at 09:51
estimated_db_size | 271.14 MiB
database_engine | mysql
database_version | 10.6.12

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
n/a
```

### Anything in the add-on logs that might be useful for us?

```txt
File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('172.30.32.1', 8123)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/homeassistant_satellite/__main__.py", line 193, in main
    async for _timestamp, event_type, event_data in stream(
  File "/usr/local/lib/python3.11/dist-packages/homeassistant_satellite/remote.py", line 26, in stream
    async with session.ws_connect(url) as websocket:
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host homeassistant:8123 ssl:default [Connect call failed ('172.30.32.1', 8123)]
```

**Comment by SamJongenelen** [comment]
wrong github :D
