### ISSUE TITLE
Matter server can't download PAA root certificates from Git

### ISSUE THREAD

**Issue by Jesibu** [home-assistant/addons#3326]
### Describe the issue you are experiencing

I try to install the Matter Server on my local install inside the HomeAssistant VW

```2023-11-22 15:24:02 core-matter-server matter_server.server.helpers.paa_certificates[127] INFO Fetched 114 PAA root certificates from DCL.
2023-11-22 15:24:02 core-matter-server matter_server.server.helpers.paa_certificates[127] INFO Fetching the latest PAA root certificates from Git.
2023-11-22 15:29:03 core-matter-server asyncio[127] ERROR Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:209> exception=TimeoutError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/server.py", line 94, in start
    await self.device_controller.initialize()
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 94, in initialize
    await fetch_certificates()
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/helpers/paa_certificates.py", line 153, in fetch_certificates
    fetch_count += await fetch_git_certificates()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/helpers/paa_certificates.py", line 126, in fetch_git_certificates
    async with http_session.get(f"{GIT_URL}/{cert}.pem") as response:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1167, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 493, in _request
    with timer:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 725, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Matter Server

### What is the version of the add-on?

4.10.2

### Steps to reproduce the issue

just install 

## System Information

version | core-2023.11.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | failed to load: timeout
can_reach_cloud_auth | failed to load: timeout
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2.rc1
-- | --
update_channel | beta
supervisor_version | supervisor-2023.11.4
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 3.7 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | failed to load: timeout
installed_addons | Matter Server (4.10.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 22 November 2023 at 08:56
-- | --
current_recorder_run | 22 November 2023 at 15:20
estimated_db_size | 0.58 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by marcelveldt** [comment]
That looks like just a temporary issue with Github or your internet connection ?!
