### ISSUE TITLE
Matter server not starting at all after 5.0.1 update

### ISSUE THREAD

**Issue by aatifk** [home-assistant/addons#3350]
### Describe the issue you are experiencing

Just updated Matter Server to 5.0.1 and now it won't start. I've restarted Home Assistant and rebooted the Home Assistant hardware as well but it just fails to start.  Log shows exec /init: exec format error.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Matter Server

### What is the version of the add-on?

5.0.1

### Steps to reproduce the issue

1. Update Matter Server to 5.0.1
2. Server fails to start (automatically or manually)
3.
...

### System Health information

Says "there are currently no repairs available

### Anything in the Supervisor logs that might be useful for us?

```txt
23-12-08 11:39:08 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-matter-server with version 5.0.1
23-12-08 11:39:08 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-15748' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1327> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1341, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 276, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
23-12-08 11:40:27 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning addon_core_matter_server application
23-12-08 11:40:28 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-16185' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1327> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1341, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 276, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
23-12-08 11:40:28 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-matter-server with version 5.0.1
23-12-08 11:41:48 INFO (SyncWorker_1) [supervisor.docker.manager] Cleaning addon_core_matter_server application
23-12-08 11:41:48 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-16707' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1327> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1341, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 276, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
23-12-08 11:41:48 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-matter-server with version 5.0.1
23-12-08 11:42:10 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning addon_core_matter_server application
23-12-08 11:42:11 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-16954' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1327> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1341, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 276, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
23-12-08 11:42:11 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-matter-server with version 5.0.1
```

**Comment by agners** [comment]
Did that resolve for you with the latest update? If not can you share the add-on logs?
