### ISSUE TITLE
Piper: EOFError: marshal data too short

### ISSUE THREAD

**Issue by walking-octopus** [home-assistant/addons#3361]
### Describe the issue you are experiencing

The server exits with the following error.

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service piper: starting
s6-rc: info: service piper successfully started
s6-rc: info: service discovery: starting
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/__main__.py", line 3, in <module>
    import asyncio
  File "/usr/lib/python3.11/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/lib/python3.11/asyncio/base_events.py", line 18, in <module>
    import concurrent.futures
  File "/usr/lib/python3.11/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 7, in <module>
    import logging
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1069, in get_code
  File "<frozen importlib._bootstrap_external>", line 729, in _compile_bytecode
EOFError: marshal data too short
[21:47:52] INFO: Service exited with code 1 (by signal 0)
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Piper

### What is the version of the add-on?

1.4.0

### Steps to reproduce the issue

1. Install Piper on Home Assistant OS
2. Pick a voice
3. Observe the issue
...

### System Health information

```
## System Information

version | core-2023.10.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Kiev
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | pending
can_reach_cloud_auth | pending
can_reach_cloud | pending

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.6
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 58.0 GB
disk_used | 28.8 GB
healthy | true
supported | true
board | rpi3-64
supervisor_api | ok
version_api | pending
installed_addons | Samba share (12.2.0), Mosquitto broker (6.3.1), Node-RED (14.6.3), SQLite Web (4.0.0), Terminal & SSH (9.7.1), Piper (1.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 21, 2023 at 02:59
-- | --
current_recorder_run | December 14, 2023 at 05:54
estimated_db_size | 98.22 MiB
database_engine | sqlite
database_version | 3.41.2

</details>
```

**Comment by walking-octopus** [comment]
Resolved after reinstall...
