### ISSUE TITLE
Assist Microphone SSL connect fail

### ISSUE THREAD

**Issue by lein1013** [home-assistant/addons#3365]
### Describe the issue you are experiencing

Assist Microphone is configured to use a USB microphone. When the wake word is said the connection to HA cannot be created.
I used Wisper in the dropdown below, since "Assist Microphone" is not available in the dropdown.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Whisper

### What is the version of the add-on?

2.2.3

### Steps to reproduce the issue

1. install addon
2. connect USB microphone
3. configure webrtcvad
4. configure Host  xyz.duckdns.org
5. start addon
6. wait for "Recording raw data 'stdin':
7. say hotword
8. check logs

ip and domain name changed for privacy

### System Health information

all good

### Anything in the add-on logs that might be useful for us?

```txt
...
File "/usr/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('178.111.111.111', 8123)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/homeassistant_satellite/__main__.py", line 200, in main
    async for _timestamp, event_type, event_data in stream(
  File "/usr/local/lib/python3.11/dist-packages/homeassistant_satellite/remote.py", line 28, in stream
    async with session.ws_connect(url) as websocket:
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host xyz.duckdns.org:8123 ssl:default [Connect call failed ('178.111.111.111', 8123)]
```

### Additional information

I use the nginx addon and have proxy hosts the xyz.duckdns.org mapped to destination http://10.x.y.z:8123
tried with and without SSL
also I have the nabucasa cloud

**Comment by lein1013** [comment]
OK, It works smoothless if I use the new Assist Microphone 1.0.0  (of the Official-Add-ons) instead of the 2.2.3 (from Rhasspy Hass.IO Add-Ons)
great job!
