### ISSUE TITLE
issue with Silicon Labs Multiprotocol Add-on and Sonoff Zigbee Dongle plus E : Failed to connect, secondary seems unresponsive

### ISSUE THREAD

**Issue by Kri72** [home-assistant/addons#3412]
### Describe the issue you are experiencing

I've flashed the Sonoff Zigbee Dongle plus 3 according https://dialedin.com.au/blog/sonoff-zbdongle-e-rcp-firmware, and have then installed Silicon Labs Multiprotocol Add-on with the configuration below, but get continuous error in the log "Failed to connect, secondary seems unresponsive"
![image](https://github.com/home-assistant/addons/assets/91803162/1c55776f-20bb-429b-b5e9-411c02f1277d)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

2.4.3

### Steps to reproduce the issue

1. upgrade firmware of Dongle according https://dialedin.com.au/blog/sonoff-zbdongle-e-rcp-firmware with latest Zigbee firmware
2. Install Silicon Labs Multiprotocol Add-on version 2.4.3
3. Run the add on according confirguration attached above
...

## System Information

version | core-2024.1.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4572
Installed Version | 1.33.0
Stage | running
Available Repositories | 1378
Downloaded Repositories | 48

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | September 10, 2024 at 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | eu-central-1-4.ui.nabu.casa
certificate_status | ready
instance_id | 96b650674c4d4b979fc74636bf614237
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 916.2 GB
disk_used | 31.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.2.0), File editor (5.7.0), motionEye (0.20.0), Home Panel (2.7.0), Grafana (9.1.2), Node-RED (17.0.2), Advanced SSH & Web Terminal (17.0.3), Home Assistant Google Drive Backup (0.112.1), Z-Wave JS UI (3.1.0), InfluxDB (5.0.0), Studio Code Server (5.15.0), RTSP Simple Server Add-on (v0.17.6), Mosquitto broker (6.4.0), Frigate (0.12.1), SQLite Web (4.1.0), eufy-security-ws (1.7.1), eWeLink Smart Home (1.4.3), Zigbee2MQTT (1.35.1-1), Silicon Labs Multiprotocol (2.4.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 19
views | 22
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 8, 2024 at 20:03
-- | --
current_recorder_run | January 14, 2024 at 14:14
estimated_db_size | 168.61 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.hassio.handler
Source: components/hassio/handler.py:584
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 14:24:42 (8 occurrences)
Last logged: 14:42:30

Timeout on /addons/core_silabs_multiprotocol/start request
```

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/check-cpcd-shm.sh
cont-init: info: /etc/cont-init.d/check-cpcd-shm.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service banner: starting

-----------------------------------------------------------
 Add-on: Silicon Labs Multiprotocol
 Zigbee and OpenThread multiprotocol add-on
-----------------------------------------------------------
 Add-on version: 2.4.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.4  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.1.3
 Home Assistant Supervisor: 2023.12.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service universal-silabs-flasher: starting
[15:09:33] INFO: Flashing firmware is disabled
s6-rc: info: service universal-silabs-flasher successfully started
s6-rc: info: service cpcd-config: starting
[15:09:34] INFO: Generating cpcd configuration.
s6-rc: info: service cpcd-config successfully started
s6-rc: info: service cpcd: starting
[15:09:35] INFO: Starting cpcd...
WARNING in function 'main' in file /usr/src/cpc-daemon/main.c at line #187 : Running CPCd as 'root' is not recommended. Proceed at your own risk.
[2024-01-14T14:09:35.151125Z] Info : [CPCd v4.4.0.0] [Library API v3] [RCP Protocol v5]
[2024-01-14T14:09:35.151284Z] Info : Git commit: 1fcaa81347466165f81e4533ee4471e9c3b6db0a / branch: 
[2024-01-14T14:09:35.151288Z] Info : Sources hash: 1e938c77bacd9c9d6d8fe7b457208a3a8a2435bd6374a1918605ffb864bf1ebe
[2024-01-14T14:09:35.151309Z] WARNING : In function 'main' in file /usr/src/cpc-daemon/main.c at line #187 : Running CPCd as 'root' is not recommended. Proceed at your own risk.
[2024-01-14T14:09:35.151535Z] Info : Reading cli arguments
[2024-01-14T14:09:35.151549Z] Info : /usr/local/bin/cpcd 
[2024-01-14T14:09:35.154978Z] Info : Reading configuration
[2024-01-14T14:09:35.154992Z] Info :   file_path = /usr/local/etc/cpcd.conf
[2024-01-14T14:09:35.154995Z] Info :   instance_name = cpcd_0
[2024-01-14T14:09:35.154997Z] Info :   socket_folder = /dev/shm
[2024-01-14T14:09:35.155000Z] Info :   operation_mode = MODE_NORMAL
[2024-01-14T14:09:35.155002Z] Info :   use_encryption = false
[2024-01-14T14:09:35.155004Z] Info :   binding_key_file = /etc/binding-key.key
[2024-01-14T14:09:35.155007Z] Info :   stdout_tracing = false
[2024-01-14T14:09:35.155009Z] Info :   file_tracing = false
[2024-01-14T14:09:35.155011Z] Info :   lttng_tracing = false
[2024-01-14T14:09:35.155013Z] Info :   enable_frame_trace = false
[2024-01-14T14:09:35.155014Z] Info :   traces_folder = /dev/shm/cpcd-traces
[2024-01-14T14:09:35.155017Z] Info :   bus = UART
[2024-01-14T14:09:35.155019Z] Info :   uart_baudrate = 460800
[2024-01-14T14:09:35.155022Z] Info :   uart_hardflow = false
[2024-01-14T14:09:35.155024Z] Info :   uart_file = /dev/ttyACM1
[2024-01-14T14:09:35.155026Z] Info :   fu_recovery_pins_enabled = false
[2024-01-14T14:09:35.155029Z] Info :   fu_connect_to_bootloader = false
[2024-01-14T14:09:35.155031Z] Info :   fu_enter_bootloader = false
[2024-01-14T14:09:35.155033Z] Info :   restart_cpcd = false
[2024-01-14T14:09:35.155035Z] Info :   application_version_validation = false
[2024-01-14T14:09:35.155037Z] Info :   print_secondary_versions_and_exit = false
[2024-01-14T14:09:35.155039Z] Info :   use_noop_keep_alive = false
[2024-01-14T14:09:35.155041Z] Info :   reset_sequence = true
[2024-01-14T14:09:35.155043Z] Info :   stats_interval = 0
[2024-01-14T14:09:35.155045Z] Info :   rlimit_nofile = 2000
[2024-01-14T14:09:35.155048Z] Info : ENCRYPTION IS DISABLED 
[2024-01-14T14:09:35.167953Z] Info : Starting daemon in normal mode
[2024-01-14T14:09:35.182677Z] Info : Connecting to Secondary...
[2024-01-14T14:09:37.183482Z] Info : Failed to connect, secondary seems unresponsive
[2024-01-14T14:09:37.183522Z] Info : Connecting to Secondary...
[2024-01-14T14:09:39.184054Z] Info : Failed to connect, secondary seems unresponsive
[2024-01-14T14:09:39.184087Z] Info : Connecting to Secondary...
[2024-01-14T14:09:41.184554Z] Info : Failed to connect, secondary seems unresponsive
[2024-01-14T14:09:41.184595Z] Info : Connecting to Secondary...
[2024-01-14T14:09:43.185133Z] Info : Failed to connect, secondary seems unresponsive
[2024-01-14T14:09:43.185174Z] Info : Connecting to Secondary...
[2024-01-14T14:09:45.185446Z] Info : Failed to connect, secondary seems unresponsive
[2024-01-14T14:09:45.185472Z] Info : Connecting to Secondary...
[2024-01-14T14:09:47.185812Z] Info : Failed to connect, secondary seems unresponsive
[2024-01-14T14:09:47.185854Z] Info : Connecting to Secondary...
```

**Comment by agners** [comment]
@darkxst can you have a look at this?

**Comment by darkxst** [comment]
@Kri72 Which version firmware did you flash? You need 4.4.0 to work this version of silabs multiprotocol, but I havent updated my webflasher, (or that blog post yet) which are still at 4.3.2.

You can install directly this firmware:
https://github.com/darkxst/silabs-firmware-builder/raw/main/firmware_builds/zbdonglee/rcp-uart-802154-v4.4.0-zbdonglee-460800.gbl

Or use my multipan flasher add-on which is updated with 4.4.0
https://github.com/darkxst/multipan_flasher

**Comment by yalec38** [comment]
Hello, I think we should downgrade the version of Silicon Labs Multiprotocol to version 2.4.2 or earlier because the version installed by Kry72 is incompatible with zigbee2mqtt
![image](https://github.com/home-assistant/addons/assets/55202342/71ffc727-1f11-4ff9-9276-40bfc136c243)

**Comment by Kri72** [comment]
Hello to all!! thanks for youor feedback.. In fact i have flashed latest version from the webflasher, which is : SDK version 4.3.1, EZSP Version 7.3.1.0 Build 176.
I'll try in the coming days to 4.4.0, and will keep you informed!

**Comment by darkxst** [comment]
> for those of us who are lazy and willing to buy a cup of coffee any eta on updating the webflasher =}

I havent updated it due to the Zigbee2MQTT breakage. It would recommend using the multipan flasher addon to get latest multipan firmware if you are using ZHA!

**Comment by chrizstone** [comment]
I have flashed the firmware with your 

> @Kri72 Which version firmware did you flash? You need 4.4.0 to work this version of silabs multiprotocol, but I havent updated my webflasher, (or that blog post yet) which are still at 4.3.2.
> 
> You can install directly this firmware: https://github.com/darkxst/silabs-firmware-builder/raw/main/firmware_builds/zbdonglee/rcp-uart-802154-v4.4.0-zbdonglee-460800.gbl
> 
> Or use my multipan flasher add-on which is updated with 4.4.0 https://github.com/darkxst/multipan_flasher

I flashed the firmware via the multipan flasher add-on. Sadly I still get the error when trying to start the Zigbee2Mqtt add-on:

Error: {"address":0,"clusterId":32770,"sequence":2} after 10000ms
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)

**Comment by chrizstone** [comment]
> > I flashed the firmware via the multipan flasher add-on. Sadly I still get the error when trying to start the Zigbee2Mqtt add-on:
> 
> You the time being you will need to install Zigbee2MQTT Edge add-on, which includes initial support for the updated EZSP protocol that comes with 4.4.0...

Oh yes, that works :) And if the fix is in stable version, I am able to just switch to the stable add-on?

**Comment by Kri72** [comment]
> eed 4.4.0 to work this version of silabs multipro

Hello @darkxst , that's it, I could update my dongle to 4.4.0 thanks to you multipan flasher!

However, it doesnz't work any better..
I still get from Zigbee2mqtt 

```
[19:52:05] INFO: Preparing to start...
[19:52:06] INFO: Socat not enabled
[19:52:09] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:debug 2024-01-21 19:52:16: Loaded state from file /config/zigbee2mqtt/state.json
Zigbee2MQTT:info  2024-01-21 19:52:16: Logging to console and directory: '/config/zigbee2mqtt/log/2024-01-21.19-52-16' filename: log.txt
Zigbee2MQTT:debug 2024-01-21 19:52:16: Removing old log directory '/config/zigbee2mqtt/log/2024-01-21.19-28-00'
Zigbee2MQTT:info  2024-01-21 19:52:16: Starting Zigbee2MQTT version 1.35.1 (commit #unknown)
Zigbee2MQTT:info  2024-01-21 19:52:16: Starting zigbee-herdsman (0.30.0)
Zigbee2MQTT:debug 2024-01-21 19:52:16: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[25],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"ezsp","path":"tcp://core-silabs-multiprotocol:9999"}}'
Zigbee2MQTT:error 2024-01-21 19:52:37: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2024-01-21 19:52:37: Failed to start zigbee
Zigbee2MQTT:error 2024-01-21 19:52:37: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2024-01-21 19:52:37: Exiting...
Zigbee2MQTT:error 2024-01-21 19:52:37: Error: Failure to connect
    at Ezsp.connect (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:277:19)
    at Driver.startup (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:139:9)
    at EZSPAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:172:16)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:60:27)
    at Controller.start (/app/lib/controller.ts:98:27)
    at start (/app/index.js:107:5)
```

And from Silicon Lab Multiprotocol 
```
[2024-01-21T18:56:06.193196Z] Info : New client connection using library v4.4.0.0
otbr-ingress-allow-dst
otbr-ingress-allow-dst-swap
OTBR_FORWARD_EGRESS  all opt    in wpan0 out *  ::/0  -> ::/0  
Chain OTBR_FORWARD_EGRESS (0 references)
target     prot opt source               destination         
ACCEPT     all      anywhere             anywhere            
[19:56:06] INFO: OTBR firewall teardown completed.
[19:56:06] WARNING: otbr-agent exited with code 1 (by signal 0).
WARNING in function 'is_endpoint_opened_reply_v5' in file /usr/src/cpc-daemon/server_core/core/protocol_v5.c at line #132 : Property-get::PROP_ENDPOINT_STATE aborted
WARNING in function 'is_endpoint_opened_reply_v5' in file /usr/src/cpc-daemon/server_core/core/protocol_v5.c at line #152 : Could not read endpoint state on the secondary
close cpc endpoint: No such file or directory
By using this software, you are agreeing to the Silicon Labs MSLA found at https://www.silabs.com/about-us/legal/master-software-license-agreement.
[19:56:08] INFO: zigbeed ended with exit code 1 (signal 0)...
[19:56:08] INFO: Setup OTBR firewall...
[2024-01-21T18:56:07.995085Z] WARNING : In function 'is_endpoint_opened_reply_v5' in file /usr/src/cpc-daemon/server_core/core/protocol_v5.c at line #132 : Property-get::PROP_ENDPOINT_STATE aborted
[2024-01-21T18:56:07.995131Z] WARNING : In function 'is_endpoint_opened_reply_v5' in file /usr/src/cpc-daemon/server_core/core/protocol_v5.c at line #152 : Could not read endpoint state on the secondary
[2024-01-21T18:56:07.997393Z] Info : Client disconnected
[19:56:08] INFO: Starting otbr-agent...
otbr-agent[33248]: [NOTE]-AGENT---: Running 0.3.0
otbr-agent[33248]: [NOTE]-AGENT---: Thread version: 1.3.0
otbr-agent[33248]: [NOTE]-AGENT---: Thread interface: wpan0
otbr-agent[33248]: [NOTE]-AGENT---: Radio URL: spinel+cpc://cpcd_0?iid=2&iid-list=0
otbr-agent[33248]: [NOTE]-ILS-----: Infra link selected: end0
[19:56:09] INFO: Starting zigbeed...
[2024-01-21T18:56:08.276452Z] Info : New client connection using library v4.4.0.0
WARNING in function 'is_endpoint_opened_reply_v5' in file /usr/src/cpc-daemon/server_core/core/protocol_v5.c at line #132 : Property-get::PROP_ENDPOINT_STATE aborted
WARNING in function 'is_endpoint_opened_reply_v5' in file /usr/src/cpc-daemon/server_core/core/protocol_v5.c at line #152 : Could not read endpoint state on the secondary
otbr-agent[33248]: 49d.17:34:43.224 [C] Platform------: CPC endpoint open failed
otbr-agent[33248]: 49d.17:34:43.224 [C] Platform------: mCpcBusSpeed = 115200
otbr-agent[33248]: 49d.17:34:43.224 [C] Platform------: Init() at radio_spinel.cpp:125: Failure
close cpc endpoint: Success
[19:56:10] INFO: otbr-agent ended with exit code 1 (signal 0)...
OTBR_FORWARD_INGRESS  all opt    in * out wpan0  ::/0  -> ::/0  
Chain OTBR_FORWARD_INGRESS (0 references)
target     prot opt source               destination         
DROP       all      anywhere             anywhere             PKTTYPE = unicast
DROP       all      anywhere             anywhere             match-set otbr-ingress-deny-src src
ACCEPT     all      anywhere             anywhere             match-set otbr-ingress-allow-dst dst
DROP       all      anywhere             anywhere             PKTTYPE = unicast
ACCEPT     all      anywhere             anywhere            
otbr-ingress-deny-src
otbr-ingress-deny-src-swap
[2024-01-21T18:56:09.995136Z] WARNING : In function 'is_endpoint_opened_reply_v5' in file /usr/src/cpc-daemon/server_core/core/protocol_v5.c at line #132 : Property-get::PROP_ENDPOINT_STATE aborted
[2024-01-21T18:56:09.995226Z] WARNING : In function 'is_endpoint_opened_reply_v5' in file /usr/src/cpc-daemon/server_core/core/protocol_v5.c at line #152 : Could not read endpoint state on the secondary
[2024-01-21T18:56:09.999349Z] Info : Client disconnected
[2024-01-21T18:56:10.190504Z] Info : New client connection using library v4.4.0.0
otbr-ingress-allow-dst
otbr-ingress-allow-dst-swap
OTBR_FORWARD_EGRESS  all opt    in wpan0 out *  ::/0  -> ::/0  
Chain OTBR_FORWARD_EGRESS (0 references)
target     prot opt source               destination         
ACCEPT     all      anywhere             anywhere            
[19:56:10] INFO: OTBR firewall teardown completed.
[19:56:10] WARNING: otbr-agent exited with code 1 (by signal 0).
```

**Comment by darkxst** [comment]
> [C] Platform------: mCpcBusSpeed = 115200

Check  Baud rate setting, it should be 460800

Z2M needs to connect to the silabs-multiprotol addon, so not going to work until that is working!

**Comment by darkxst** [comment]
> And if the fix is in stable version, I am able to just switch to the stable add-on?

yes, once 1.36 is release you can just switch back. Probably worth taking a backup of the z2m config folder, but it should work just fine

**Comment by chrizstone** [comment]
I just updated the Silicon Labs Multiprotocol to version 2.4.4 and now getting this error:

`*** ASSERT *** : FATAL in function 'protocol_version_check' in file /usr/src/cpc-daemon/server_core/server_core.c at line #729 : Secondary Protocol v5 doesn't match CPCd Protocol v4
[21:10:35:527823] Info : Daemon exiting with status EXIT_FAILURE
Logger buffer size = 28672, highwater mark = 2439 : 8.51%. Lost logs : 0
[21:10:35] INFO: CPC ended with exit code 1 (signal 0)...` when trying to start it? What could be the probem here?

**Comment by darkxst** [comment]
> I just updated the Silicon Labs Multiprotocol to version 2.4.4

You need to downgrade back to Multipan 4.3.1 again. Seems 4.4.0 hasn't been working out so well.

**Comment by MYanello** [comment]
> > I just updated the Silicon Labs Multiprotocol to version 2.4.4
> 
> You need to downgrade back to Multipan 4.3.1 again. Seems 4.4.0 hasn't been working out so well.

So with this advice what should we be using? z2mqtt edge and multipan 4.3.1?
If so, how do we get past the original issue since the fix for that seemed to be run 4.4.0? Apologies, I'm getting lost a bit in the different advice but came here for the issue that was in the original post.

> Which version firmware did you flash? You need 4.4.0 to work this version of silabs multiprotocol, but I havent updated my webflasher,

**Comment by tl-sl** [comment]
@MYanello As a general rule you always need to use the same 4.x version as the Silabs Multiprotocol addon is using. Twice now, this has been downgraded back to 4.3.1.  As a one-off 4.3.2 also has some stability issues so that is the reasoning for going back to 4.3.1 instead.

Just keep an eye on the release notes, whenever they bump to a new major 4.x version you need to update firmware. 
https://github.com/home-assistant/addons/blob/master/silabs-multiprotocol/CHANGELOG.md

**Comment by MYanello** [comment]
Thanks. I can confirm it is working now with z2m 1.35.3; silabs multiprotocol 2.4.4; multipan flasher 0.2.1; and sonoff 3.0 e version 4.3.1.

**Comment by Kri72** [comment]
> Thanks. I can confirm it is working now with z2m 1.35.3; silabs multiprotocol 2.4.4; multipan flasher 0.2.1; and sonoff 3.0 e version 4.3.1.

Hello @MYanello  does this mean I need to reflash my Sonoff back from 4.4 to 4.3.1?  I also need to revert Multipan flasher from 0.2.2 to 0.2.1?

**Comment by MYanello** [comment]
> > Thanks. I can confirm it is working now with z2m 1.35.3; silabs multiprotocol 2.4.4; multipan flasher 0.2.1; and sonoff 3.0 e version 4.3.1.
> 
> Hello @MYanello does this mean I need to reflash my Sonoff back from 4.4 to 4.3.1? I also need to revert Multipan flasher from 0.2.2 to 0.2.1?

If it ain't broke, don't fix it. But I couldn't get z2m up when I was running 4.4.

**Comment by darkxst** [comment]
> If it ain't broke, don't fix it.

Its not optional. Firmware must match what the multiprotocol addon is using 4.4.x firmware will not work with 4.3.x multiprotocol addon. Or vise versa. For now run 4.3.1, when the multiprotocol changelog mentions upgrading to 4.4.x again then you need to update firmware again.

**Comment by joswart** [comment]
I am using a Sonoff device that should be able to do both Zigbee and Thread. USB ID: 
/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230829203441-if00

I flashed it with firmware 4.3.1 through the web flash tool.

Thread Border Router is started, but after around 2 days I am hit with the "Failed to connect, secondary seems unresponsive" issue. The only solution is to disconnect the USB device from my PC and plug it back in. After that operation everything works for another two days.

**Comment by darkxst** [comment]
multiprotocol is essentially unsupported these days, due to poor stability when sharing the radio. It is strongly recommend to use separate dongles for Zigbee and Thread OTBR addon.

**Comment by joepio** [comment]
If Silicon Labs Multiprotocol is unsupported / no longer maintained, perhaps it's best to remove it from the official add-ons list.

**Comment by thomas1970w** [comment]
@darkxst hi could you have a look, i have actual a problem with flashing the custom FW Z3RouterUSBDonlge_EZNet6.10.3_V1.0.0.gbl .. when i use https://darkxst.github.io/silabs-firmware-builder/ - i get an error message like
![Image](https://github.com/user-attachments/assets/c43fd9b5-c891-470d-b1e3-40adbf31a4d7)
do you have an idea ?

**Comment by darkxst** [comment]
The Sonoff builds wont work with web flasher, you should use the "Silabs flasher" HA addon instead.
