### ISSUE TITLE
Watchdog reach limit when internet is down

### ISSUE THREAD

**Issue by tyjtyj** [home-assistant/addons#3439]
### Describe the issue you are experiencing

Watchdog attempt to restart the addons such as Duck DNS and Cloudflared during internet down causing the addons to failed. 

After 10 attemps while internet still down, watchdog reached limit

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Duck DNS

### What is the version of the add-on?

1.15.0

### Steps to reproduce the issue

1. Disconnect the internet for more than 10 mins
2.
3.
...

### System Health information

There are currently no repair available

### Anything in the Supervisor logs that might be useful for us?

```txt
24-01-26 11:06:01 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/brenner-tobias/cloudflared/aarch64 with version 5.1.0
24-01-26 11:06:06 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Duck DNS is failed, restarting...
24-01-26 11:06:06 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning addon_core_duckdns application
24-01-26 11:06:10 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-duckdns with version 1.15.0
24-01-26 11:06:22 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Cloudflared is failed, restarting...
24-01-26 11:06:22 INFO (SyncWorker_0) [supervisor.docker.manager] Cleaning addon_9074a9fa_cloudflared application
24-01-26 11:06:25 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/brenner-tobias/cloudflared/aarch64 with version 5.1.0
24-01-26 11:06:30 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Duck DNS is failed, restarting...
24-01-26 11:06:30 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning addon_core_duckdns application
24-01-26 11:06:34 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-duckdns with version 1.15.0
24-01-26 11:06:45 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Cloudflared is failed, restarting...
24-01-26 11:06:45 INFO (SyncWorker_1) [supervisor.docker.manager] Cleaning addon_9074a9fa_cloudflared application
24-01-26 11:06:49 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/brenner-tobias/cloudflared/aarch64 with version 5.1.0
24-01-26 11:06:54 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-20606' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1346> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1360, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 276, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
24-01-26 11:07:08 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-21164' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1346> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1360, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 276, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
```

### Additional information

Watchdog attempt to restart the service 10 times within 4 mins. This resulting the limit reached.

Work around, dont restart when internet is down ? 
Exponential restart, eg 1,5,10,30,60 mins and repeat 60 over 24 hours or more ?

The watchdog purpose is to ensure the container is working. 

My current work around 
Enable automation to monitor running Cloudflared container every 10 mins, if it is down, restarted the container.

**Comment by jv271** [comment]
I vote for "Exponential restart, eg 1,5,10,30,60 mins and repeat 60 over 24 hours or more".

**Comment by Koknico** [comment]
I'm experiencing the same problem with Cloudflared Addon.
When I'm away and Internet failed for a while, my Home Assistant remain unreacheable until I came back.
This is really annoying.
Please reopen this issue @tyjtyj

**Comment by sbraz** [comment]
Hi, I made a feature request for this: https://community.home-assistant.io/t/configurable-retries-or-exponential-backoff-for-watchdog-to-avoid-rate-limit-exceeded-more-than-10-calls-in-000/896253
Please vote on it to make it more visible.
