### ISSUE TITLE
Assist Microphone - wake word detected only once

### ISSUE THREAD

**Issue by myrakrusemark** [home-assistant/addons#3464]
### Describe the issue you are experiencing

(BTW, might want to add Assist Microphone to the list of available add-ons to report on)
Duplicated from https://github.com/home-assistant/core/issues/110351

I'm using a Jabra 410 via USB with Assist Microphone. It works once, maybe twice, and then no longer works unless I either restart the add-on, or, if I mute and unmute the mic, it will sometimes work again.

I created an automation to do this for me, but again, it only sometimes works and I'll find myself yelling "Computer!" into the abyss.

There are no error logs to speak of, I think the issue may reside in some sort of joining of threads when audio capture is complete, but only a guess.

The issue is independent of any wake word I use (openwakeword, snowboy, porcupine1).

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

CEC Scanner

### What is the version of the add-on?

1.0.0

### Steps to reproduce the issue

1. WIth Assist Microphone Installed
2. With Jabra 410 USB speaker/mic installed
3. Use Assist Microphone normally with an assistant in HA
4. Wake, and speak normally, process finishes
5. Wake word no longer works.
6. Mute and unmute microphone in the MA device panel OR restart MA
7. Might work one more time
...

### System Health information

I don't have this option in my HA instance??

### Anything in the Supervisor logs that might be useful for us?

```txt
There are no errors to speak of for this issue. I've had similar problems with audio with failed thread joins.
```

### Anything in the add-on logs that might be useful for us?

```txt
Full log since last night.

s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service assist_microphone: starting
s6-rc: info: service assist_microphone successfully started
s6-rc: info: service discovery: starting
INFO:root:Ready
INFO:root:Connected to services
Recording raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
[19:50:25] INFO: Successfully sent discovery information to Home Assistant.
s6-rc: info: service discovery successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
INFO:root:Streaming audio
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
INFO:root:Streaming audio
INFO:root:Streaming audio
INFO:root:Streaming audio
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
INFO:root:Streaming audio
INFO:root:Streaming audio
INFO:root:Streaming audio
INFO:root:Streaming audio
INFO:root:Streaming audio
INFO:root:Streaming audio
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
INFO:root:Streaming audio
INFO:root:Streaming audio
INFO:root:Streaming audio
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Streaming audio
INFO:root:Streaming audio
INFO:root:Streaming audio
INFO:root:Streaming audio
INFO:root:Streaming audio
INFO:root:Streaming audio
INFO:root:Streaming audio
INFO:root:Streaming audio
INFO:root:Streaming audio
INFO:root:Streaming audio
INFO:root:Streaming audio
```

**Comment by oiml** [comment]
I have the same issue. 
Log from Assist Microphone:

```shell
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service assist_microphone: starting
s6-rc: info: service assist_microphone successfully started
s6-rc: info: service discovery: starting
DEBUG:root:Namespace(mic_uri=None, mic_command='arecord -r 16000 -c 1 -f S16_LE -t raw', mic_command_rate=16000, mic_command_width=2, mic_command_channels=1, mic_command_samples_per_chunk=1024, mic_volume_multiplier=1.5, mic_noise_suppression=2, mic_auto_gain=4, snd_uri=None, snd_command='aplay -r 16000 -c 1 -f S16_LE -t raw', snd_command_rate=16000, snd_command_width=2, snd_command_channels=1, snd_volume_multiplier=1.0, wake_uri=None, wake_word_name=[], wake_command=None, wake_command_rate=16000, wake_command_width=2, wake_command_channels=1, vad=False, vad_threshold=0.5, vad_trigger_level=1, vad_buffer_seconds=2, vad_wake_word_timeout=5.0, event_uri=None, startup_command=None, detect_command=None, detection_command=None, transcript_command=None, stt_start_command=None, stt_stop_command=None, synthesize_command=None, tts_start_command=None, tts_stop_command=None, streaming_start_command=None, streaming_stop_command=None, error_command=None, awake_wav='/usr/src/sounds/awake.wav', done_wav='', uri='tcp://0.0.0.0:10700', name='assist microphone', area=None, no_zeroconf=True, zeroconf_name=None, zeroconf_host=None, debug=True)
INFO:root:Ready
DEBUG:root:Connecting to mic service: ['arecord', '-r', '16000', '-c', '1', '-f', 'S16_LE', '-t', 'raw']
DEBUG:root:Connecting to snd service: ['aplay', '-r', '16000', '-c', '1', '-f', 'S16_LE', '-t', 'raw']
INFO:root:Connected to services
DEBUG:root:Using webrtc audio enhancements
DEBUG:root:Connected to mic service
Recording raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
[11:48:37] INFO: Successfully sent discovery information to Home Assistant.
s6-rc: info: service discovery successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
DEBUG:root:Server set: 59933965328040
INFO:root:Streaming audio
DEBUG:root:Wake word detected
DEBUG:root:Connected to snd service
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
DEBUG:root:Event(type='transcript', data={'text': ' Do something.'}, payload=None)
INFO:root:Streaming audio
DEBUG:root:Event(type='synthesize', data={'text': 'Did something', 'voice': {'name': 'de_DE-thorsten-high'}}, payload=None)
DEBUG:root:Connected to snd service
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
``` 

Afterwards, it stops functioning until I restart the Addon. If I reload the integration in the wyoming protocol, the addon log gets flooded with these:
```shell
DEBUG:root:Connection cancelled: 73160184118258
DEBUG:root:Connection cancelled: 73168186595571
DEBUG:root:Connection cancelled: 73176188033183
DEBUG:root:Connection cancelled: 73184190937269
DEBUG:root:Connection cancelled: 73192193808068
``` 

Until I restart the addon.

**Comment by myrakrusemark** [comment]
@oiml Thanks for this more comprehensive logs! Ill have to research how to turn on those debug messages.

I have also seen that satellite disconnection.

**Comment by GinAndBacon** [comment]
Looks like your on top of it but same issue, started a few releases back but not sure the exact release since there are 5 core updates a month. Same error if following the steps above after restarting Wyoming in devices after using wake word once. 

I'm using a USB speakerphone plugged directly into my HA server via USB. I wasn't sure if by "sattelte" you meant wireless granted the add on is for USB based devices but just want to give any information I can and not cause confusion.  Same output in add on logs even when debug mode is on. Seems to be working or at least doesn't throw any errors in that log. Had to replicate steps above to see the below errors. 

DEBUG:root:Connection cancelled: 248136146588787
DEBUG:root:Connection cancelled: 248144153326454
DEBUG:root:Connection cancelled: 248152159039471

**Comment by oiml** [comment]
Wyoming integration seems to treat it as a satellite in the logs, but yes, I use a local USB microphone.
This issue is only with the assist microphone addon.

**Comment by mattjoubert** [comment]
Ditto here Anker a360 conference speaker

**Comment by parhamalikhah** [comment]
I have the same problem with the usb microphone, and after restarting the assist microphone, the problem is solved only once

**Comment by asal1842** [comment]
I have the same issue with wake word
When I also used a usb microphone 
It just only detected my wake word once then I should restart my pi or restart my assist microphone to detect again and i also find it if i mute my assist microphone then unmute it also solve the problem but just for once and I should repeat these again and again

**Comment by ErfanCyber10** [comment]
I restarted the Raspberry Pi and my problem was solved only once, but I have to restart the Raspberry Pi to make it work again.

**Comment by dangero2000** [comment]
Using a Zoom H2N as a USB sound-card with a tiny speaker plugged into the headphone jack, speaker model uncertain. I have the same issue.

**Comment by tek79** [comment]
Same issue with my AV Access AnyCo A3 USB conference speaker. Started with the February releases for me. Rolling back to January again.

**Comment by thomasdupkavich94** [comment]
anyone find a solution to this? im getting the same issue.

**Comment by pako-github** [comment]
I have exactly the same issue.

**Comment by Arkasha-P** [comment]
У меня тоже самое, помогает тока перезапуск дополнения и то на 1 раз !

**Comment by micseydel** [comment]
I don't know how useful this is but please let me know if it's not because testing is flaky
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service assist_microphone: starting
s6-rc: info: service assist_microphone successfully started
s6-rc: info: service discovery: starting
DEBUG:root:Namespace(mic_uri=None, mic_command='arecord -r 16000 -c 1 -f S16_LE -t raw', mic_command_rate=16000, mic_command_width=2, mic_command_channels=1, mic_command_samples_per_chunk=1024, mic_volume_multiplier=1.0, mic_noise_suppression=0, mic_auto_gain=5, snd_uri=None, snd_command='aplay -r 16000 -c 1 -f S16_LE -t raw', snd_command_rate=16000, snd_command_width=2, snd_command_channels=1, snd_volume_multiplier=0.5, wake_uri=None, wake_word_name=[], wake_command=None, wake_command_rate=16000, wake_command_width=2, wake_command_channels=1, vad=False, vad_threshold=0.5, vad_trigger_level=1, vad_buffer_seconds=2, vad_wake_word_timeout=5.0, event_uri=None, startup_command=None, detect_command=None, detection_command=None, transcript_command=None, stt_start_command=None, stt_stop_command=None, synthesize_command=None, tts_start_command=None, tts_stop_command=None, streaming_start_command=None, streaming_stop_command=None, error_command=None, awake_wav='/usr/src/sounds/awake.wav', done_wav='/usr/src/sounds/done.wav', uri='tcp://0.0.0.0:10700', name='assist microphone', area=None, no_zeroconf=True, zeroconf_name=None, zeroconf_host=None, debug=True)
INFO:root:Ready
DEBUG:root:Connecting to mic service: ['arecord', '-r', '16000', '-c', '1', '-f', 'S16_LE', '-t', 'raw']
DEBUG:root:Connecting to snd service: ['aplay', '-r', '16000', '-c', '1', '-f', 'S16_LE', '-t', 'raw']
INFO:root:Connected to services
DEBUG:root:Using webrtc audio enhancements
DEBUG:root:Connected to mic service
Recording raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
DEBUG:root:Server set: 53014131066653
INFO:root:Streaming audio
[09:18:53] INFO: Successfully sent discovery information to Home Assistant.
s6-rc: info: service discovery successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
DEBUG:root:Wake word detected
DEBUG:root:Connected to snd service
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
DEBUG:root:Event(type='transcript', data={'text': ' Turn off the light by the TV.'}, payload=None)
INFO:root:Streaming audio
DEBUG:root:Connected to snd service
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
DEBUG:root:Event(type='synthesize', data={'text': 'Turned off the light', 'voice': {'name': 'en_US-hfc_female-medium'}}, payload=None)
DEBUG:root:Connected to snd service
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
DEBUG:root:Server disconnected
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-12' coro=<AsyncEventHandler.run() done, defined at /usr/local/lib/python3.11/dist-packages/wyoming/server.py:28> exception=ConnectionResetError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wyoming/server.py", line 31, in run
    event = await async_read_event(self.reader)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wyoming/event.py", line 77, in async_read_event
    json_line = await reader.readline()
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/streams.py", line 545, in readline
    line = await self.readuntil(sep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/streams.py", line 637, in readuntil
    await self._wait_for_data('readuntil')
  File "/usr/lib/python3.11/asyncio/streams.py", line 522, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 995, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
DEBUG:root:Server set: 53531309764631
INFO:root:Streaming audio
DEBUG:root:Wake word detected
DEBUG:root:Connected to snd service
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
DEBUG:root:Event(type='transcript', data={'text': ' Turn off the light by the TV.'}, payload=None)
INFO:root:Streaming audio
DEBUG:root:Connected to snd service
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
DEBUG:root:Event(type='synthesize', data={'text': 'Turned off the light', 'voice': {'name': 'en_US-hfc_female-medium'}}, payload=None)
DEBUG:root:Connected to snd service
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
DEBUG:root:Server disconnected
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-66' coro=<AsyncEventHandler.run() done, defined at /usr/local/lib/python3.11/dist-packages/wyoming/server.py:28> exception=ConnectionResetError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wyoming/server.py", line 31, in run
    event = await async_read_event(self.reader)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wyoming/event.py", line 77, in async_read_event
    json_line = await reader.readline()
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/streams.py", line 545, in readline
    line = await self.readuntil(sep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/streams.py", line 637, in readuntil
    await self._wait_for_data('readuntil')
  File "/usr/lib/python3.11/asyncio/streams.py", line 522, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 995, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
DEBUG:root:Server set: 53553571805382
INFO:root:Streaming audio
```

**Comment by synesthesiam** [comment]
@synesthesiam Tagging myself to take a look

**Comment by krisatmanning** [comment]
Same issue. I have an M5 Atom Echo. From the ESP32Home Integration, if I toggle off and on the "Use Wake Word" from the atom echo config page it lets me say "OK, Nabu" one time. Togging off and on allows one time, then it quits.

**Comment by MathisP75** [comment]
It seems like this is still an issue? I have this problem with my M5 Atom Echo.

**Comment by krisatmanning** [comment]
Yep I think so. I haven’t tried in ages though to be honest.

On May 4, 2025, at 8:37 PM, MathisP75 ***@***.***> wrote:

[https://avatars.githubusercontent.com/u/98901170?s=20&v=4]MathisP75 left a comment (home-assistant/addons#3464)<https://github.com/home-assistant/addons/issues/3464#issuecomment-2849704306>

It seems like this is still an issue? I have this problem with my M5 Atom Echo.

**Comment by Juniper-Berries** [comment]
I'm looking into getting an HA green and voice functionality is important for me - has this issue been resolved?

**Comment by micseydel** [comment]
@synesthesiam, was this tested as resolved?

**Comment by Craigydbuzzbitt** [comment]
I'm still receiving this issue now. Any luck with a fix yet?
