### ISSUE TITLE
Unable to pair matter device (network unreachable)

### ISSUE THREAD

**Issue by rbeumer** [home-assistant/addons#3479]
### Describe the issue you are experiencing

I'm trying to pair an Aqara P2 door sensor with my Home Assistant using a Skyconnect dongle. When putting the sensor in paring mode and trying to add it to HA as a Matter device the process fails with "something went wrong". All the previous steps succeed, up to "adding to Home Assistant".

When checking the logs of the Matter server addon I'm seeing the following errors:

```
2024-02-21 15:47:09 core-matter-server matter_server.server.device_controller[126] INFO Starting Matter commissioning using Node ID 5 and IP fd1a:2dfb:d4b:1:fdb5:872c:b891:cf2c (attempt 1/3).
2024-02-21 15:47:09 core-matter-server matter_server.server.client_handler[126] ERROR [548211341712] SDK Error during handling message: CommandMessage(message_id='5f18fec8b4ef4f778ac33ef8de04dbc1', command='commission_on_network', args={'setup_pin_code': [REDACTED], 'ip_addr': 'fd1a:2dfb:d4b:1:fdb5:872c:b891:cf2c'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/client_handler.py", line 193, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 351, in commission_on_network
    success = await self._call_sdk(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 1058, in _call_sdk
    await self.server.loop.run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chip/ChipDeviceCtrl.py", line 1759, in CommissionIP
    self._ChipStack.CallAsync(
  File "/usr/local/lib/python3.11/site-packages/chip/ChipStack.py", line 383, in CallAsync
    raise res.to_exception()
chip.exceptions.ChipStackError: src/inet/UDPEndPointImplSockets.cpp:417: OS Error 0x02000065: Network is unreachable
```

The IPv6 ULA subnets specified in the error are not present on Home Assistant (checked via the terminal with `ip -6 addr`) or somewhere else on my network.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Matter Server

### What is the version of the add-on?

5.1.2

### Steps to reproduce the issue

1. try to pair an Aqara P2 sensor with Home Assistant

### System Health information

 There are currently no repairs available 

### Anything in the Supervisor logs that might be useful for us?

```txt
no relevant logs
```

### Anything in the add-on logs that might be useful for us?

```txt
2024-02-21 15:47:09 core-matter-server matter_server.server.device_controller[126] INFO Starting Matter commissioning using Node ID 5 and IP fd1a:2dfb:d4b:1:fdb5:872c:b891:cf2c (attempt 1/3).
2024-02-21 15:47:09 core-matter-server matter_server.server.client_handler[126] ERROR [548211341712] SDK Error during handling message: CommandMessage(message_id='5f18fec8b4ef4f778ac33ef8de04dbc1', command='commission_on_network', args={'setup_pin_code': [REDACTED], 'ip_addr': 'fd1a:2dfb:d4b:1:fdb5:872c:b891:cf2c'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/client_handler.py", line 193, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 351, in commission_on_network
    success = await self._call_sdk(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 1058, in _call_sdk
    await self.server.loop.run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/chip/ChipDeviceCtrl.py", line 1759, in CommissionIP
    self._ChipStack.CallAsync(
  File "/usr/local/lib/python3.11/site-packages/chip/ChipStack.py", line 383, in CallAsync
    raise res.to_exception()
chip.exceptions.ChipStackError: src/inet/UDPEndPointImplSockets.cpp:417: OS Error 0x02000065: Network is unreachable
```

**Comment by rbeumer** [comment]
Long story short, it was my Nanoleaf Shapes that was sending router advertisements for the fd1a network. I'm not using it as a border router but somehow it is being used in the commissioning process.
