### ISSUE TITLE
2.4.5 - manifest unknown

### ISSUE THREAD

**Issue by simonepittis** [home-assistant/addons#3541]
### Describe the issue you are experiencing

Failed to call service update/install. Error updating Silicon Labs Multiprotocol: Can't install homeassistant/aarch64-addon-silabs-multiprotocol:2.4.5: 404 Client Error for http+docker://localhost/v1.43/images/create?tag=2.4.5&fromImage=homeassistant%2Faarch64-addon-silabs-multiprotocol&platform=linux%2Farm64: Not Found ("manifest for homeassistant/aarch64-addon-silabs-multiprotocol:2.4.5 not found: manifest unknown: manifest unknown")

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Silicon Labs Multiprotocol

### What is the version of the add-on?

2.4.5

### Steps to reproduce the issue

on upgrade addon request

## System Information

version | core-2024.3.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.73-haos-raspi
arch | aarch64
timezone | Europe/Oslo
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1477
Downloaded Repositories | 65

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 49

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | December 4, 2024 at 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-2.ui.nabu.casa
certificate_status | ready
instance_id | 9bf6bfe6548f4eefb7793026aa85f000
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.03.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 28.5 GB
disk_used | 14.1 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (17.2.0), Silicon Labs Multiprotocol (2.4.4), AppDaemon (0.16.4), Matter Server (5.5.1), zabbix-agent (1.5), Whisper (2.0.0), Piper (1.5.0), ESPHome (2024.3.1), SNMP Sensor Server (1.3.5.1), openWakeWord (1.10.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 37
views | 18
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 26, 2024 at 08:58
-- | --
current_recorder_run | April 1, 2024 at 19:24
estimated_db_size | 1661.66 MiB
database_engine | mysql
database_version | 11.2.3

</details>

<details><summary>Sonoff</summary>

version | 3.6.0 (8dd8af9)
-- | --
cloud_online | 0 / 2
local_online | 0 / 0

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
2024-04-03 14:32:24.841 INFO (MainThread) [supervisor.backups.manager] Backup 0053cdcf starting stage addon_repositories
2024-04-03 14:32:24.842 INFO (MainThread) [supervisor.backups.manager] Backup 0053cdcf starting stage docker_config
2024-04-03 14:32:24.842 INFO (MainThread) [supervisor.backups.manager] Creating new partial backup with slug 0053cdcf
2024-04-03 14:32:24.846 INFO (MainThread) [supervisor.backups.manager] Backup 0053cdcf starting stage addons
2024-04-03 14:32:24.890 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_silabs_multiprotocol
2024-04-03 14:32:24.904 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_silabs_multiprotocol
2024-04-03 14:32:24.906 INFO (MainThread) [supervisor.backups.manager] Backup 0053cdcf starting stage finishing_file
2024-04-03 14:32:24.918 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug 0053cdcf completed
2024-04-03 14:32:24.920 INFO (MainThread) [supervisor.docker.addon] Updating image homeassistant/aarch64-addon-silabs-multiprotocol:2.4.4 to homeassistant/aarch64-addon-silabs-multiprotocol:2.4.5
2024-04-03 14:32:24.921 INFO (MainThread) [supervisor.docker.interface] Downloading docker image homeassistant/aarch64-addon-silabs-multiprotocol with tag 2.4.5.
2024-04-03 14:32:26.513 ERROR (MainThread) [supervisor.docker.interface] Can't install homeassistant/aarch64-addon-silabs-multiprotocol:2.4.5: 404 Client Error for http+docker://localhost/v1.43/images/create?tag=2.4.5&fromImage=homeassistant%2Faarch64-addon-silabs-multiprotocol&platform=linux%2Farm64: Not Found ("manifest for homeassistant/aarch64-addon-silabs-multiprotocol:2.4.5 not found: manifest unknown: manifest unknown")
```

### Anything in the add-on logs that might be useful for us?

```txt
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:239
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 14:29:41 (4 occurrences)
Last logged: 14:32:26

[546843877824] Error updating Silicon Labs Multiprotocol: Can't install homeassistant/aarch64-addon-silabs-multiprotocol:2.4.5: 404 Client Error for http+docker://localhost/v1.43/images/create?tag=2.4.5&fromImage=homeassistant%2Faarch64-addon-silabs-multiprotocol&platform=linux%2Farm64: Not Found ("manifest for homeassistant/aarch64-addon-silabs-multiprotocol:2.4.5 not found: manifest unknown: manifest unknown")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 58, in _wrapper
    data = await funct(*argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 135, in async_update_addon
    return await hassio.send_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 592, in send_command
    raise HassioAPIError(error.get(ATTR_MESSAGE))
homeassistant.components.hassio.handler.HassioAPIError: Can't install homeassistant/aarch64-addon-silabs-multiprotocol:2.4.5: 404 Client Error for http+docker://localhost/v1.43/images/create?tag=2.4.5&fromImage=homeassistant%2Faarch64-addon-silabs-multiprotocol&platform=linux%2Farm64: Not Found ("manifest for homeassistant/aarch64-addon-silabs-multiprotocol:2.4.5 not found: manifest unknown: manifest unknown")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2319, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2356, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 905, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 161, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 465, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Silicon Labs Multiprotocol: Can't install homeassistant/aarch64-addon-silabs-multiprotocol:2.4.5: 404 Client Error for http+docker://localhost/v1.43/images/create?tag=2.4.5&fromImage=homeassistant%2Faarch64-addon-silabs-multiprotocol&platform=linux%2Farm64: Not Found ("manifest for homeassistant/aarch64-addon-silabs-multiprotocol:2.4.5 not found: manifest unknown: manifest unknown")
```

**Comment by simonepittis** [comment]
fixed"
