### ISSUE TITLE
Matter 6.1 error at update process

### ISSUE THREAD

**Issue by gt026328** [home-assistant/addons#3629]
### Describe the issue you are experiencing

Update from Matter Server V.6.0 to V 6.1 stopps with error

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Matter Server

### What is the version of the add-on?

6.1

### Steps to reproduce the issue

1. Starting to update from 6.0 to 6.1
2.
3.
...

### System Health information

no repairs

### Anything in the Supervisor logs that might be useful for us?

```txt
2024-06-06 07:28:59.440 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548088431520] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 168, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 57, in _wrapper
    data = await funct(*argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 134, in async_update_addon
    return await hassio.send_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 599, in send_command
    raise HassioAPIError(error.get(ATTR_MESSAGE))
homeassistant.components.hassio.handler.HassioAPIError: Can't install homeassistant/aarch64-addon-matter-server:6.1.0: 500 Server Error for http+docker://localhost/v1.44/images/create?tag=6.1.0&fromImage=homeassistant%2Faarch64-addon-matter-server&platform=linux%2Farm64: Internal Server Error ("Head "https://registry-1.docker.io/v2/homeassistant/aarch64-addon-matter-server/manifests/6.1.0": Get "https://auth.docker.io/token?scope=repository%3Ahomeassistant%2Faarch64-addon-matter-server%3Apull&service=registry.docker.io": EOF")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 977, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1049, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 461, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 170, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Matter Server: Can't install homeassistant/aarch64-addon-matter-server:6.1.0: 500 Server Error for http+docker://localhost/v1.44/images/create?tag=6.1.0&fromImage=homeassistant%2Faarch64-addon-matter-server&platform=linux%2Farm64: Internal Server Error ("Head "https://registry-1.docker.io/v2/homeassistant/aarch64-addon-matter-server/manifests/6.1.0": Get "https://auth.docker.io/token?scope=repository%3Ahomeassistant%2Faarch64-addon-matter-server%3Apull&service=registry.docker.io": EOF")
```

### Anything in the add-on logs that might be useful for us?

```txt
2024-06-06 07:28:59.440 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548088431520] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 168, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 57, in _wrapper
    data = await funct(*argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 134, in async_update_addon
    return await hassio.send_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 599, in send_command
    raise HassioAPIError(error.get(ATTR_MESSAGE))
homeassistant.components.hassio.handler.HassioAPIError: Can't install homeassistant/aarch64-addon-matter-server:6.1.0: 500 Server Error for http+docker://localhost/v1.44/images/create?tag=6.1.0&fromImage=homeassistant%2Faarch64-addon-matter-server&platform=linux%2Farm64: Internal Server Error ("Head "https://registry-1.docker.io/v2/homeassistant/aarch64-addon-matter-server/manifests/6.1.0": Get "https://auth.docker.io/token?scope=repository%3Ahomeassistant%2Faarch64-addon-matter-server%3Apull&service=registry.docker.io": EOF")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 977, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1049, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 461, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 170, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Matter Server: Can't install homeassistant/aarch64-addon-matter-server:6.1.0: 500 Server Error for http+docker://localhost/v1.44/images/create?tag=6.1.0&fromImage=homeassistant%2Faarch64-addon-matter-server&platform=linux%2Farm64: Internal Server Error ("Head "https://registry-1.docker.io/v2/homeassistant/aarch64-addon-matter-server/manifests/6.1.0": Get "https://auth.docker.io/token?scope=repository%3Ahomeassistant%2Faarch64-addon-matter-server%3Apull&service=registry.docker.io": EOF")
```

**Comment by gt026328** [comment]
additional Information from supervisor log:
2024-06-06 07:28:59.432 ERROR (MainThread) [supervisor.docker.interface] Can't install homeassistant/aarch64-addon-matter-server:6.1.0: 500 Server Error for http+docker://localhost/v1.44/images/create?tag=6.1.0&fromImage=homeassistant%2Faarch64-addon-matter-server&platform=linux%2Farm64: Internal Server Error ("Head "https://registry-1.docker.io/v2/homeassistant/aarch64-addon-matter-server/manifests/6.1.0": Get "https://auth.docker.io/token?scope=repository%3Ahomeassistant%2Faarch64-addon-matter-server%3Apull&service=registry.docker.io": EOF")

**Comment by gt026328** [comment]
Now the setup process run without some issues. 
Thanks for grat work you are doing all the time

Add-on: Matter Server
 Matter WebSocket Server for Home Assistant Matter support.
-----------------------------------------------------------
 Add-on version: 6.1.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.3  (aarch64 / raspberrypi5-64)
 Home Assistant Core: 2024.6.0
 Home Assistant Supervisor: 2024.06.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
