### ISSUE TITLE
LetsEncrypt fails to renew via DNSimple

### ISSUE THREAD

**Issue by rspeicher** [home-assistant/addons#3822]
### Describe the issue you are experiencing

At some point within the last three months -- when the addon successfully renewed the current certificate used in my HA instance -- I've started seeing a 400 error:

```
[13:19:25] INFO: Selected DNS Provider: dns-dnsimple
[13:19:25] INFO: Use propagation seconds: 60
[13:19:25] INFO: Detecting existing certificate type for [redacted]
Saving debug log to /var/log/letsencrypt/letsencrypt.log
[13:19:29] INFO: Existing certificate using 'rsa' key type.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Renewing an existing certificate for [redacted]
Error adding TXT record: 400 Client Error: Bad Request for url: https://api.dnsimple.com/v2/[redacted]/zones/[redacted]/records
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
```

I found `/var/log/letsnecrypt/letsencrypt.log` in `./mnt/data/docker/overlay2/a4a2aa228ad19a9f97e8a33951b97ac6b4174960cfd70a5f23e813aab4456e84/diff/var/log/letsencrypt/letsencrypt.log`, but nothing useful there:

<details>
<summary>letsencrypt.log</summary>

```
2024-11-08 13:19:41,081:DEBUG:root:Actual zone name resolved for domain [redacted]: [redacted]
2024-11-08 13:19:41,082:DEBUG:root:Override resolved zone name because --delegated option is set: [redacted]
2024-11-08 13:19:41,649:DEBUG:lexicon._private.providers.dnsimple:list_records: []
2024-11-08 13:19:41,649:DEBUG:lexicon._private.providers.dnsimple:delete_records: []
2024-11-08 13:19:41,649:DEBUG:lexicon._private.providers.dnsimple:delete_record: True
2024-11-08 13:19:41,650:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/certbot/plugins/dns_common_lexicon.py", line 224, in _perform
    operations.create_record(rtype='TXT', name=validation_name, content=validation)
  File "/usr/local/lib/python3.12/site-packages/lexicon/client.py", line 36, in create_record
    return self.provider.create_record(rtype, name, content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/lexicon/_private/providers/dnsimple.py", line 90, in create_record
    payload = self._post(f"/{self.account_id}/zones/{self.domain}/records", record)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/lexicon/interfaces.py", line 171, in _post
    return self._request("POST", url, data=data, query_params=query_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/lexicon/_private/providers/dnsimple.py", line 220, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url:
https://api.dnsimple.com/v2/[redacted]/zones/[redacted]/records

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/certbot/_internal/main.py", line 1894, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/certbot/_internal/main.py", line 1600, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/certbot/_internal/main.py", line 131, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/usr/local/lib/python3.12/site-packages/certbot/_internal/renewal.py", line 399, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
    resps = self.auth.perform(achalls)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/certbot/plugins/dns_common.py", line 76, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/local/lib/python3.12/site-packages/certbot/plugins/dns_common_lexicon.py", line 227, in _perform
    raise errors.PluginError('Error adding TXT record: {0}'.format(e))
certbot.errors.PluginError: Error adding TXT record: 400 Client Error: Bad
Request for url: https://api.dnsimple.com/v2/[redacted]/zones/[redacted]/records
2024-11-08 13:19:41,663:ERROR:certbot._internal.log:Error adding TXT record: 400
Client Error: Bad Request for url: https://api.dnsimple.com/v2/[redacted]/zones/[redacted]/records
```
</details>

The same renewal works if I run certbot on another machine with the same DNSimple token:

```sh
$ certbot --version
certbot 3.0.0

$ certbot certonly \
  --non-interactive \
  --agree-tos \
  --email [redacted] \
  --dns-dnsimple \
  --dns-dnsimple-credentials ./config/dns_dnsimple_credentials.ini \
  -d [redacted] \
  --cert-path ./certs/[redacted].crt \
  --fullchain-path ./certs/[redacted].pem \
  --key-path ./certs/[redacted].key \
  --dry-run

Account registered.
Simulating renewal of an existing certificate for [redacted]
Waiting 30 seconds for DNS changes to propagate
The dry run was successful.
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

5.2.3

### Steps to reproduce the issue

1. Set `challenge` to `dns`
2. Configuration:
   ```
   provider: dns-dnsimple
   dnsimple_token: [token]
   ```

## System Information

version | core-2024.11.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1460
Downloaded Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.2
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 458.4 GB
disk_used | 19.9 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.15.0), Studio Code Server (5.17.3), Let's Encrypt (5.2.3), NGINX Home Assistant SSL proxy (3.11.0), Tailscale (0.23.2), AdGuard Home (5.1.5), TimescaleDB (4.2.0), pgAdmin4 (3.2.0), Silicon Labs Flasher (0.3.0), Matter Server (6.6.0), OpenThread Border Router (2.11.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 3
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 15, 2024 at 10:50 PM
-- | --
current_recorder_run | November 6, 2024 at 9:17 PM
estimated_db_size | 6105.02 MiB
database_engine | postgresql
database_version | 16.3

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
About a dozen entries like


2024-11-10 09:12:25.969 WARNING (MainThread) [supervisor.addons.options] Option 'keytype' does not exist in the schema for Let's Encrypt (core_letsencrypt)
2024-11-10 09:14:05.553 WARNING (MainThread) [supervisor.addons.options] Option 'keytype' does not exist in the schema for Let's Encrypt (core_letsencrypt)
```

### Anything in the add-on logs that might be useful for us?

See issue body.

**Comment by rspeicher** [comment]
And I did try Discord first, but it's unclear if this is a bug or my error: https://discord.com/channels/330944238910963714/1304832441579601992/1304832441579601992

**Comment by rspeicher** [comment]
Welp, don't now if it was upgrading to 2024.11.01, or the restart from upgrading, or just me posting about it here, but this has resolved itself.
