### ISSUE TITLE
Piper does not process a long messages

### ISSUE THREAD

**Issue by gribouk** [home-assistant/addons#3836]
### Describe the issue you are experiencing

Piper is run under HA OS as add-on, but it is being used by the HA on another machine running in a Docker.
If using outher TTS, works well without responce limitation. If using assist with piper TTS:
For short replies it outputs tts for the relevant responces well.
If the message is pretty long, the following error returned:

Error doing job: Exception in callback SpeechManager._async_get_tts_audio.<locals>.handle_error(<Task cancell...nit__.py:761>>) at /usr/src/homeassistant/homeassistant/components/tts/__init__.py:829 (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 831, in handle_error
    if audio_task.exception():
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 771, in get_tts_data
    extension, data = await engine_instance.internal_async_get_tts_audio(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 491, in internal_async_get_tts_audio
    return await self.async_get_tts_audio(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/wyoming/tts.py", line 126, in async_get_tts_audio
    event = await client.read_event()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/wyoming/client.py", line 25, in read_event
    return await async_read_event(self._reader)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/wyoming/event.py", line 79, in async_read_event
    json_line = await reader.readline()
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 568, in readline
    line = await self.readuntil(sep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 660, in readuntil
    await self._wait_for_data('readuntil')
  File "/usr/local/lib/python3.12/asyncio/streams.py", line 545, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Piper

### What is the version of the add-on?

1.5.2

### Steps to reproduce the issue

1. Ask for something which implies long responce, like weather for tomorrow
2. Wait
3. Read the error in the logs
...

### System Health information

There are currently no repairs pending

### Anything in the add-on logs that might be useful for us?

```txt
DEBUG:wyoming_piper.handler:Synthesize(text="Tomorrow's weather forecast includes:\nExpected temperature: zero degrees Celsius throughout the day\nRelative humidity: starting from ninety three percent in the morning, decreasing throughout the day\nAir pressure: gradually decreasing, starting at one thousand two point six hectopascals\nWind speed: expected to remain calm, around zero meters per second for most of the day\nLight precipitation expected in the evening.\n\nIf you need specific details for any time during the day, feel free to ask!", voice=SynthesizeVoice(name='en_US-libritts-high', language=None, speaker=None))
DEBUG:wyoming_piper.handler:synthesize: raw_text=Tomorrow's weather forecast includes:
Expected temperature: zero degrees Celsius throughout the day
Relative humidity: starting from ninety three percent in the morning, decreasing throughout the day
Air pressure: gradually decreasing, starting at one thousand two point six hectopascals
Wind speed: expected to remain calm, around zero meters per second for most of the day
Light precipitation expected in the evening.
If you need specific details for any time during the day, feel free to ask!, text='Tomorrow's weather forecast includes: Expected temperature: zero degrees Celsius throughout the day Relative humidity: starting from ninety three percent in the morning, decreasing throughout the day Air pressure: gradually decreasing, starting at one thousand two point six hectopascals Wind speed: expected to remain calm, around zero meters per second for most of the day Light precipitation expected in the evening.  If you need specific details for any time during the day, feel free to ask!'
DEBUG:wyoming_piper.handler:input: {'text': "Tomorrow's weather forecast includes: Expected temperature: zero degrees Celsius throughout the day Relative humidity: starting from ninety three percent in the morning, decreasing throughout the day Air pressure: gradually decreasing, starting at one thousand two point six hectopascals Wind speed: expected to remain calm, around zero meters per second for most of the day Light precipitation expected in the evening.  If you need specific details for any time during the day, feel free to ask!"}
DEBUG:wyoming_piper.handler:/tmp/tmpv4d0ywnl/1732548855002914313.wav
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='wyoming event handler' coro=<AsyncEventHandler.run() done, defined at /usr/local/lib/python3.11/dist-packages/wyoming/server.py:31> exception=BrokenPipeError(32, 'Broken pipe')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 48, in handle_event
    return await self._handle_event(event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 132, in _handle_event
    await self.write_event(
  File "/usr/local/lib/python3.11/dist-packages/wyoming/server.py", line 29, in write_event
    await async_write_event(event, self.writer)
  File "/usr/local/lib/python3.11/dist-packages/wyoming/event.py", line 131, in async_write_event
    await writer.drain()
  File "/usr/lib/python3.11/asyncio/streams.py", line 378, in drain
    await self._protocol._drain_helper()
  File "/usr/lib/python3.11/asyncio/streams.py", line 167, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wyoming/server.py", line 41, in run
    if not (await self.handle_event(event)):
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 50, in handle_event
    await self.write_event(
  File "/usr/local/lib/python3.11/dist-packages/wyoming/server.py", line 29, in write_event
    await async_write_event(event, self.writer)
  File "/usr/local/lib/python3.11/dist-packages/wyoming/event.py", line 131, in async_write_event
    await writer.drain()
  File "/usr/lib/python3.11/asyncio/streams.py", line 366, in drain
    raise exc
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 1057, in write
    n = self._sock.send(data)
        ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by Sythsaz** [comment]
I wanna say it's a timing issue cause I reinstalled home assistant with a better cpu and that error went away

**Comment by jleach87** [comment]
Errors here, too!

```
DEBUG:wyoming_piper.handler:Synthesize(text='Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.', voice=None)
DEBUG:wyoming_piper.handler:synthesize: raw_text=Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book., text='Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.'
DEBUG:wyoming_piper.handler:input: {'text': 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.'}
DEBUG:wyoming_piper.handler:
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='wyoming event handler' coro=<AsyncEventHandler.run() done, defined at /usr/local/lib/python3.11/dist-packages/wyoming/server.py:31> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wyoming/server.py", line 41, in run
    if not (await self.handle_event(event)):
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 53, in handle_event
    raise err
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 48, in handle_event
    return await self._handle_event(event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 108, in _handle_event
    wav_file: wave.Wave_read = wave.open(output_path, "rb")
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/wave.py", line 630, in open
    return Wave_read(f)
           ^^^^^^^^^^^^
  File "/usr/lib/python3.11/wave.py", line 280, in __init__
    f = builtins.open(f, 'rb')
        ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by Jieper001** [comment]
Same thing happening here.  Restarting the Piper add-on works for a few hours and then below issues resurfaces; no voice feedback anymore.  This is with the Nabu Casa Voice Preview Edition running piper 1.5.2 on HA core 2024.12.5.

ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='wyoming event handler' coro=<AsyncEventHandler.run() done, defined at /usr/local/lib/python3.11/dist-packages/wyoming/server.py:31> exception=BrokenPipeError(32, 'Broken pipe')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 48, in handle_event
    return await self._handle_event(event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 114, in _handle_event
    await self.write_event(
  File "/usr/local/lib/python3.11/dist-packages/wyoming/server.py", line 29, in write_event
    await async_write_event(event, self.writer)
  File "/usr/local/lib/python3.11/dist-packages/wyoming/event.py", line 131, in async_write_event
    await writer.drain()
  File "/usr/lib/python3.11/asyncio/streams.py", line 378, in drain
    await self._protocol._drain_helper()
  File "/usr/lib/python3.11/asyncio/streams.py", line 167, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wyoming/server.py", line 41, in run
    if not (await self.handle_event(event)):
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/handler.py", line 50, in handle_event
    await self.write_event(
  File "/usr/local/lib/python3.11/dist-packages/wyoming/server.py", line 29, in write_event
    await async_write_event(event, self.writer)
  File "/usr/local/lib/python3.11/dist-packages/wyoming/event.py", line 131, in async_write_event
    await writer.drain()
  File "/usr/lib/python3.11/asyncio/streams.py", line 366, in drain
    raise exc
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 1057, in write
    n = self._sock.send(data)
        ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

**Comment by fawzib** [comment]
i have a powerful system and i get the same error. i even tried it with wyoming protocol for an external server and i am getting the same issue. it is not very consistent when it appears but mostly on longer messages. checking debugs shows that piper response is 0s on all successful replies meaning it is not a resource constraint.

**Comment by testercell** [comment]
Same issue here, any fixes found?

**Comment by fawzib** [comment]
this might sound crazy but change your dns to something that doesn't block tracking/ads
somehow, this was my issue and i was able to fix it by changing the DNS.

**Comment by testercell** [comment]
My router doesn't allow DNS to be changed :(

**Comment by fawzib** [comment]
not a big deal, set the dns inside home assistant. disable ipv6 as well. mine below

![Image](https://github.com/user-attachments/assets/92d50ae4-65a9-4575-831e-f181a8421ba9)

**Comment by testercell** [comment]
Disabled ipv6 and set same DNS servers as you. Restarted but still same issue when returning longer tts
