### ISSUE TITLE
Matter Server not starting after update to 6.6.1

### ISSUE THREAD

**Issue by mf76130** [home-assistant/addons#3839]
### Describe the issue you are experiencing

Matter Server is not starting anymore

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Matter Server

### What is the version of the add-on?

6.6.1

### Steps to reproduce the issue

1. Install Matter update
2. restart service

## System Information

version | core-2024.11.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Europe/Vienna
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1533
Downloaded Repositories | 16

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.4
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 234.0 GB
disk_used | 41.9 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi5-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (19.0.0), Samba share (12.3.2), Mosquitto broker (6.4.1), Weather Station MQTT (0.1), Grafana (10.2.2), InfluxDB (5.0.1), Studio Code Server (5.17.3), VLC (0.3.0), Speedtest (1.6.2), File editor (5.8.0), OpenThread Border Router (2.12.1), Matter Server (6.6.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 11
-- | --
resources | 4
views | 23
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 2. November 2024 um 11:01
-- | --
current_recorder_run | 26. November 2024 um 13:59
estimated_db_size | 6487.37 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 291, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
2024-11-26 13:55:13.356 INFO (SyncWorker_7) [supervisor.docker.manager] Cleaning addon_core_matter_server application
2024-11-26 13:55:13.906 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-matter-server with version 6.6.1
2024-11-26 13:55:31.542 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_matter_server
2024-11-26 13:55:48.175 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-239549' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1491> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1505, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 291, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
2024-11-26 13:55:53.848 INFO (SyncWorker_7) [supervisor.docker.manager] Cleaning addon_core_matter_server application
2024-11-26 13:55:54.278 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-matter-server with version 6.6.1
2024-11-26 13:56:12.165 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_matter_server
2024-11-26 13:56:29.024 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-239675' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1491> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1505, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 291, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
2024-11-26 13:57:12.735 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
2024-11-26 13:57:12.922 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
2024-11-26 13:57:12.927 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
2024-11-26 13:58:00.460 INFO (SyncWorker_0) [supervisor.docker.manager] Restarting homeassistant
2024-11-26 13:58:01.659 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API for a0d7b954_vscode closed
2024-11-26 13:59:01.426 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
2024-11-26 13:59:05.078 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-11-26 13:59:05.193 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-11-26 13:59:05.299 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-11-26 13:59:06.440 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to APIState(core_state='NOT_RUNNING', offline_db_migration=False)
2024-11-26 13:59:17.205 INFO (MainThread) [supervisor.host.info] Updating local host information
2024-11-26 13:59:17.636 INFO (MainThread) [supervisor.host.services] Updating service information
2024-11-26 13:59:17.643 INFO (MainThread) [supervisor.host.network] Updating local network information
2024-11-26 13:59:18.005 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
2024-11-26 13:59:18.010 INFO (MainThread) [supervisor.host.manager] Host information reload completed
2024-11-26 13:59:48.044 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to APIState(core_state='RUNNING', offline_db_migration=False)
2024-11-26 13:59:48.045 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
2024-11-26 13:59:49.151 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
2024-11-26 13:59:49.156 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode
2024-11-26 13:59:49.174 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
2024-11-26 14:00:00.138 INFO (SyncWorker_7) [supervisor.docker.manager] Cleaning addon_6b87c29e_speedtest_addon application
2024-11-26 14:00:00.833 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/mrsuicideparrot/hassio-speedtest-addon-aarch64 with version 1.6.2
2024-11-26 14:02:31.000 INFO (SyncWorker_3) [supervisor.docker.manager] Cleaning addon_core_matter_server application
2024-11-26 14:02:31.448 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-matter-server with version 6.6.1
2024-11-26 14:02:40.903 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:5580 ssl:default [Connect call failed ('172.30.32.1', 5580)]
2024-11-26 14:02:43.056 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:5580 ssl:default [Connect call failed ('172.30.32.1', 5580)]
2024-11-26 14:02:44.489 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:5580 ssl:default [Connect call failed ('172.30.32.1', 5580)]
2024-11-26 14:02:45.973 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:5580 ssl:default [Connect call failed ('172.30.32.1', 5580)]
2024-11-26 14:02:49.416 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_matter_server
2024-11-26 14:03:06.039 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-240617' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1491> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1505, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 291, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
2024-11-26 14:03:06.857 INFO (SyncWorker_6) [supervisor.docker.manager] Cleaning addon_core_matter_server application
2024-11-26 14:03:07.246 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-matter-server with version 6.6.1
2024-11-26 14:03:24.929 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_matter_server
2024-11-26 14:03:25.396 INFO (SyncWorker_2) [supervisor.docker.manager] Stopping addon_core_matter_server application
2024-11-26 14:03:36.425 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning addon_core_matter_server application
2024-11-26 14:03:36.853 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-matter-server with version 6.6.1
2024-11-26 14:03:54.666 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_matter_server
2024-11-26 14:04:11.546 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-240934' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1491> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1505, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 291, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
2024-11-26 14:05:07.384 INFO (SyncWorker_7) [supervisor.docker.manager] Cleaning addon_core_matter_server application
2024-11-26 14:05:07.828 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-matter-server with version 6.6.1
2024-11-26 14:05:25.717 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_matter_server
2024-11-26 14:05:42.392 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-241048' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1491> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1505, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 291, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
2024-11-26 14:06:27.818 INFO (SyncWorker_4) [supervisor.docker.manager] Cleaning addon_core_matter_server application
2024-11-26 14:06:28.281 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-matter-server with version 6.6.1
2024-11-26 14:06:46.431 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_matter_server
2024-11-26 14:07:03.220 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-241185' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1491> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1505, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 291, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
```

### Anything in the add-on logs that might be useful for us?

```txt
[Detaching after vfork from child process 247]
2024-11-26 13:56:15.167 (MainThread) INFO [matter_server.server.stack] Initializing CHIP/Matter Logging...
2024-11-26 13:56:15.167 (MainThread) INFO [matter_server.server.stack] Initializing CHIP/Matter Controller Stack...
2024-11-26 13:56:17.297 (MainThread) ERROR [root] Uncaught exception
Traceback (most recent call last):
  File "/usr/local/bin/matter-server", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/matter_server/server/__main__.py", line 220, in main
    server = MatterServer(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/matter_server/server/server.py", line 138, in __init__
    self.stack = MatterStack(self, bluetooth_adapter_id, enable_server_interactions)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/matter_server/server/stack.py", line 108, in __init__
    chip.native.Init(999 if bluetooth_adapter_id is None else bluetooth_adapter_id)
  File "/usr/local/lib/python3.12/site-packages/chip/native/__init__.py", line 254, in Init
    handle = _GetLibraryHandle(Library.CONTROLLER, False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/chip/native/__init__.py", line 227, in _GetLibraryHandle
    handle = _Handle(ctypes.CDLL(FindNativeLibraryPath(lib)))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /usr/local/lib/python3.12/site-packages/chip/_ChipDeviceCtrl.so)
[Thread 0x7ff2d6f180 (LWP 246) exited]
[Inferior 1 (process 244) exited with code 01]
No stack.
[12:56:17] WARNING: matter-server service exited with code 1 (by signal 0).
```

**Comment by mf76130** [comment]
ok, "fixed" it myself. Just turned off "Use the latest beta version" now its working again

**Comment by agners** [comment]
There has been a beta release which didn't work in the add-on environment due to glibc versioning issues. We've temporarily reverted the Matter SDK update and released another beta, so the add-on should work again with the beta flag set.

See also: https://github.com/home-assistant-libs/python-matter-server/releases/tag/6.7.0b2

There will be another beta with the latest Matter SDK which will work with the add-on.

This is not an add-on issue per-se, so closing this report.
